### ISSUE TITLE
Running `gb` alone should produce usage text, including available subcommands

### ISSUE THREAD

**Issue by peterbourgon** [constabulary/gb#1]
Input: 

```bash
$ gb
```

Output: 

```bash
2015/04/27 11:00:39 no command supplied
```

Expected output:

```
Usage:
  gb [flags] build [package] - builds a package
  gb [flags] test [package]  - tests a package

Flags:
  -goarch="amd64": override GOARCH
  -goos="darwin": override GOOS
  -goroot="/Users/peter/src/go.googlesource.com/go": override GOROOT
  -q=false: suppress log messages below ERROR level
  -toolchain="gc": choose go compiler toolchain
  -v=false: enable log levels below INFO level
```

**Comment by mariokostelac** [comment]
@constabulary do you want me to do that?

**Comment by davecheney** [comment]
@mariokostelac sure, i'm working on #5 at the moment as part of getting more complicated patterns to work.

A note of advice, this shouldn't just be a dead blob of text, it should consume data from the registered commands and produce the information dynamically -- you can change the main.Command interface in any way you choose to do so.

**Comment by mariokostelac** [comment]
@davecheney ok, i'll look at the similar tools and the way how they do that.

**Comment by mariokostelac** [comment]
Also, I will catch some time for that next week, probably not sooner. Sorry if that's too late.
