### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by andrewchambers** [constabulary/gb#104]
Imo there is a good opportunity to make a well designed package system which uses git tags as package versions, and each package has a .json file. This would work well as a gb plugin.

I think stealing the way dart pub works https://www.dartlang.org/tools/pub/get-started.html is a good idea. The associated pubspec.lock approach is an elegant way to tackle published versions and package updates.

 We can run a simple package repository on GCE/appengine which just hosts json files. All source code will be hosted and accessed via git/mercurial/etc tags. Package names would probably just be published as username/packagename to avoid name collisions.

A plugin like this would create the equivalent of rust cargo. We should not distribute precompiled binaries, only source code which is checked out into the vendor directory after a source code clone.

**Comment by andrewchambers** [comment]
The git tags could be specially named so they do not conflict with a project. i.e. gopackage-1.1.1 .

**Comment by andrewchambers** [comment]
I imagine the package file something like this:
```
{
"name": "my-package",
"type" :  "library",
"url": "https://github.com/path/to/package",
"dependencies" : [ { "name" : "andrewc/lib", "versions" : ["1.1.1", "1.2.3"] }, { "name" : "andrewc/lib2", "versions" : ["any"] }  ]
}
```

The key part is the ability for the plugin to find the most up  to date combination of library versions which work together automatically.

**Comment by davecheney** [comment]
Thanks @andrewchambers 

There are a few things as part of this request, so I'll address them separately.

> Imo there is a good opportunity to make a well designed package system which uses git tags as package versions, and each package has a .json file. This would work well as a gb plugin.

It's clear to me that I cannot hold the line of "just use git sub<mumble>" for much longer. Once gb is feature complete (cgo, tags support) then I'll be focusing on replacing gb-vendor with something that can fetch, record and update dependencies from their repos.

What I believe you are talking about is a process by which Go packages are _released_. That is not something that I want gb to do, but I realise that a plugin could be written to tag, and push to _somewhere_ a released version of a Go package.

To reiterate what I have said elsewhere, Go packages do not have version. Go packages may be known to source control which tracks changes to those packages with _revisions_, and this is an independent concept. This is not to say that releasing Go packages is not a good idea, it's just not core to what gb does.

> We can run a simple package repository on GCE/appengine which just hosts json files. All source code will be hosted and accessed via git/mercurial/etc tags. Package names would probably just be published as username/packagename to avoid name collisions.

To be clear, I have no intention of writing or hosting a central package repository for Go packages.

**Comment by andrewchambers** [comment]
I agree gb shouldn't need to care about the tool used for this. I think GB is a bit more flexible as a platform for a tool like this than the vanilla go tool though, which Is why I created an issue here.

I am just hoping people can gather around a common and intelligent pattern for doing this so we don't end up with a fragmented ecosystem. We all have limited free time, so perhaps there are other people reading this and who want this sort of feature can team up with me to work on it separately, but with an eye on integration with this project.

**Comment by andrewchambers** [comment]
Further thoughts:

We actually shouldn't make a central package repo. We should make a distributed package repository where the published package metadata itself is in the git repo. The published versions are named git tags, and we access packages via url.

*Goes off to prototype*

**Comment by davecheney** [comment]
I agree completely. Please don't take this the wrong way. I am closing this issue because it is not something that _gb_ will do in the foreseeable future. 

Please don't interpret this as a rejection of the idea; you can write your own gb plugins without them needing to be integrated into the codebase.

**Comment by andrewchambers** [comment]
No problem, I will post back here with a link to prototype repo where brainstorming and discussion can continue without cluttering this so prematurely.

**Comment by davecheney** [comment]
Please take this discussion to the go-pm mailing list. It would be more
appropriate there.
