### ISSUE TITLE
github.com/skelterjohn/go-gb :(

### ISSUE THREAD

**Issue by skelterjohn** [constabulary/gb#11]
I am disappointed that you are reusing the name of my build tool without letting me know :(

**Comment by skelterjohn** [comment]
I also wish this could have been issue #9.

**Comment by davecheney** [comment]
I am sorry, I should have consulted with you first.

I honestly thought that gb died years ago, killed off by the go tool.

**Comment by skelterjohn** [comment]
It did, and I have no core problem with you reusing the name, just would have liked a heads up for a formal passing of the baton. Particularly poignant since I recently started working on a similar tool and called it gb at first :) though now it's called wgo.
