### ISSUE TITLE
gb env infinite loop

### ISSUE THREAD

**Issue by o172** [constabulary/gb#119]
Plugin gb-env passes an empty string for parameter projectroot to cmd.RunCommand() which seems to cause FindProjectRoot() to go into an infinite loop, depending on the actual current directory (seen on os x). 

I note that other plugins pass os.Getenv("GB_PROJECT_DIR") for this parameter. But since gb-env is specifically about environment variables I'm not sure if that's correct here.

**Comment by davecheney** [comment]
Thanks for the error report and diagnosing the problem. I'll fix it.

**Comment by cryptix** [comment]
I've seen this as well but couldn't figure out the cause. Sometimes it keeps trying to traverse on `.`.
