### ISSUE TITLE
command "build" failed: run ../pack r pkg.a

### ISSUE THREAD

**Issue by cryptix** [constabulary/gb#12]
Hi!

I started to convert a bigger project of mine but I tripped over one of it's dependencies. 

This is what I got when I made a new gb project for the dependency:

```
[cryptix@higgs ~] mkdir devel/cznicZappy
[cryptix@higgs ~] cd devel/cznicZappy 
[cryptix@higgs ~/devel/cznicZappy] mkdir -p src/github.com/cznic/zappy
[cryptix@higgs ~/devel/cznicZappy] git clone -1 https://github.com/cznic/zappy src/github.com/cznic/zappy 
[cryptix@higgs ~/devel/cznicZappy] gb build all
2015/04/29 13:38:59 INFO project root "/home/cryptix/devel/cznicZappy"
2015/04/29 13:38:59 INFO compile github.com/cznic/zappy [decode.go encode.go zappy.go]
2015/04/29 13:38:59 INFO pack [[compile {zappy github.com/cznic/zappy /home/cryptix/devel/cznicZappy/src/github.com/cznic/zappy}]]
2015/04/29 13:38:59 INFO build duration: 4.985918ms map[compile:3.364623ms pack:712.983µs]
2015/04/29 13:38:59 command "build" failed: run: [/home/cryptix/gosrc/pkg/tool/linux_amd64/pack r /tmp/gb213012010/github.com/cznic/zappy.a]: [/home/cryptix/gosrc/pkg/tool/linux_amd64/pack r /tmp/gb213012010/github.com/cznic/zappy.a]: exit status 2
[cryptix@higgs ~/devel/cznicZappy] 
```

Running the last command by hand gave me this:

```
[cryptix@higgs /tmp/gb213012010] /home/cryptix/gosrc/pkg/tool/linux_amd64/pack r /tmp/gb213012010/github.com/cznic/zappy.a 
Usage: pack op file.a [name....]
Where op is one of cprtx optionally followed by v for verbose output.
For compatibility with old Go build environments the op string grc is
accepted as a synonym for c.

For more information, run
	godoc cmd/pack
[cryptix@higgs /tmp/gb213012010] 

[cryptix@higgs /tmp/gb213012010] file /tmp/gb213012010/github.com/cznic/zappy.a
/tmp/gb213012010/github.com/cznic/zappy.a: current ar archive
```

I've added a `Debugf` to `runOut` to get the stderr output and pasted the verbose run [here](https://gist.github.com/cryptix/89196e5f15e608d08bdb).

i really like the idea and approach you have taken. I hope it takes off. Sadly, I missed your talk even though I was in the Berlin at the time...

**Comment by davecheney** [comment]
Which version of Go are you running, i've tested with 1.4 and 1.5. Also,
cgo support doesn't work properly yet, that could explain the failure.

**Comment by cryptix** [comment]
I used go 1.4.2 for this. Yes it's a cgo issue but his dependency has a build tag for a pure go build. Are `go build -tags` supported?

**Comment by davecheney** [comment]
Not yet, give me a day to get the cgo code working.

**Comment by cryptix** [comment]
Perfect, no problemo! :+1:

I have other projects to play with in the meantime. :smile:

**Comment by freeformz** [comment]
I ran into this too converting a project with cgo deps.

**Comment by cryptix** [comment]
@davecheney Sorry, but I don't see how #95 fixes this.

AFAICT cgo is still not supported. Are `go build -tags` just a special form of `-ldflags`? If so, how do I use them like that?

**Comment by davecheney** [comment]
cgo is not supported (yet), I added an explicit error, this might not have been in #95. Sorry about that.

**Comment by davecheney** [comment]
> Are go build -tags just a special form of -ldflags? If so, how do I use them like that?

`-ldflags` is used to pass flags to the linker, people use them to set things like the git version their project was built with. They are unrelated to `-tags`

**Comment by cryptix** [comment]
> They are unrelated to `-tags`

Ok, that was my understanding, too which is why the closing of this issue confused me.

I guess, I'll track #92 for CGO support?

**Comment by cryptix** [comment]
Just a little shout out: [ql](https://github.com/cznic/ql) and it's deps now build fine (tested on linux/amd64)

**Comment by dinedal** [comment]
Hi, wondering if there are still plans for `cgo` support?

**Comment by davecheney** [comment]
Hi Paul,

Cgo support is mostly working these days. With the exception of this issue
and one other one that is waiting for confirmation, there are no other open
cgo issues.

Could you please test your project and raise an issue if you encounter bugs.

Thanks

Dave

**Comment by dinedal** [comment]
I was directed to this issue by a failure when I attempted to use gb for my project:

```bash
~/go/src/github.com/dinedal/textql(feature/v2 ✔) gb build
github.com/youtube/vitess/go/hack
github.com/dinedal/textql/inputs
github.com/dinedal/textql/outputs
github.com/dinedal/textql/util
github.com/dinedal/textql/test_util
github.com/youtube/vitess/go/bytes2
github.com/youtube/vitess/go/bson
github.com/youtube/vitess/go/sqltypes
github.com/dinedal/textql/sqlparser
github.com/dinedal/textql
FATAL command "build" failed: github.com/mattn/go-sqlite3: cgo not suppored, see https://github.com/constabulary/gb/issues/12
```

**Comment by davecheney** [comment]
Hi Paul,

I think you have an outdated version. Gb is moving very quickly, please
update to the latest available.

http://getgb.io/docs/install/

Thanks

Dave

**Comment by dinedal** [comment]
D'oh, sorry to have bothered you :) that worked, thanks!

**Comment by davecheney** [comment]
S'ok, not your fault. Hopefully before the end of the year gb will have a
more predictable release story.
