### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by manveru** [constabulary/gb#13]
Is there some kind of `gb test`?

**Comment by davecheney** [comment]
Yes, `gb test` works. There are some bugs an limitations at the moment, for example external tests aren't working yet.

**Comment by manveru** [comment]
With external tests you mean things that depend on a testing library? Because I get `panic: could not locate package: github.com/stretchr/testify/assert` here, even though it's in `src/github.com/stretchr/testify/assert`.

**Comment by davecheney** [comment]
An external test is `package something_test`. I'll look at improving this
tomorrow. There are also problems with ensuring all the various test
depdendencies are resolved before building.
