### ISSUE TITLE
GOPATH with underscore failed

### ISSUE THREAD

**Issue by rbucker** [constabulary/gb#133]
A number of things went wrong. a) I had 3 paths in my GOPATH and it did not use them or all of them. b) the '_' underscore was removed

root@pcore3 ~/src/bitbucket.org/netcentrix/gwtcmp $gb test ./...
FATAL command "test" failed: failed to resolve package "bitbucket.org/netcentrix/gwtcmp/cmd": cannot find package "bitbucket.org/netcentrix/encoding/prospero" in any of:
        /usr/lib/golang/src/bitbucket.org/netcentrix/encoding/prospero (from $GOROOT)
        /root/src/bitbucket.org/netcentrix/encoding/prospero (from $GOPATH)
        /root/vendor/src/bitbucket.org/netcentrix/encoding/prospero
root@pcore3 ~/src/bitbucket.org/netcentrix/gwtcmp $echo $GOPATH
/root/_vendor:/root:/root/src/bitbucket.org/netcentrix/gwtcmp/_vendor

**Comment by davecheney** [comment]
gb is backward compatible with GOPATH in that GOPATH elements look like gb projects (without a vendor/ subdirectory). gb doesn't consume all the elements of GOPATH, the goal is to encourage people who want reliable builds to move away from GOPATH.

The second issue is a symptom of the first, bitbucket.org/netcentrix/encoding/prospero was not inside the detected project root (I'm guessing it is in /root/_vendor/src/bitbucket.org/netcentrix/encoding/prospero).

**Comment by rbucker** [comment]
ok, 

//-SLIGHTLY OFF TOPIC-// I do not want to suggest that the go-way is better than the gb-way, however, unless gb is going to be incorporated into the go tools (with or without a feature flag) then I will have to install gb and it's plugins as part of my environment; which flies in the face of vendoring, simple and elegant environments. (feel free to close; thank you)

**Comment by davecheney** [comment]
Based on the information I have available to me, gb will not be shipped with any Go distribution.
