### ISSUE TITLE
Suggestion: gb-vendor to optionally pull in vendored package's dependencies

### ISSUE THREAD

**Issue by jtolds** [constabulary/gb#139]
Hi! gb is rapidly getting so much awesomer! I <3 the new gb-vendor fetch. The addition of gb-vendor fetch makes gb that much closer to the dreams I was having for gb a week ago but forgot to say anything.

So I'm filing three tickets. Happy to send pull requests but want to discuss first. Ticket 1/3: Wouldn't it be nice if gb could walk the vendored code, find the dependencies, and pull those in too if they aren't already checked in?

**Comment by davecheney** [comment]
Yes. I want that as well, it is a bit frustrating that for project owners
getting started they have to do a loop of gb-vendor gb build over and over
again until their code compiles.

This is a medium sized bit of work, but there are no technical reasons why
it is not possible.

**Comment by davecheney** [comment]
Closed in #231
