### ISSUE TITLE
should the gb repo be a project?

### ISSUE THREAD

**Issue by ccmtaylor** [constabulary/gb#14]
Reading through `README.md` and `getting-started.md`, I got a bit confused whether projects are meant to be checked into version control, and how the different directory structure would interact with making a project `go get`able.

So I thought that since gb is proposing the new structure, and it seems to fit the definition of a project (i.e. it has a package main, and isn't designed to be consumed by other code), it would make sense for the gb repo to be structured as a project itself.

I'm not sure how to go about this though. If I understand correctly, this would only entail moving the code to `gb/src`. This creates a chicken-and-egg problem, though, since `cmd/path.go` and `cmd/gb/main.go` both import `github.com/constabulary/gb`. When I build with `go build`, this would now need to be `import "github.com/constabulary/gb/src"`, and building with `gb` would probably expect the code to live under `src/github.com/constabulary/gb`, right?

**Comment by davecheney** [comment]
In an ideal world; yes. At the moment, there is a bootstrapping problem, so unless `gb` grows a stack of dependencies, I don't think this is super urgent.

**Comment by davecheney** [comment]
You can try if you like, this is a low priority item for me at the moment.

**Comment by skelterjohn** [comment]
I think it's appropriate to leave it go gettable permanently. Go get is a great way to fetch code. Dave just has to keep the transitive deps low or zero.

**Comment by andrewchambers** [comment]
This will be fine once there is a hosted prebuilt binary to download.

**Comment by ccmtaylor** [comment]
Closing due to age
