### ISSUE TITLE
Suggestion: gb vendor fetch supports gb repos

### ISSUE THREAD

**Issue by jtolds** [constabulary/gb#141]
Hi! gb is rapidly getting so much awesomer! I <3 the new gb-vendor fetch. The addition of gb-vendor fetch makes gb that much closer to the dreams I was having for gb a week ago but forgot to say anything.

So I'm filing three tickets. Happy to send pull requests but want to discuss first. Ticket 3/3: It makes me super sad that library repos and gb itself can't actually use gb for their public repository (since developers currently want to make things easy for go get). There's this balkanization it seems like where gb is for projects and gb isn't for libraries. Let's change that!

If we're getting rid of go get anyway, why not have gb vendor fetch understand gb repos? Let's say I have a gb repo at http://github.com/jtolds/mygbproject, and so I have a package at http://github.com/jtolds/mygbproject/src/package1. If I run gb vendor fetch github.com/jtolds/mygbproject/package1, I think it should autodetect that mygbproject is a gbproject and download it and put the files in the right places. It could even support https://github.com/constabulary/gb/issues/139 and get the vendored versions from the manifest into my own vendor folder.

That way we could use gb for libraries too?

**Comment by jtolds** [comment]
Downsides: library creators would have different package imports than library users (package2 vs github.com/me/myproject/package2), which would require import rewriting, which definitely ruins submoduling/subfoldering, etc, which were already ruined since the repo paths would have to change too.

**Comment by jtolds** [comment]
I feel like the benefits here might outweigh the costs? Or maybe there's a way to solve them? For instance I know we hate symlinks but go build totally works with symlinks. It's just that "..." doesn't find anything past symlinks, which might be okay for vendored libs?

**Comment by jtolds** [comment]
Orrrr everyone just uses "package1" and there's even more GOPATH entries.

I'll stop thinking in issue comments now

**Comment by davecheney** [comment]
You can totally use gb for libraries. See #49

**Comment by jtolds** [comment]
Ohhhh sweet I missed that whole conversation. Thanks!

**Comment by davecheney** [comment]
This is my fault for not writing this up as an faq or an example. To close
#49 I have to do that.
