### ISSUE TITLE
Gb doesn't build a main package under src/cmd

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#143]
I was creating an example gb project, to see how a public Gb project might be used. This includes internal packages, vendorized packages and travis integrations. It's here:

https://github.com/fatih/gb-example

I don't know why, but I can't build the code `src/cmd/main.go`. After cloning the repo, I run the following commands:

```bash
~/Code/gb-example (master) gb build cmd
FATAL command "build" failed: failed to resolve import path "cmd": no buildable Go source files in /usr/local/go/src/cmd
~/Code/gb-example (master) gb build cmd/helloworld
cmd/helloworld
```

`src/cmd/helloworld` builds perfectly as seen (just added so it can be tested).

**Comment by davecheney** [comment]
This is a side effect of reusing the go/build package, cmd is a special
word for that package and we've inherited that side effect.

I think there is another issue about this already.

**Comment by fatih** [comment]
You are right, just found these two issues:

https://github.com/constabulary/gb/issues/46
https://github.com/constabulary/gb/pull/48
https://github.com/constabulary/gb/issues/45

I agree with #48 and #46. However I think that #45 shouldn't be marked as closed. This is not of course a priority, however I think that `src/cmd` is a complete valid package name. I'll close this issue as this answers all my questions, though I want you to reconsider #45 again :)

**Comment by davecheney** [comment]
I will fix the src/cmd issue, it shouldn't be too hard. Its just a side
effect of reusing the go/build source loader.

**Comment by fatih** [comment]
Awesome @davecheney :+1:  I really appreciate your work on this!
