### ISSUE TITLE
New gb plugin analogous to go generate

### ISSUE THREAD

**Issue by mdwhatcott** [constabulary/gb#148]
Maybe this is already implemented but I can't find out how to invoke it.

I've tried:

```
gb generate
gb plugin generate
```

...to no avail.

Is this on the roadmap?

https://blog.golang.org/generate

**Comment by vdemario** [comment]
`go generate` is independent of `go build` and it has no explicit relationship with dependency management. In other words, why not keep using `go generate` followed by `gb build`?

**Comment by davecheney** [comment]
Yup, supporting this won't be too difficult. I'll take a crack this weekend
unless nobody else beats me too it.

**Comment by mdwhatcott** [comment]
Thanks!
