### ISSUE TITLE
theory of operation

### ISSUE THREAD

**Issue by glycerine** [constabulary/gb#15]
Hi Dave,

I read your slides and gb sounds like a really great project.

But: I'm a little unclear on how the basic vendoring and GOPATH stuff is supposed to work.

Could you outline the theory of operation in the documentation? A getting started guide would be a great help too.

Thanks!

Jason

**Comment by andrewchambers** [comment]
Hi glycerine, there is nothing too complicated. It works in a similar way to normal GOPATH, only the GOPATH directory is inferred by finding the location of a parent dir called src. It also searches two directories instead of one for source code the main, src dir and the vendor dir.

**Comment by davecheney** [comment]
This does sound useful, as a stronger understanding of how go code is built is useful for all. 

Being honest, this is not top of the list at the moment. It will probably need to wait until we do a github wiki for this project. 

+helpwanted

**Comment by glycerine** [comment]
The most basic example would be a start --

If you wanted to give a friend an example of what to do in order to:  use gb with a single vendored library file and a single main.go file, how would you tell them to set up their directories and invoke gb?

**Comment by glycerine** [comment]
Arg. Missed this: https://github.com/constabulary/gb/blob/master/getting-started.md
