### ISSUE TITLE
Fetch unable to download repo

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [constabulary/gb#151]
For some reason "gb vendor fetch speter.net/go/exp/math/dec/inf" fails to download speter.net/go/exp/math/dec/inf but go get speter.net/go/exp/math/dec/inf works fine.

**Comment by drewwells** [comment]
Fetch the plain repo, paths inside repos are not supported yet.

**Comment by davecheney** [comment]
Sorry, vanity imports are not supported yet

Duplicate of #144
