### ISSUE TITLE
stop duplicating documentation

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#152]
Currently gb commands and plugins have usage messages, godoc, and are documented in getgb.io.

I want to reduce the number of times this documentation is repeated, specifically changing getgb.io to link to the godoc. There is no reason gb and it's plugins couldn't have godoc like this, https://godoc.org/rsc.io/grepdiff

**Comment by davidkaya** [comment]
I would suggest changing only the getgb.io documentation into the godoc as you said but I would leave usage messages as they are now (and maybe use KISS principle to avoid over-documenting usage) because I guess user won't want to visit godoc/generate godoc just to see how to use a command.

**Comment by davecheney** [comment]
At the moment I think il add pages to the site, the overwrite them with a redirect at the nginx level
