### ISSUE TITLE
just use github.com/spf13/viper 

### ISSUE THREAD

**Issue by natefinch** [constabulary/gb#158]
You seem to be spending a lot of time recreating a command parsing structure... Viper already does this and is well regarded. I suggest just using viper and making PRs as needed if it doesn't do quite what you want.

**Comment by davecheney** [comment]
We don't use an external library because I don't want to be reliant on it (see the whole rant about go get not being deterministic). At some point gb will move to be self hosting, see #14, but there will have to be a significant payoff for the cost of loosing the go get install story.

**Comment by natefinch** [comment]
There are many fixes to the dependency problem.  The easiest of which is to simply fork viper and import your (effectively frozen) copy.  I understand the impetus to limit your dependencies, but the user experience of an application is very important, and getting it just right requires a lot of annoying tweaking that the Viper developers have already done for you.

**Comment by davecheney** [comment]
I don't think it's that big of a problem.

**Comment by davecheney** [comment]
Closing for the moment. Not that viper is bad, but I'm not just ready to pull the trigger on #14

**Comment by natefinch** [comment]
:+1:
