### ISSUE TITLE
Ability to set linker options?

### ISSUE THREAD

**Issue by calmh** [constabulary/gb#16]
Specifically, `-X main.Version v1.0.47` and similar to create properly version tagged binaries.

(Or how do you solve this?)

**Comment by davecheney** [comment]
I'd like to support this pattern, but I think it would be best handled with a plugin.

Waves hands, something like gb release which would do effectively release build of the product, including sniffing and setting these release values. 

+help wanted

**Comment by calmh** [comment]
I haven't looked at the plugin system yet beyond reading the readme, it sounded to me like it was merely a way to run commands through `gb` (and thus couldn't do things that `gb` couldn't already), but otherwise I'll happily write a `gb release` plugin to do what I need.

**Comment by calmh** [comment]
I'm not sure how to proceed with such a plugin, although I admin I've only looked at the code for a minute or two. It seems like the exposed `gb.Ld` etc also don't accept the possibility of such flags, so I would either have to duplicate everything, or duplicate the work of figuring out the project structure and shelling out to the `go` toolchain to do the build myself...? (which would obviously render the exercise meaningless to start with). I assume I'm missing the obvious :D

**Comment by davecheney** [comment]
I'm sorry, I should have been clearer. Writing a new plugin is possible,
but probably not easy without changes to the gb package.

At the moment adding this functionality is not top of my list, but it is
something that I want to support so gb can be useful throughout the whole
software development life cycle.

**Comment by davecheney** [comment]
#95 added support for `-ldflags` in the traditional manner. `gb release` will have to wait for another day.
