### ISSUE TITLE
gb cgo support broken on OSX 10.10.3?

### ISSUE THREAD

**Issue by newhook** [constabulary/gb#162]
I tried a gb build of a project and got lots of errors from gb.

  "_fdb_transaction_set_option", referenced from:
      __cgo_eebe09c45e95_Cfunc_fdb_transaction_set_option in 000000.o
     (maybe you meant: __cgo_eebe09c45e95_Cfunc_fdb_transaction_set_option)
  "_fdb_transaction_set_read_version", referenced from:
      __cgo_eebe09c45e95_Cfunc_fdb_transaction_set_read_version in 000000.o
     (maybe you meant: __cgo_eebe09c45e95_Cfunc_fdb_transaction_set_read_version)
  "_fdb_transaction_watch", referenced from:
      __cgo_eebe09c45e95_Cfunc_fdb_transaction_watch in 000000.o
     (maybe you meant: __cgo_eebe09c45e95_Cfunc_fdb_transaction_watch)
  "_snappy_compress", referenced from:
      __cgo_775f1b88ab3b_Cfunc_snappy_compress in 000002.o
     (maybe you meant: __cgo_775f1b88ab3b_Cfunc_snappy_compress)
  "_snappy_max_compressed_length", referenced from:
      __cgo_775f1b88ab3b_Cfunc_snappy_max_compressed_length in 000002.o
     (maybe you meant: __cgo_775f1b88ab3b_Cfunc_snappy_max_compressed_length)
  "_snappy_uncompress", referenced from:
      __cgo_775f1b88ab3b_Cfunc_snappy_uncompress in 000002.o
     (maybe you meant: __cgo_775f1b88ab3b_Cfunc_snappy_uncompressed_length, __cgo_775f1b88ab3b_Cfunc_snappy_uncompress )

**Comment by davecheney** [comment]
Thanks for the error report. Can you include a link to the source or instructions on how to reproduce a project that shows this.

**Comment by newhook** [comment]
I contacted your email regarding this issue.

**Comment by davecheney** [comment]
@newhook can you please try now #301 has landed.

**Comment by davecheney** [comment]
Timed out. I'm hoping this is fixed, please reopen if not.
