### ISSUE TITLE
gb vendor fetch: fetching all dependencies from Manifest file

### ISSUE THREAD

**Issue by davidkaya** [constabulary/gb#175]
I was thinking about adding flag to `gb vendor fetch`, which would parse Manifest file and download (sync) all dependencies.
 
Use cases: 
* User has its project in VCS without dependencies but with Manifest file, he clones his project and calls `gb vendor fetch --sync` to download dependencies.
* User makes changes directly to Manifest file (changing branches, etc.) and wants to mass-update dependencies, same command - `gb vendor fetch --sync`.

What do you think about that @davecheney ?

**Comment by davecheney** [comment]
not lgtm. I'm not keen on encouraging people to think of gb vendor fetch as
a replacement to go get. Let's keep the simple story, gb builds the
project, gb vendor helps fill out the project, I don't want to reinvent a
tool for dynamically downloading code from the internet as that is counter
to the arguments of repeatable builds.

**Comment by davidkaya** [comment]
Ok, closing

**Comment by davecheney** [comment]
Again, this isn't a bad idea. But it is inconsistent with the philosophy of
gb. Our goal is to have a project layout for your source code, tools like
gb-vendor help project owners setup and maintain that project, but
gb-vendor is a plugin, a project should be buildable without it. If the
project is missing pieces of the source, and only has a record of them in
the manifest, then it isn't buildable, and that leads to a whole shitshow
of documentation and user training.

Maybe in the future, a successor to gb can be smarter about having to copy
all the source into one place, but that isn't today.

**Comment by davidkaya** [comment]
Yep you are right. I was not thinking about that from this specific perspective.

**Comment by davecheney** [comment]
s'ok, no harm in dreaming, but FYI this is why I am concerned about -all
type flags on commands that work with dependencies. Convenience is ok, but
I don't want people to forget that gb-vendor is just a plugin, and it will
not adapt to 100% of their edge cases. By doing a good job at the 70%
level, we encourage people into a standard workflow, without making them
reliant on the tool to do everything; rsync, cp -r and git subtrees are
always an option.

**Comment by davidkaya** [comment]
You are right. :)

**Comment by svenwltr** [comment]
> not lgtm. I'm not keen on encouraging people to think of gb vendor fetch as
> a replacement to go get. [...]

I don't think this would replace `go get` since it is not possible to fetch a specific revision, tag or branch with `go get`.

**Comment by acasajus** [comment]
euh.. Why is the manifest there then? Just for info purposes?

**Comment by davecheney** [comment]
The manifest file exists to record where the dep came from. I tried to hold
the line and suggest people use git submodules, but people demanded a tool
to manage this for them, and that tool needs to record its actions.

**Comment by acasajus** [comment]
It seems like a half-way solution then. "I'll download the dependencies and write down the version I've got but I won't redownload them in case you need to". A project is certainly buildable without gb-vendor but It makes the life of the devs easier. Why not make it feature-complete? I mean I can make my own tool to complement gb-vendor but I think most of the people would agree with me that it would be extra nice if it did the whole thing (and that just means adding a fetch of the already defined deps) and there's a tool we can all use.

Using tools is a choice. No one is forcing anyone to use gb-vendor or all of its features.

**Comment by davecheney** [comment]
@acasajus to explain my position, I care about reliable builds, and that means, at the moment, copying source code. I appreciate that gb-vendor could be made to operate just from a manifest file, but this is not my goal, and would, as I have said above, quickly devolve into a poor replacement for `go get`.

Having said that, my strong desire is that gb consists of useful reusable pieces. I want _you_ to be able to build the tools you want to manage your builds however it suits you. I encourage you to build your own gb-vendor replacement, and to raise issues on this project when a piece of gb, or gb-vendor is not sufficiently reusable, and I will fix that.

**Comment by acasajus** [comment]
I fail to see how copying files by hand is less error prone than git/hg fetching them with a sha reference. I understand that google's take is to put all the deps in the repo. But many of us are happy with just adding the references to the deps with the commits stored. 

That said, I just made a PR for go-vendor. I could just fork go-vendor into something like go-deps. If you prefer that I'll close the PR and do so.

**Comment by davecheney** [comment]
Thank you for your persistence here, you've won me over -- let's try it and see what others think.

I have some concerns that not including the source of a dependency will mean users of this mode will have to

**Comment by davecheney** [comment]
Closed in #281

**Comment by dayuoba** [comment]
i think is a cool feature,compared with nodejs npm, tracking deps and there versions in a file is very convenient!
