### ISSUE TITLE
Adding description to Manifest file

### ISSUE THREAD

**Issue by davidkaya** [constabulary/gb#176]
Another idea. What about adding "description" into packages in Manifest file. Let's say user has project with huge amount of dependencies and wants to add description to them - `gb vendor fetch --desc "My awesome package" $repo`. Also the `gb vendor list` can be updated to also print the description of the package.

```json
{
	"version": 0,
	"dependencies": [
		{
			"importpath": "github.com/my/awesome/package",
			"repository": "https://github.com/my/awesome",
			"revision": "214a2b2cadabe2baeb2fbfab3bd...",
			"branch": "master",
			"path": "",
			"description": "My awesome package that does nothing at all"
		}
	]
}
```
@davecheney ?

**Comment by davecheney** [comment]
Not LGTM for two reasons

1. This would mean changing the metadata format (potentially) and this
isn't a good enough justification for this.

2. If you want comments then json is the wrong format for that. That means
changing the format, see point 1

**Comment by davidkaya** [comment]
Ok, closing

**Comment by davecheney** [comment]
This isn't to say it isn't a good idea, but I don't want to see it
shoehorned into json, because that is a poor format for free style
commentary. There are bigger fish to fry, and will be for some time.

**Comment by davidkaya** [comment]
Yea, that json was also in my "cons" list. It´s ok, I was just brainstorming during my studying for Bachelor finals today..

**Comment by davecheney** [comment]
Maybe once gb becomes self hosting we can look at a different encoding
scheme, one that maybe isnt available in the stdlib, but becoming self
hosting is very low on the priority list.
