### ISSUE TITLE
gb vendor fetch git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git fail

### ISSUE THREAD

**Issue by jvermillard** [constabulary/gb#182]
```go get git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git```
works, but

```gb vendor fetch git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git
FATAL command "git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git" failed: unknown repository type
FATAL command "vendor" failed: exit status 1```

**Comment by jvermillard** [comment]
reading the code:
https://github.com/constabulary/gb/blob/master/cmd/gb-vendor/vendor/repo.go#L62
looks like it only support GH and bitbucket

**Comment by PSG-Luna** [comment]
This seems to be a dup of #178 ?

**Comment by davecheney** [comment]
Not quite. Does the go tool support this import path ?

**Comment by jvermillard** [comment]
yes the import path is comical, but works with go tools:

go get git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git

then
import "git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git"

http://godoc.org/git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git

**Comment by davecheney** [comment]
Ok, this is different. We will add support for that form.

**Comment by oleksandr** [comment]
Something similar with apache's git repo:

```$ gb vendor fetch git.apache.org/thrift.git/lib/go/thrift
FATAL command "fetch" failed: Get https://git.apache.org/thrift.git/lib/go/thrift?go-get=1: dial tcp 54.84.58.65:443: connection refused
FATAL command "plugin" failed: exit status 1```

**Comment by davecheney** [comment]
Hello, I took a look at this on the weekend. It shouldn't be that hard to
implement.
