### ISSUE TITLE
Hangs when vendoring from repo

### ISSUE THREAD

**Issue by crsmithdev** [constabulary/gb#19]
Unfortunately I can't put the actual repo url in here, but this is hanging when trying to vendor one of our (Uber's) repositories:

```
gb vendor <host>/<path>/<repo>.git
2015/04/29 15:00:53 INFO project root "<project root>"
```

...and just stays there until I Ctrl-C.

**Comment by mvdan** [comment]
Surely you mean gb-vendor?

**Comment by crsmithdev** [comment]
More info after letting it time out:

```
gb vendor <host>/<path>/<repo>.git
2015/04/29 15:00:53 INFO project root "<project root>"
package code.google.com/p/snappy-go/snappy: Get https://code.google.com/p/snappy-go/source/checkout?repo=: read tcp 74.125.239.40:443: operation timed out
2015/04/29 15:08:50 exit status 1
2015/04/29 15:08:50 command "vendor" failed: exit status 1
```

`code.google.com/p/snappy-go/snappy` is directly go-gettable, though.

**Comment by crsmithdev** [comment]
interesting, both `gb vendor` and `gb-vendor` seem to be valid commands?

**Comment by crsmithdev** [comment]
Strange!  `gb-vendor` works.  Why are they both valid and why does the latter work but not the former?

**Comment by davecheney** [comment]
gb-vendor is a git style plugin. It's a bug that t doesn't properly protect itself from being run directly. I'll fix that. 

As an aside, gb-vendor is just a thin shim that sets GOPATH to the project's vendor directory and shells out to go get. 

Gb-vendor is just a hack to bootstrap your project, you can always just popular the vendor/src directory manually.

**Comment by crsmithdev** [comment]
OK thanks for the clarification, closing, although definitely fix the `gb vendor` issue, that was quite confusing.
