### ISSUE TITLE
Allow plugin pre-build hooks

### ISSUE THREAD

**Issue by philhofer** [constabulary/gb#193]
First of all, thanks for your hard work on this project.

One of the primary reasons I still have to use `make` for some projects is dependency detection for generated code.

If `gb build` could be configured to run a pre-build hook through a plugin, one could ultimately write something similar to `go generate` that actually performed dependency analysis. (Wouldn't it be wonderful if updating a `.proto` automatically triggered a re-generate+re-build of the package?)

If you/we can come to a decision on the design of such a feature, I'm happy to implement it.

**Comment by davecheney** [comment]
Thanks for your suggestion. Being honest, this sounds like something that is outside the very simple remit for gb at the moment. I'm trying to hold the line that gb just build code in a project. 

So I can understand the workflow better, can you explain what you are doing now, and where the missing command or action would be that would improve your workflow ?

**Comment by philhofer** [comment]
Since `go generate` has no idea about dependencies between files, I usually keep a makefile around that   formalizes those dependencies. That seems like overkill, and it doesn't actually guarantee that the right things get built if it isn't your only build tool.

So, in that particular case, I'd like `gb build` to run `make` before it runs a build, but of course a pre-build hook could include other stuff (like `go vet`, `golint`, etc. At $DAYJOB we've got a linter that forbids yoda conditional expressions.)

So, the benefits are two-fold:
- Codify formal build dependencies (modifications to `foo.proto` invalidate a cached package build)
- Codify informal build requirements (linters, etc.)

... but I can imagine other uses as well.

(In the case I mentioned above with `make`, I ultimately wanted to build a `gb` plugin that did `go generate` dependency detection, but that's another conversation.)

**Comment by dradtke** [comment]
I just came across a need for something like this as well; I want to incorporate [go-bindata](https://github.com/jteeuwen/go-bindata) into my project, and ideally it would be included as part of the build, but run before anything actually gets built.

**Comment by davecheney** [comment]
I don't have any plans to add this at the moment.

I recognise the need for this feature, but I have no plans to add it
without careful though about how this would change gb's role into that of a
general build tool. Just as gb doesn't seek to replicate go get, it also
doesn't seek to replicate make(1).

**Comment by dradtke** [comment]
My planned workaround is to use `make` to selectively build a couple dependencies, run the resulting binaries to get their output, and then invoke `gb build`.

**Comment by davecheney** [comment]
Closing based on my comments on Oct 13 https://github.com/constabulary/gb/issues/193#issuecomment-147856490
