### ISSUE TITLE
Add API similar to go/build.

### ISSUE THREAD

**Issue by avrtno** [constabulary/gb#197]
- Given import path, return physical directory.
- Given import path and build constraints, return files, test files, x test files, etc.
- Given directory in project, return project root.

**Comment by davecheney** [comment]
> Given import path, return physical directory.

http://godoc.org/github.com/constabulary/gb#Context.ResolvePackage

will return a *gb.Package, the Dir field should be the path to the package's source.

> Given import path and build constraints, return files, test files, x test files, etc.

Same

> Given directory in project, return project root.

http://godoc.org/github.com/constabulary/gb/cmd#FindProjectroot

**Comment by davecheney** [comment]
@avrtno I'm going to close this for the moment as I believe I have answered your question.

Please feel free to reopen this if you have more questions.
