### ISSUE TITLE
Should the vendor command use an internal directory?

### ISSUE THREAD

**Issue by jpoehls** [constabulary/gb#2]
Instead of fetching dependencies into `vendor/src`, should it put them in `internal/src` or `internal/vendor/src` to comply with the proposed "official recommendation" for vendoring? 

https://groups.google.com/d/msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ
> 1. officially recommends vendoring into an “internal” directory with import rewriting (not GOPATH modifications) as the canonical way to pin dependencies.

**Comment by davecheney** [comment]
The `internal` directory is for, well, paths inside your source, `vendor` lives outside your source, so I don't think `internal` makes a lot of sense.
