### ISSUE TITLE
fetch failed on windows

### ISSUE THREAD

**Issue by alexnv** [constabulary/gb#200]
when trying to fetch package github.com/labstack/echo i've got error.
OS Windows 7 x64
git version 1.9.4.msysgit.0

```
E:\go_dev\vd-crm-prj
λ gb vendor fetch github.com/labstack/echo
FATAL command "fetch" failed: remove E:\go_dev\APPDATA\tmp\gb-vendor-240678526\.git\objects\pack\pack-3461fa99fcbbe64c91c25f698a8d530602fb28d2.idx: Access is denied.
FATAL command "vendor" failed: exit status 1
```

help to fix this problem

**Comment by davecheney** [comment]
Sorry about that. I'll take a look tomorrow when I have access to my
windows machine tomorrow.

**Comment by alexnv** [comment]
It seems that the problem is git.exe in the windows

**Comment by alexnv** [comment]
the problem is read-only file attribute in .git folder in 
```
E:\go_dev\APPDATA\tmp\gb-vendor-240678526\.git\objects\pack\pack-3461fa99fcbbe64c91c25f698a8d530602fb28d2.idx 
```

**Comment by davecheney** [comment]
thanks for that. there is an open bug in the go issue tracker around read
only files that are hard to delete with os.RemoveAll.

I'll see if we can do something better for windows as we have to support Go
1.4 for a while yet.

On Wed, Jun 10, 2015 at 8:08 PM, Aleksey Nepryahin <notifications@github.com

**Comment by ChrisHines** [comment]
Note that the vendored code **does** successfully get copied to the project, and the manifest file is updated. Only the removal of the temporary clone fails.
