### ISSUE TITLE
$PROJECT/pkg file layout not compatible with golang/x/tools/go/loader

### ISSUE THREAD

**Issue by Ecsy** [constabulary/gb#202]
gb generate fails because go generate fails to find \*.a files under pkg/ directory.
`stringer: checking package: x.go:4:2: could not import xxx`
`(c *Context) Pkgdir()` creates a path separator between `GOOS` and `GOARCH`.
Expected result would be an **underscore** instead of *separator*, e.g. **linux_amd64** and not *linux/amd64*

**Comment by davecheney** [comment]
Thanks for your report. This might be a bit tricky to fix, it's looking like some go generate plugins are parsing the output (go/loader), not the source. The way I arrange things with the gb generate plugin, it only maintains the illusion of the latter.

**Comment by Ecsy** [comment]
In my understanding the only problem is that **gb build** produces the installed package object in a wrong directory that is the cause of **gb generate** could not find the object.
the actual output of gb build:
```
pkg/
  linux/
    amd64/
      foo/
        bar.a
```
expected output:
```
pkg/
  linux_amd64/
    foo/
      bar.a
```
That could be fixed at https://github.com/constabulary/gb/blob/master/context.go#L91
```diff
func (c *Context) Pkgdir() string {
        // TODO(dfc) c.Context.{GOOS,GOARCH} may be out of date wrt. tc.{goos,goarch}
-       return filepath.Join(c.Project.Pkgdir(), c.Context.GOOS, c.Context.GOARCH)
+       return filepath.Join(c.Project.Pkgdir(), c.Context.GOOS+"_"+c.Context.GOARCH)
}
```
Am I getting something wrong?

**Comment by davecheney** [comment]
You're not wrong, but I'm reserving the right to change the package
directory's name and path, I want to put more things in there like tags and
other flags.

**Comment by paulsmith** [comment]
What's the workaround, just `GOPATH=$GB_PROJECT_DIR go generate`?

**Comment by davecheney** [comment]
The underlying issue is the layout of .a files inside $PROJECT/pkg is not compatible with the `golang.org/x/tools/go/loader` package.

I don't want to make it compatible because that would make it harder to implement incremental compilation in the face of -tags and other conditional constructs.

**Comment by davecheney** [comment]
Marking this closed for the moment, fwiw the format of $PROJECT/pkg is not intended to be compatible with go/loader.
