### ISSUE TITLE
gb vendor fetch cannot retrieve http hosted (non-secure) packages

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#207]
I have several general purpose packages in our internal VCS. These packages are used in multiple projects each of which should vendor them for reproducible project builds. But our internal VCS does not have https enabled.

Any chance `gb vendor fetch` could try http if https is not available for a repo?

**Comment by davecheney** [comment]
The Go team fell into this trap when go get automatically failed back to http when https failed.

I deliberately did not include support for pulling from http repos (although it will try git repos, which I guess is just as bad) for this reason.

What if I added a flag to fetch / update to permit insecure fetching. This flag would always default to off.

**Comment by ChrisHines** [comment]
@davecheney Yes, a flag to enable insecure fetching would be great.

**Comment by jpoehls** [comment]
Ditto for a flag.

I ran into this when trying to fetch a package from my vanity URL, which redirects to GitHub.
