### ISSUE TITLE
cmd/gb-vendor: add support for fetching from a tag

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#209]
@davidkaya what do you say to adding support for gb vendor fetching from a tag, not a revision ?

Updates docker/docker#13756

**Comment by davidkaya** [comment]
Well if you specify tag in `--branch` it should clone a tag. We can just make flag for `--tag` which would be alias for `--branch`.

**Comment by davecheney** [comment]
Hmm. I'm not sure, I think tags and branches are different animals in
mercurial, but that is because branches are a more serious commitment.

How about this, at least add the -tag flag and we'll figure out what
refactorings need to be made to integrate it into RemoteRepo.Checkout

**Comment by davidkaya** [comment]
Well I don't know much about mercurial. But I think in git it should be enough.

**Comment by davecheney** [comment]
For the moment, let's do RemoteRepo.Checkout(branch, tag, revision string).
I know it's a gross API, but at least it _shouldn't_ grow a forth string
parameter.

Then at least each of the repo types can choose how to interpret those
three values. GitRepo should probably assert that at most one of those
three is set, and can use tag as an alias for branch if that's what fits.

**Comment by davidkaya** [comment]
Ok. I can start working on it this evening (9:56 a.m. here), because I am currently in a library studying for my bachelor finals.

**Comment by davecheney** [comment]
Let me make an attempt this evening, then I'll pass it off to you for
review.

**Comment by davidkaya** [comment]
Oh, ok sure, sounds good.

**Comment by pires** [comment]
I've updated `gb` but not sure if this is present, since..

```
 gb vendor help fetch
usage: gb vendor fetch [-branch branch] [-revision rev] importpath

fetch vendors the upstream import path.

Flags:
	-branch branch
		fetch from the name branch. If not supplied the default upstream
		branch will be used
	-revision rev
		fetch the specific revision from the branch (if supplied). If no
		revision supplied, the latest available will be supplied.
```

no `-tag`?

**Comment by davecheney** [comment]
@pires  please try the following
```
% rm $GOPATH/bin/gb-vendor
% whch gb-vendor
```
If you find any remaining copies, remove them. Then
```
% go get -u github.com/constabulary/gb/...
```

**Comment by pires** [comment]
My fault. Thanks @davecheney worked like a charm.
