### ISSUE TITLE
Can not run the specified test file(s)

### ISSUE THREAD

**Issue by hyper-carrot** [constabulary/gb#210]
I want to start testing under a package path:
```
[10:17:48] client(master ✔) $ pwd
/Users/haolin/Office/Wepiao/Project/common_tools/src/weixin/client
[9:30:58] client(master ✔) $ ls
msgsender.go           msgsender_test.go
[9:30:59] client(master ✔) $ gb test msgsender_test.go msgsender.go
```
But it failed:
```
FATAL command "test" failed: failed to resolve package "msgsender_test.go": cannot find package "msgsender_test.go" in any of:
	/usr/local/go/src/msgsender_test.go (from $GOROOT)
	/Users/haolin/Office/Wepiao/Project/common_tools/src/msgsender_test.go (from $GOPATH)
	/Users/haolin/Office/Wepiao/Project/common_tools/vendor/src/msgsender_test.go
```
The Golang standard tool `go test` is running well:
```
[10:17:29] client(master ✔) $ export GOPATH=$GOPATH:/Users/haolin/Office/Wepiao/Project/common_tools; go test msgsender_test.go msgsender.go
ok  	command-line-arguments	0.669s
```

Could you improve it?

**Comment by davecheney** [comment]
gb only works with packages, not individual files. use 

`gb test weixin/client`

**Comment by hyper-carrot** [comment]
@davecheney but any enhancement Plan?

**Comment by davecheney** [comment]
No, this is a design decision, gb will only work with packages, not files.

**Comment by hyper-carrot** [comment]
OK, can I ask the reason for the decision?

**Comment by davecheney** [comment]
Because the go compilers work with packages, not individual files. The fact that go {run,build,test} sort of work with files, sometimes, is a mistake and confuses new users, so gb only builds code correctly organised into packages.

**Comment by hyper-carrot** [comment]
I feel this reason is not sufficient, actually. But I can understand. Thank you.

**Comment by davecheney** [comment]
I'm sorry you feel that way. Can you help me understand a use case that
requires passing individual files to a gb command ? Hopefully I can show
you how to do it another way.

**Comment by hyper-carrot** [comment]
@davecheney Sometimes, I need to test a few small functions, not the whole package. The package `client` will contains some kinds of client program (redis client, message sender, etc.), as follows:
```
[11:31:05] client(master ✗) $ ls
common.go           jsapiticket_test.go redis.go
common_test.go      msgsender.go        token.go
jsapiticket.go      msgsender_test.go   token_test.go
```
I know that it can be divided into different packages, but now is not the time. So I want to test them separately.

Do I make myself clear?

**Comment by davecheney** [comment]
@hyper-carrot gb supports the same flags as go test, so use `gb test -run SOMETHING`, where SOMETHING is a regex that matches the name of the tests you want to run.

**Comment by hyper-carrot** [comment]
@davecheney It's useful, but not very well. I want to a more convenient and flexible command line for test. `xx test -run` could force me to input many words.

**Comment by davecheney** [comment]
I don't understand how gb test -run REGEX is more work that gb test file.go
file2.go.

**Comment by hyper-carrot** [comment]
@davecheney For example, I want to run some test functions in the same test file `msgsender_test.go`, such as  `TestSendMsg`, `TestConvertToJson `, `TestFillData`.

I have to run `go test -run "(Send|Convert|Fill)"` or `gb test -run "(Send|Convert|Fill)"` (`gb` will scan all packages in current project, right?). But I can run `go test msgsender_test.go msgsender.go` with less input (The key: there is auto-completion for file names).

**Comment by davecheney** [comment]
Robert, I'm very sorry, but I will not be changing gb test to accept files. I believe my reasons for this are sound, and I am sorry that I cannot help you with your workflow.

**Comment by hyper-carrot** [comment]
@davecheney  That's OK. Good thing I have `go test`. I'm going to mix them in my workflow.
