### ISSUE TITLE
cloning repository with `--single-branch` blocks checkouts on specific tag/revision

### ISSUE THREAD

**Issue by MerlinDMC** [constabulary/gb#219]
reproducible examples:

```
gb vendor fetch -tag v1.5.0 github.com/docker/docker
gb vendor fetch -revision a8a31eff10544860d2188dddabdee4d727545796 github.com/docker/docker
```
fails with:
```
error: pathspec 'v1.5.0' did not match any file(s) known to git.
FATAL command "fetch" failed: exit status 1
FATAL command "vendor" failed: exit status 1

fatal: reference is not a tree: a8a31eff10544860d2188dddabdee4d727545796
FATAL command "fetch" failed: exit status 128
FATAL command "vendor" failed: exit status 1
```

For fetching tags this might be fixed by adding a `--branch <tag>` to the actual clone command but setting via revision would still fail in that example.

I personally would favour to drop the `--single-branch` flag or give fetch a flag to enable it explicitly or even a `--depth` that can be set for the fetch.

**Comment by davecheney** [comment]
@davidkaya would you have time to look at this one?

**Comment by davidkaya** [comment]
On Thursday, I got bachelor finals on Wednesday.

**Comment by davecheney** [comment]
Got it. Thanks. Good luck with your examinations.

**Comment by davecheney** [comment]
@MerlinDMC if you wanted to send a PR that removes `--single-branch`, that'd be ok by me, I'm not convinced it's paying for itself.
