### ISSUE TITLE
gb vendor fetch fails on code.google.com repositories

### ISSUE THREAD

**Issue by MerlinDMC** [constabulary/gb#220]
```
$ gb vendor fetch code.google.com/p/goauth2/oauth
FATAL command "fetch" failed: go-import metadata not found
FATAL command "vendor" failed: exit status 1
```

Seems as if the metadata is not published anymore and `ParseMetadata()` relies on that.

**Comment by davecheney** [comment]
I'll add code.google.com support, but you should aim to move away from that repo as soon as possible as code.google.com is shutting down.
