### ISSUE TITLE
gb build doesn't support -tags

### ISSUE THREAD

**Issue by jhenzie** [constabulary/gb#226]
Seems like an important flag for conditional compilation

Is there an alternative.

**Comment by davecheney** [comment]
Dup of #81 

Yes, I absolutely want to add these. It's on the roadmap.

**Comment by gobwas** [comment]
@davecheney also, `gb test -tags=` should work?

**Comment by davecheney** [comment]
Not yet I'm afraid, there is no -tag support yet.

**Comment by gobwas** [comment]
:disappointed: 

Is it planned to support this?

**Comment by davecheney** [comment]
Yes, build tags are very much in the roadmap.

**Comment by gobwas** [comment]
Cool.

Also, just as an idea: in the [Rust](https://www.rust-lang.org/) ecosystem, there are three types of tests:
 - unit
 - doc (exmaples)
 - and integration

For the integration tests there are special dir `tests` on the same level as `src`. In Go, I wanted to use `-tags` to separate unit-tests from integration-tests. So, since GB makes some rules to directory structure of project, it will be a good tool to split test code this way.

If you find this make sense =)

**Comment by gobwas** [comment]
@davecheney what do u think about comment above?

**Comment by davecheney** [comment]
You can do that now with gb as we have -tags support.

**Comment by gobwas** [comment]
@davecheney thats cool, but what about tests dir?

**Comment by davecheney** [comment]
So you're asking for $PROJECT/tests, not $PROJECT/src/tests ?

**Comment by gobwas** [comment]
Yes, about $PROJECT/tests =)

**Comment by davecheney** [comment]
Apart from putting things in different boxes, what would be the advantage
given that $PROJECT/src/tests would work today with no change.

**Comment by gobwas** [comment]
What will u do if you will have package tests, that's not for integration tests?

**Comment by davecheney** [comment]
I'm not keen on adding a special top level directory $PROJECT/tests just so
that there can be some go code that does not exist within the existing two
project/src and project/vendor/src directories.

You're going to have to make a stronger argument that this code is special.

**Comment by gobwas** [comment]
Also, about tags – how could I use them?

```shell
> gb test -tags=abcd all
flag provided but not defined: -tags
Usage of /var/folders/g2/xmqjypqx3wn6h3nvq4yw9vr00000gp/T/gb182840264/xxx.test:
...
```

**Comment by davecheney** [comment]
I am sorry, it is likely that gb test doesn't handle -tags correctly yet --
it has a lot of limitations. Please raise a new bug.
