### ISSUE TITLE
Build failure "FATAL could not locate project root:"

### ISSUE THREAD

**Issue by shrimpywu** [constabulary/gb#227]
I have below folder structure:

````
myproject
   |--src
         |--hello
               |-- hello.go

````

in command prompt, current directory is "myproject"
perform "gb build all", get below error:

````
FATAL could not locate project root: The system cannot find the file specified.
````

i am using windows server 2012

is there a way to turn on more logs to see what is going on? i looked at source code, error seems to come from [here ](https://github.com/constabulary/gb/blob/master/cmd/cmd.go#L64).

**Comment by davecheney** [comment]
Can you run the command with -v and post the output please.

**Comment by shrimpywu** [comment]
i tried below command 

````
gb build all -v
and 
gb build -v all 
````

i don`t see any extra error message other than

````
FATAL could not locate project root: The system cannot find the file specified.
````

**Comment by davecheney** [comment]
OK, thanks. I'll take a look today.

**Comment by shrimpywu** [comment]
any update what was the issue?

**Comment by davecheney** [comment]
Hello @shrimpywu 

I tried to reproduce this problem on a win8 machine and was not able. Can you please zip up the project and upload it to this issue so I can tried to reproduce the issue.

**Comment by davecheney** [comment]
timed out
