### ISSUE TITLE
vendor update does not leave project in a consistent state after errors

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#228]
If gb vendor encounters an error before completing, it may have updated `vendor/src/...` but the manifest file is left unchanged.

This issue comes up repeatedly on Windows where deleting a temporary git clone always fails (see  #200).

A workaround is:

1. `gb vendor delete <import path>`
2. `gb vendor fetch <import path>`

**Comment by davecheney** [comment]
I agree we can do better here, by moving the removal of the old dep down later, and writing the manifest before removing the temporary copy.

There is still a window where failures can happen, and some of that responsibility for covering that will have to be covered by project owners to use source control studiously.
