### ISSUE TITLE
gb vendor fetch speter.net/go/exp/math/dec/inf fails

### ISSUE THREAD

**Issue by tarfu** [constabulary/gb#236]
Hi,

first of all cool work and i really like it!

when i try to vendor speter.net/go/exp/math/dec/inf it fails with the following:

    # gb vendor fetch speter.net/go/exp/math/dec/inf
    FATAL command "fetch" failed: lstat /tmp/gb-vendor-661692106/inf: no such file or directory
    FATAL command "vendor" failed: exit status 1

Anyone has any suggestions why this happens and how to fix it?

**Comment by davecheney** [comment]
I think I know what is causing this.

For the moment if you vendor the root of the repo speter.net/go/exp
(guess), it should work.

**Comment by tarfu** [comment]
I have tried this and it makes it kind of worse....

    panic: runtime error: slice bounds out of range

     goroutine 1 [running]:
    github.com/constabulary/gb/cmd/gb-vendor/vendor.DeduceRemoteRepo(0x7fffadba8893, 0x11,         0xc20801fb00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/home/tobias/go/src/github.com/constabulary/gb/cmd/gb-vendor/vendor/repo.go:131 +0x1d00
    main.func·002(0xc208011a40, 0xc20800a020, 0x1, 0x1, 0x0, 0x0)
    	/home/tobias/go/src/github.com/constabulary/gb/cmd/gb-vendor/fetch.go:64 +0x258
    main.main()
    	/home/tobias/go/src/github.com/constabulary/gb/cmd/gb-vendor/main.go:78 +0x9ca
    
    goroutine 10 [runnable]:
    net/http.(*persistConn).readLoop(0xc20805e4d0)
    	/usr/local/go/src/net/http/transport.go:928 +0x9ce
    created by net/http.(*Transport).dialConn
    	/usr/local/go/src/net/http/transport.go:660 +0xc9f

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

    goroutine 11 [select]:
    net/http.(*persistConn).writeLoop(0xc20805e4d0)
    	/usr/local/go/src/net/http/transport.go:945 +0x41d
    created by net/http.(*Transport).dialConn
    	/usr/local/go/src/net/http/transport.go:661 +0xcbc
    FATAL command "vendor" failed: exit status 2

**Comment by davecheney** [comment]
Thanks. Now I have two bugs :)
