### ISSUE TITLE
Exporting a GOPATH and then running go test yields errors even when gb test succeeds

### ISSUE THREAD

**Issue by aviflax** [constabulary/gb#237]
I’m having some strange issues related to exporting a GOPATH and then running `go test`. I don’t know, but it seems almost like some of my dependency code is getting cached somewhere somehow.

Here’s what I’m seeing:

```
$ export PROJECT=`pwd`
$ export GOPATH=$PROJECT:$PROJECT/vendor
$ go test -v rugen
# rugen
src/rugen/rugen.go:140: undefined: timezones.AllOffsetsSorted
src/rugen/rugen.go:193: undefined: timezones.NewZone
src/rugen/rugen.go:194: undefined: timezones.NewZone
src/rugen/rugen.go:218: undefined: timezones.NewZone
src/rugen/rugen.go:219: undefined: timezones.NewZone
src/rugen/rugen.go:225: undefined: timezones.Offset
src/rugen/timezones.go:11: undefined: timezones.Offset
src/rugen/rugen_test.go:401: undefined: timezones.LastOffset
src/rugen/rugen_test.go:774: undefined: timezones.LastOffset
src/rugen/rugen_test.go:826: undefined: timezones.LastOffset
src/rugen/rugen_test.go:826: too many errors
FAIL	rugen [build failed]
```

…those errors are incorrect; the supposedly undefined symbols are actually defined.

And `gb test` works fine:

```
$ gb test
testing: warning: no tests to run
PASS
2015/06/25 11:56:29 | WARN  | goth/stat | STATHAT_KEY not set; StatHat events will NOT be tracked.
Running Suite: Rugen Suite
==========================
Random Seed: 1435247789
Will run 47 of 47 specs

••workers: 2015/06/25 11:56:29.783151 processing queue foo with 1 workers.
workers: 2015/06/25 11:56:29.784174 foo JID-162c1723974f00609467f7a9 start
workers: 2015/06/25 11:56:29.784201 foo JID-162c1723974f00609467f7a9 args:  [123,20150515,1431691200]
workers: 2015/06/25 11:56:29.784424 foo JID-162c1723974f00609467f7a9 done: 243.103µs
workers: 2015/06/25 11:56:29.789136 quitting queue foo (waiting for 0 / 1 workers).
•••••••••••••••dial tcp: lookup foo: no such host
•••dial tcp: lookup foo: no such host
•••••••••••••••••••••••••••
Ran 47 of 47 Specs in 2.307 seconds
SUCCESS! -- 47 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

(if some of that output looks odd, it’s because I’m using Ginkgo)

Much of the time `gb test` is OK, but:

1. I need test coverage results, so I need to use `go test` since `gb test` does’t currently support test coverage.
2. This is just disturbing because it makes me feel like there’s something fundamental I’m just missing related to how the GOPATH works and how `go test` works… what the hell is even going on?

Thanks!

**Comment by aviflax** [comment]
I just closed that terminal and opened a new one, and `go test` seems to be working OK now… I’m glad, but I still have no idea what was going on, or why opening a new terminal seems to have worked around the problem. I would be delighted if anyone can enlighten me. Thanks!

**Comment by davecheney** [comment]
Maybe you set project to the wrong thing, pwd might not be the right value.
You can use, gb env to recover the project root anywhere inside the project

**Comment by aviflax** [comment]
Hmm, maybe, thanks! I’ll re-open if it happens again.
