### ISSUE TITLE
Can gb help forking vendor packages?

### ISSUE THREAD

**Issue by ybogdanov** [constabulary/gb#239]
Hi,

I can't find an easy way of forking third-party packages in Go, especially of they refer themselves in import paths like this `import "github.com/docker/docker/nat"`. In this case if I fork docker, the path will be `github.com/ybogdanov/docker/nat` and it will break the whole thing.

A known solution is to use symlinks, but it is hard to manage when your package is pulled by someone else. Other solutions? Maybe I don't know something...

gb may help with something like `gb vendor link github.com/docker/docker github.com/ybogdanov/docker` which will pull `github.com/ybogdanov/docker`, create a symlink and save it to manifest. It should be also possible to maintain forked packages as a local git clone (within vendor/src?) or be able to link it from somewhere.

I feel that it's not that easy, but I am ready to contribute once there is a confirmed solution.

**Comment by davecheney** [comment]
> A known solution is to use symlinks, but it is hard to manage when your package is pulled by someone else. Other solutions? Maybe I don't know something...

I don't recommend symlinks when working with Go code. 

The vendor manifest file has all the parts needed for your requirements, they just aren't hooked up. For example, the manifest has separate fields for the importpath (github.com/docker/nat) and the upstream repository (github.com/ybogdanov/docker/nat). 

Possibly an invocation would look like

    gb vendor fetch -as github.com/docker/nat github.com/ybogdanov/docker/nat

This would overwrite the deduced import path with the one you supplied via `-as`.

**Comment by ybogdanov** [comment]
Thanks for quick response.

Your solution looks easy and straightforward. But how then work with a forked package while still keeping it in `vendor/src`? You have to be able to push your changes. You can do `git init` there, but I guess it will be removed once you do `gb vendor update -all`.

**Comment by davecheney** [comment]
The project's vendor directory is not for developing code, code that lives there is a copy of code that lives somewhere else. 

If you are keeping a long running fork of docker/nat for your project, I recommend doing this

    git clone https://github.com/ybogdanov/docker/nat $PROJECT/vendor/src/github.com/docker/docker/nat

**Comment by ybogdanov** [comment]
But what will happen if after it I run `gb vendor update -all`?

**Comment by davecheney** [comment]
> But what will happen if after it I run gb vendor update -all? 

If you follow my advice in https://github.com/constabulary/gb/issues/239#issuecomment-116016722 nothing will happen as that part of the vendor directory is not known to gb vendor as it is not in the manifest.

If you pursue https://github.com/constabulary/gb/issues/239#issuecomment-116013550 then the copy of the code in the vendor directory will be overwritten. 

You should decide if you want to develop the code in your gb project, or in a separate repository and vendor it with gb vendor.

**Comment by ybogdanov** [comment]
But what if I need both?
1. `gb vendor fetch -as github.com/docker/docker github.com/ybogdanov/docker` to let others easily work with my project using forked docker
2. `git clone https://github.com/ybogdanov/docker vendor/src/github.com/docker/docker` for me to work with my docker fork within the project

**Comment by davecheney** [comment]
> But what if I need both?
> 1. gb vendor fetch -as github.com/docker/docker github.com/ybogdanov/docker to let others easily  work with my project using forked docker

You should always check the contents of your vendored code into your project. Others pulling your project will then have the correct versions of vendored depedencies.

> 2. git clone https://github.com/ybogdanov/docker vendor/src/github.com/docker/docker for me to work with my docker fork within the project

If you like you could use git submodules, I don't know if that is an option for you.

**Comment by davecheney** [comment]
Closing as answered for the moment.
