### ISSUE TITLE
cmd/gb: add support for -gcflags

### ISSUE THREAD

**Issue by evertheylen** [constabulary/gb#240]
I would like to be able to configure flags when building the project, like this:

    go build -work helloworld.go

Is this possible? I have only found the possibility of passing linker flags.

**Comment by davecheney** [comment]
I'm not sure I understand the question. Do you want a flag to keep the
working directory after competition of the command?

**Comment by evertheylen** [comment]
The example has nothing to do with what I want to achieve, it's just an example. However, I can see some confusion, as the 'go' executable does not contain the compiler itself. A better example would be this:

How can I pass a flag to the compiler like this one: https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/lex.go#L228

(Again, just an arbitrary chosen example.)

**Comment by davecheney** [comment]
Thanks for explaining. I can add -gcflags to gb build.

**Comment by evertheylen** [comment]
That would be awesome :D
