### ISSUE TITLE
Question: how to fetch all dependencies to a fresh clone

### ISSUE THREAD

**Issue by ybogdanov** [constabulary/gb#244]
How to fetch all dependencies to a fresh project clone using locked versions of dependencies from a manifest, in case `vendor/src` is gitignored?
`gb vendor update -all` pulls the newest versions, but I want to keep those which are locked already.

Thanks.

**Comment by ybogdanov** [comment]
Found #175, but it's not clear to me. Are you talking about that checking vendor code into project source control is the only option?

**Comment by davecheney** [comment]
Yes, gb vendor does not seek to replace go get. gb expects all the code to be present in either `$PROJECT/src` or `$PROJECT/vendor/src`. To achieve this you could use gb vendor to copy that code into `$PROJECT/vendor/src` then check the resulting code in. Others have used git submodules.

gb does not take a position on what scheme you use to make sure all the source of a project is present at build time, but gb vendor does not seek to replace go get as it is concerned with reliable reproducible builds.

**Comment by ybogdanov** [comment]
Got it, thanks. What will happen if a project that is using gb is included to another project (as a dependency)? How then dependencies would be resolved?

**Comment by davecheney** [comment]
GB projects are not go gettable, and at the moment GB vendor will not
vendor them properly.

At the moment GB projects should represent the top of the tree.

**Comment by davecheney** [comment]
> Got it, thanks. What will happen if a project that is using gb is included to another project (as a dependency)? 

gb vendor expects dependencies to be go gettable, and at the moment gb projects are not go gettable (the project format does not match the go get format).

> How then dependencies would be resolved?

The project owner will probably be manually copying the bits over. In the future gb vendor might be able to help automate this, all the parts are there in the manifest, but they are not hooked up yet.

**Comment by davecheney** [comment]
`gb-vendor fetch` now supports recursive fetching of transitive dependencies. Explicitly fetching all dependencies, that is your code in `$PROJECT/src/` and no vendor directory will not be added as it will encourage people to use gb vendor fetch as a replacement for go get, which it is not.
