### ISSUE TITLE
Recursive Dependency Fetch Incorrectly Attempts to Fetch Native Packages

### ISSUE THREAD

**Issue by wmadisonDev** [constabulary/gb#245]
Operating System: Windows 7 Professional

    PS C:\git\stash\playground\cerebro> gb vendor fetch github.com/aws/aws-sdk-go
    fetching recursive dependency crypto/hmac
    skipping insecure protocol: http://crypto/hmac?go-get=1
    FATAL command "fetch" failed: unable to determine remote metadata protocol
    FATAL command "vendor" failed: exit status 1

crypto/hmac is actually native Go package and doesn't need to be fetched at all given that it's not a remote package. I can only infer that the recursive fetch isn't properly detecting which dependencies are non native and ought to be fetched via go get.

**Comment by davecheney** [comment]
Thanks for raising this bug. I'll look into it today.

**Comment by davecheney** [comment]
I cannot reproduce this on linux. I think this is probably a windows path issue (import paths and unix paths match, windows paths do not)
```
% gb vendor fetch github.com/aws/aws-sdk-go
fetching recursive dependency github.com/lsegal/gucumber
fetching recursive dependency github.com/shiena/ansicolor
fetching recursive dependency github.com/stretchr/testify/assert
fetching recursive dependency github.com/vaughan0/go-ini
```
