### ISSUE TITLE
$GOPATH/vendor and 3rd party libraries

### ISSUE THREAD

**Issue by Supermighty** [constabulary/gb#25]
Is there anything special about the $GOPATH/vendor directory? Could it store non-Go 3rd party libraries? I'm thinking about javascript and css libraries.

**Comment by davecheney** [comment]
Nothing special about it at all. It is currently hard coded in the tool,
but that is just a convenience, there is no reason why $PROJECT/*/src could
not be considered a vendor directory, leading people to very complicated

$PROJECT/src
$PROJECT/company/src
$PROJECT/3rdparty/src

etc, if they wanted.

With respect to assets, I'd be keep to define a standard place for them, I
propose

$PROJECT/assets

or a compromise of

$PROJECT/static

**Comment by Supermighty** [comment]
I don't have a good answer to this; I'm still playing around with where to keep everything. Where do assets go vs compiled js/css assets, 3rd party vs my own. I currently keep final assets in my web root $PROJECT/htdocs but at some point in expanding my build process, and integrating a pre-processor, I'll need a assets src location.

**Comment by davecheney** [comment]
Hmm. I think this might be outside what gb can offer.

gb is not a workflow system, it isn't make, so it cannot offer you the same
features of pre and post actions that you might need for minifying js, and
compressing css, etc.

For that, I recommend you use a Makefile in the root of your $PROJECT and
lay out the assets and compiled files in a way that makes most sense to
you. I'd probably avoid the vendor/ directory as that is effectively
reserved for 3rd party go source.

**Comment by Supermighty** [comment]
I agree this is outside the scope for gb. I'm learning `make` for the build system. The idea of storing assets in vendor seemed like a way to cut down on too many directories littering my workspace.

**Comment by davecheney** [comment]
I'm going to close this for the moment. Please reopen it if you have further questions.
