### ISSUE TITLE
gb vendor fetch: fails when fetching `git.apache.org/thrift.git/lib/go/thrift`

### ISSUE THREAD

**Issue by jtolds** [constabulary/gb#250]
If you run

```
gb vendor fetch git.apache.org/thrift.git/lib/go/thrift
```

gb vendor fetch fails. I assume this is due to the `.git` in the expected import path.

**Comment by davecheney** [comment]
Can you post the output you see please.

**Comment by jtolds** [comment]
```
~/Desktop$ mkdir -p test/src
~/Desktop$ cd test/
~/Desktop/test$ gb vendor fetch git.apache.org/thrift.git/lib/go/thrift
FATAL command "fetch" failed: lstat /tmp/gb-vendor-731544424/thrift: no such file or directory
FATAL command "vendor" failed: exit status 1
~/Desktop/test$ 
```

**Comment by jtolds** [comment]
I straced and now I'm convinced I simply have no idea what's going on. It might not be due to the .git bit. ¯\_(ツ)_/¯

**Comment by davecheney** [comment]
Thanks. I think I know what is going on, it is related to the path that
follows the segment ending in .git.

**Comment by davecheney** [comment]
Found the bug, fix coming rsn
