### ISSUE TITLE
gb vendor fetch <git repository>  fails on RHEL/Centos 6

### ISSUE THREAD

**Issue by asbjxrn** [constabulary/gb#257]
RHEL6/Centos6 uses git 1.7.1, which do not have the --exit-code option for ls-remote. 
This causes gb vendor fetch to fail. 

While these os's are getting old, RHEL6 is still widely used in big slow-moving companies.

**Comment by davecheney** [comment]
I'd like to make GB work for those older versions of git, do you have a
suggested replacement ?

**Comment by asbjxrn** [comment]
As it always returns 0, I think the alternative is to look at the output to see if the HEAD tag is found. Since the ls-remote searches for that tag specifically, it might be enough to simply check if output is more than 0 bytes but I haven't looked too much into it yet.

I see that there is an open pull request that changes the git command to using pkg/exec. I could try creating a pull request if you want, but should I wait for that one to be merged first?

**Comment by davecheney** [comment]
Nah, I won't merge that one til after gophercon, don't worry about merge
conflicts.

**Comment by davecheney** [comment]
Closed in 31f0b3fdea2ea4407c0050bf01bb0cc2dbd9ac33
