### ISSUE TITLE
Flags not being evaluated at the right time

### ISSUE THREAD

**Issue by wolfeidau** [constabulary/gb#26]
Just tried to add -R to override the project root and ran into the fact that the flags are not evaluated till after the plugins.

After adding a bit of debugging `*goroot, *goos, *goarch` will only ever get set to the default values.

https://github.com/constabulary/gb/blob/master/cmd/gb/main.go#L77

vs flags evaluated on

https://github.com/constabulary/gb/blob/master/cmd/gb/main.go#L100

**Comment by davecheney** [comment]
Can you check with the latest version, I think I fixed this problem last
night.

To be fair, -goos and -goarch aren't rrally tested, but I know -goroot works

**Comment by wolfeidau** [comment]
I pulled down the latest changes and added.

```go
	gb.Infof("goroot=%s goos=%s goarch=%s", *goroot, *goos, *goarch)
	tc, err := gb.NewGcToolchain(*goroot, *goos, *goarch)
```

Passed in arm as goarch and it is still set to amd64.

```
gb build -goarch=arm -goos=linux all
```

got

```
2015/05/02 10:18:38 INFO goroot=/usr/local/Cellar/go/1.4.2/libexec goos=darwin goarch=amd64
```

**Comment by davecheney** [comment]
Yup, that's a bug. I haven't tested GOOS/GOARCH only changing the toolchain
via -goroot, there is a chance those former values are hard coded.

I'll fix it.

**Comment by davecheney** [comment]
Note, unless you're using go1.5, to do cross compiles you'll have to do
that 'christen your cross compile toolchain dance', gb wont save you from
that, and in fact, it might make it worse as we always consider the
standard library to be up to date irrespective of the toolchain.

**Comment by davecheney** [comment]
@wolfeidau what i'm going to do is close this issue by removing -goarch and -goos. I'll open a new issue to make them work properly.
