### ISSUE TITLE
gb generate fails with Go installed from Fedora repos

### ISSUE THREAD

**Issue by Luit** [constabulary/gb#262]
`gb generate` uses `build.Context.GOROOT` to find the `go` tool, which fails when using Fedora's system package for Go because it's not at `$GOROOT/bin/go` but at `$GOROOT/bin/linux_amd64/go` (I'm not sure why).

Would using `exec.LookPath` here to find `go` break anything? I'm not familiar with the `build.Context`, and how it's constructed, so I'm not sure if this could find the wrong executable. For me, this version of `gb generate` works:

```diff
diff --git a/cmd/gb/generate.go b/cmd/gb/generate.go
index acf394a..a2592da 100644
--- a/cmd/gb/generate.go
+++ b/cmd/gb/generate.go
@@ -24,11 +24,15 @@ source files, for instance by running yacc.
 
 See 'go help generate'`,
        Run: func(ctx *gb.Context, args []string) error {
+               bin, err := exec.LookPath("go")
+               if err != nil {
+                       return err
+               }
                env := cmd.MergeEnv(os.Environ(), map[string]string{
                        "GOPATH": fmt.Sprintf("%s:%s", ctx.Projectdir(), filepath.Join(ctx.Projectdir(), "vendor")),
                })
 
-               args = append([]string{filepath.Join(ctx.GOROOT, "bin", "go"), "generate"}, args...)
+               args = append([]string{bin, "generate"}, args...)
 
                cmd := exec.Cmd{
                        Path: args[0],
```

**Comment by Luit** [comment]
Found out how the binaries end up in this nonstandard folder: http://pkgs.fedoraproject.org/cgit/golang.git/tree/golang.spec#n406 (lines 408-410)

**Comment by Luit** [comment]
The version I'm now using locally (with -n -x and -v options added too): https://github.com/constabulary/gb/compare/constabulary:45ec0f4...Luit:014193a

**Comment by Luit** [comment]
Fedora's 1.5betaX packages seem to have less broken behavior, symlinking instead of moving the binaries to the linux_amd64 folder

**Comment by davecheney** [comment]
@Luit I'm going to close this for the moment, I don't think there is much more to do here.
