### ISSUE TITLE
FATAL command "fetch" failed: stat /goroot/src: no such file or directory

### ISSUE THREAD

**Issue by markmandel** [constabulary/gb#266]
I get this error message whenever I use `go fetch ...`

It doesn't seem to actually affect everything, as I have a manifest file, and the import gets downloaded as well.

```bash
mark@laptop:~/workspace/gb-binary-distribution/gb-build$ gb vendor fetch github.com/gorilla/mux
FATAL command "fetch" failed: stat /goroot/src: no such file or directory
FATAL command "vendor" failed: exit status 1
mark@laptop:~/workspace/gb-binary-distribution/gb-build$ echo $GOROOT

mark@laptop:~/workspace/gb-binary-distribution/gb-build$ ls
Dockerfile  gb-build.iml  Makefile  Makefile.docker  src  vendor
mark@laptop:~/workspace/gb-binary-distribution/gb-build$ cd src/
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$ ls
web
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$ gb vendor delete github.com/gorilla/mux
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$ gb vendor fetch github.com/gorilla/mux
FATAL command "fetch" failed: stat /goroot/src: no such file or directory
FATAL command "vendor" failed: exit status 1
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$ printenv | GREP GO
GREP: command not found
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$ printenv | grep GO
mark@laptop:~/workspace/gb-binary-distribution/gb-build/src$
```

All my binaries are stored in /usr/bin

**Comment by markmandel** [comment]
I worked out the issue here. I needed to set the $GOROOT environment variable, since I had built this binary on a machine with a different GOROOT.

Is this still a bug?

**Comment by davecheney** [comment]
During debugging it was discovered that the version of gb was built on another system with a different GOROOT. This isn't something that gb can support at the moment; you have to built it on the same system, or at least on a system with an identically installed go toolchain.

I'd like to lift this restriction in the future, but I don't have any immediate ideas how to do so.
