### ISSUE TITLE
gb vendor fetch -tag is applied recursively, causing vendoring to fail

### ISSUE THREAD

**Issue by mholt** [constabulary/gb#270]
It looks like the -tag option is being recursed to the dependencies as well, though I'm only assuming that is what is happening based on the output:

```
$ gb vendor fetch -tag v0.7.2 github.com/mholt/caddy
fetching recursive dependency github.com/BurntSushi/toml
error: pathspec 'v0.7.2' did not match any file(s) known to git.
FATAL command "fetch" failed: exit status 1
FATAL command "vendor" failed: exit status 1
```

It looks like it's failing because there is no v0.7.2 tag of the toml repository. I'm new to gb, so if this is expected behavior, my apologies.

**Comment by abiosoft** [comment]
I can confirm this behaviour.

**Comment by davecheney** [comment]
Yup. That is what is happening, I'll fix it this afternoon.

**Comment by mholt** [comment]
Elegant and quick fix - thanks!
