### ISSUE TITLE
New feature: refresh/restore vendored dependencies

### ISSUE THREAD

**Issue by mmindenhall** [constabulary/gb#271]
I recently took a look at both `gb` and [wgo](https://github.com/skelterjohn/wgo) to manage dependencies for a new Go project at my company (our first).

I really liked the `wgo restore` command, and would like to propose a similar sub-command for `gb vendor`.  The rationale here is to avoid checking vendored dependencies into my source repo -- i.e., I want to `.gitignore` the `vendor/src` folder.  When a new developer joins the team, they would run `gb vendor refresh` (or whatever you want to call it) from the project root to fetch the current set of dependencies.

Someone might object that if a vendored dependency repo (or branch, or tag) was suddenly removed, the refresh could fail.  If something like that did happen, every developer on the team would still have the correct version in their `vendor/src` tree, so it would be easy enough to grab the dependency and check it in somewhere to avoid disruption in the short term.

**Comment by davecheney** [comment]
I'm sorry but I do not plan to add this feature. Please see #244
