### ISSUE TITLE
gb does not support ssh:// scheme

### ISSUE THREAD

**Issue by PSG-Luna** [constabulary/gb#272]
When trying to gb vendor fetch from a vanity URL containing an ssh:// path, which works fine with go get, and also used to work fine in gb, I get the following error:

     FATAL command "fetch" failed: unable to determine remote protocol

**Comment by davecheney** [comment]
Thanks for the report, this won't be hard to add. Can you send me (privately if you like) the metadata that ends up in the ssh:// repo so I can test the fix.

Ta

**Comment by PSG-Luna** [comment]
https://code.palmstonegames.com/chttp
