### ISSUE TITLE
gb-vendor: `fetch` should be able to *fix* missing dependencies.

### ISSUE THREAD

**Issue by chakrit** [constabulary/gb#277]
Manually copying dependencies is tedious and error-prone. It's even more tedious when migrating old projects with tons of scripts to use `gb`. Also even more cumbersome and error-prone if we go the git submodules route. Not everyone likes git submodules.

In standard GO workspace, one could simply do `go get ./...` inside the project's folder to automatically fix all its missing dependencies. This is not possible with `gb` at its current state.

**So I propose that `gb vendor fetch` should adopt this behavior by enumerating through `src/` packages and invoking `gb vendor fetch X` for each package `X` that's not already in the `vendor/src`**

Since we already have a `gb vendor purge` command adding this ability will allow a much much simpler and smoother flow for updating dependencies during development. Especially at the start of a project when one continuously adds and removes packages as things are being figured out.

This could even be combined with the `vendor purge` command into a `vendor fix` so that both `purge` and `fetch` would be run at the same time simplifying adding/removing dependencies during development.

**Comment by davecheney** [comment]
I am sorry but this is not in line with the goals of gb. This is for the following reasons

1. There is a one time setup cost when converting a project to gb, this is paid by the project owner and is proportional to the number of direct dependencies your code has. `gb vendor fetch` will already fetch any transitive dependencies automatically. On our largest project this involved running gb vendor fetch roughly twenty times, nor extreme by any measure.
2. Adding a command to automatically bring in a dependency when you start to use it in your code feels like automating the wrong thing. Having to `gb vendor fetch $DEP` is a tiny cost compared to the debate inside your team if you should be using that dependency, what is its licence, is it stable, is it maintained, etc. 
3. Most importantly, I have a grave fear that if there was a command that would fetch the entire graph of dependencies from the source in the `$PROJECT/src` directory, it would be abused to avoid vendoring _any_ code, and expecting `gb vendor fetch` to act as a replacement for `go get`, and at that point the differentiation that `gb` offers over `go get` would be significantly diminished.

Thank you for this feature request, but we will not be implementing it.

**Comment by chakrit** [comment]
I understand. Thanks for taking the time to explain it : )
