### ISSUE TITLE
$PROJECT/pkg hierarchy not compatible with other go tools.

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#279]
GB puts compiled packages into `$PROJECT/pkg/$GOOS/$GOARCH`.

The go tool puts compiled packages into `$GOPATH/pkg/$GOOS_$GOARCH`.

This discrepancy breaks tools that use the compiled package files, such as the popular autocomplete daemon [gocode](https://github.com/nsf/gocode#options).

**Comment by metral** [comment]
I currently symlink my project's pkg/linux/amd64 to pkg/linux_amd64 to allow gocode to keep working with gb

```ln -s linux/amd64/ linux_amd64```

**Comment by MerlinDMC** [comment]
Here is a quickly patched gocode that will work in gb projects once you have build them:

https://github.com/MerlinDMC/gocode (https://github.com/MerlinDMC/gocode/commit/85c63bdec7cd2dc6531cf2cb52d243a914ce6744)

I use that with vim-go and it looks sane enough for me :dancers:

**Comment by MerlinDMC** [comment]
This patch has been merged upstream ... so hopefully after you upgrade your gocode binary it should "just work"

**Comment by davecheney** [comment]
Duplicate of #202
