### ISSUE TITLE
Vendoring with large dependencies

### ISSUE THREAD

**Issue by Preetam** [constabulary/gb#280]
We currently use [Johnny Deps](https://github.com/VividCortex/johnny-deps) (jd) for dependency management. The general setup is that I have all of our dependencies in my GOPATH and they're all checked out to specific revisions. Therefore, there is a single copy of all of my dependencies. I can still get reproducible builds by checking out an older revision of my project and having jd checkout the proper revisions of the dependencies.

We have many repositories, and quite a few are referenced by multiple projects. What's a good way to vendor these dependencies using gb? I feel like using submodules would result in multiple copies of the same dependencies, which are probably also on the same revisions.

**Comment by davecheney** [comment]
I recommend using git submodules, they come at no cost to the repo size as they are effectively the git version of a symlink.

**Comment by davecheney** [comment]
Opps, I didn't mean to close this.

**Comment by Preetam** [comment]
This looks like what I need: [Git: Possible to use same submodule working copy by multiple projects?](http://stackoverflow.com/questions/27379818/git-possible-to-use-same-submodule-working-copy-by-multiple-projects)

**Comment by davecheney** [comment]
Closing as answered.
