### ISSUE TITLE
This might be a useful example

### ISSUE THREAD

**Issue by mickep76** [constabulary/gb#283]
This was a sample app. I wrote as a tutorial, might be useful to others thought.

https://github.com/mickep76/go-sampleapp

- Still needs some unit testing otherwise quite a complete example

**Comment by mickep76** [comment]
Added an example for building an Alpine Go image using gb:

https://github.com/mickep76/go-sampleapp-docker

Build image:

https://github.com/mickep76/alpine-golang
https://hub.docker.com/r/mickep76/alpine-golang/

**Comment by davecheney** [comment]
Thanks Michael,

How should we integrate this into the gb documentation?

**Comment by mickep76** [comment]
I'll have a look and see how it could be integrated.

**Comment by davecheney** [comment]
I'm going to close this for the moment, please feel free to send a PR to the constabulary/getgb.io repo.
