### ISSUE TITLE
Cross-compilation broken with Go 1.5?

### ISSUE THREAD

**Issue by pires** [constabulary/gb#289]
I'm a MacOS 10.10.x user and this `Makefile` used to work for me with `go 1.4.2` and a two month old `gb` release:
```
VERSION=$(shell cat VERSION)
local:
        GOOS=linux ARCH=amd64 gb build -ldflags "-w -X main.Version $(VERSION)-dev"
```

Now with `go 1.5-beta3` and latest `gb`, it doesn't.

```
$ GOOS=linux ARCH=amd64 gb build all
github.com/aws/aws-sdk-go/aws/awsutil
github.com/aws/aws-sdk-go/aws/awserr
github.com/vaughan0/go-ini
github.com/aws/aws-sdk-go/internal/endpoints
github.com/aws/aws-sdk-go/internal/protocol/query/queryutil
github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil
vendor/src/github.com/aws/aws-sdk-go/aws/awsutil/copy.go:4: can't find import: "io"
vendor/src/github.com/aws/aws-sdk-go/internal/endpoints/endpoints.go:7: can't find import: "strings"
vendor/src/github.com/aws/aws-sdk-go/internal/protocol/xml/xmlutil/build.go:5: can't find import: "encoding/base64"
vendor/src/github.com/aws/aws-sdk-go/aws/awserr/types.go:3: can't find import: "fmt"
FATAL command "build" failed: exit status 2
vendor/src/github.com/vaughan0/go-ini/ini.go:5: can't find import: "bufio"
vendor/src/github.com/aws/aws-sdk-go/internal/protocol/query/queryutil/queryutil.go:4: can't find import: "encoding/base64"
```

Any idea why?

**Comment by PSG-Luna** [comment]
It seems you didn't build the stdlib for GOOS=linux and ARCH=amd64 yet ?

**Comment by tianon** [comment]
Isn't this technically a dupe of #31 (since cross-compilation support doesn't really officially exist in "gb" yet)?

**Comment by davecheney** [comment]
gb needs to be built with the version of go you want to use. If you have update to 1.5beta3, please try rebuilding gb with that version.

Please note that cross compilation is not done (yet), so if works, that's unexpected.

**Comment by pires** [comment]
Ah, my bad. I forgot to compile `go` with `--with-cc-common`. The following fixed it and it's working again:
```
brew uninstall go
brew install go --devel --with-cc-common
rm -rf ~/Work/Projects/go/src/github.com/constabulary
go get github.com/constabulary/gb/...
```

Now, `make` is happy!

**Comment by davecheney** [comment]
Glad to hear it.

Fortunately when 1.5 ships, that flag will no longer be necessary.

**Comment by pires** [comment]
Awesome @davecheney! Thank you for `gb`.
