### ISSUE TITLE
FATAL command "build" failed: Gc: no Gofiles provided

### ISSUE THREAD

**Issue by metral** [constabulary/gb#292]
The new commit: https://github.com/constabulary/gb/commit/107eaaa57b50166458992db6d66ee844d258986b is causing this fatal build issue.

In a GB project with ./bin & ./pkg empty, doing a `gb build all` builds all the pkg's but, crashes at the end

**Comment by davecheney** [comment]
Thanks for the error report, can you please include the full build output, and with -v if you can.

**Comment by metral** [comment]
Sorry, i just noticed that the issue was on my end.

I had a barebones package with files declaring the package name and nothing else in the files themselves, and that was the cause of the issue. Closing
