### ISSUE TITLE
Do-nothing build takes 25 seconds

### ISSUE THREAD

**Issue by thockin** [constabulary/gb#294]
I reorganized the kubernetes (http://github.com/GoogleCloudPlatform/kubernetes) code into a gb project, with all our Godeps moved to vendor/src/.  `gb build` runs successfully.  Immediately running a second `gb build` (which obviously does nothing!) takes 25 seconds.

Can someone explain why this second build doesn't complete approximately instantly?

**Comment by davecheney** [comment]
Thanks for your report. Can you include the output of gb build -v which
will print timing information.

Thanks

Dave

**Comment by thockin** [comment]
https://gist.github.com/thockin/3eb57512f56954e04343

**Comment by davecheney** [comment]
ok, so what is going here is gb will always rebuild the final binary, that
is to say, it caches everything except the final binary. I think the
argument at the time was, if you said gb build, you want it to build
something, but given you example that doesn't make a lot of sense as you
have a lot of binaries and probably most of them are not stale all the time.

I'll change gb to not rebuild the final binary if it's source has not
changed which will save you a lot of linking time.

**Comment by thockin** [comment]
Honestly, if GB can get the do-nothing case down to a second or two, I
might make the case to use it.

It's a tough sell to be so "non-standard", but someone has to be an early
adopter.  We will have a lot of tooling issues to think about.  Overall, I
just miss having a Makefile to add my special cases.  Instead, we wrap 'go
build' in a script.  Puke.

Need to sort out how to properly deal with generated files (checking them
in is horrible).

**Comment by davecheney** [comment]
I spent yesterday working on this, and by working on this I mean noodling
with an integration test for this, and by that I mean downloading all the
dependencies for k8n. Damn, there are a lot of them, I though juju was bad.

Anyway, I think the fix should be simple, but I need to set up a test
harness first to verify the fix.

**Comment by davecheney** [comment]
I'm sorry, I didn't intend for that last update to come out as complainy as it did. 

What I meant to say was, I think your issue is important, but while preparing to work on it yesterday I ended up spending a lot of time on plumbing, and didn't get to the point of changing the code. I hope to be more productive today.

**Comment by thockin** [comment]
That was how I interpreted it, no swear :)

We have a big scope in a single repo, with a lot of deps.  We acknowledge
that is part of the problem :)

**Comment by davecheney** [comment]
I have a branch which reduces the do nothing case to effectively zero.
After a few more tweaks I should have something to propose today.

**Comment by thockin** [comment]
I am itching to try it.

**Comment by thockin** [comment]
Hallelujah, confirmed!

Now to see if I can glue together a process around what we do with godeps
and tests

**Comment by thockin** [comment]
thanks

**Comment by davecheney** [comment]
Nice. Please send bug reports.
