### ISSUE TITLE
gb vendor: fetching a "parent" package copies nested packages to vendor dir.

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#298]
`$ gb vendor fetch -no-recurse github.com/go-kit/kit/log`

Note that `github.com/go-kit/kit/log/levels` also exists in vendor dir, and is not registered in the manifest.

**Comment by davecheney** [comment]
Yup. Gb vendor assumes it has complete control over the vendor directory. I
will enhance this to bail out of vendoring a dependency will overwrite
existing contents.

**Comment by ChrisHines** [comment]
An additional concern with the current behavior is that vendoring a package also copies all of its nested packages, **even if they are not needed or wanted**. The result is that project code can import the unrequested packages, and those packages are not tracked in the manifest.

I would prefer `gb vendor` not to populate the vendor/src tree with packages not explicitly fetched or discovered while recursing.

**Comment by davecheney** [comment]
> An additional concern with the current behavior is that vendoring a package also copies all of its nested packages, even if they are not needed or wanted. The result is that project code can import the unrequested packages, and those packages are not tracked in the manifest.

Can you 

1. please open a new issue
2. give a concrete example of this. recursive dependency fetching should always walk from roots in the code from $PROJECT/src, not $PROJECT/vendor/src.

Having said that, gb vendor always vendors the entire repo that holds a particular import path. I think this is the least surprising way to do this.

**Comment by ChrisHines** [comment]
>Having said that, gb vendor always vendors the entire repo that holds a particular import path. I think this is the least surprising way to do this.

I see. That's not what I expected. Given my example above, I don't really want project code importing `github.com/go-kit/kit/log/levels` unless that package has been fetched and added to the manifest. I also don't necessarily want such packages filling up my project repository if they aren't being used.

**Comment by davecheney** [comment]
> I see. That's not what I expected. Given my example above, I don't really want project code importing github.com/go-kit/kit/log/levels unless that package has been fetched and added to the manifest. I also don't necessarily want such packages filling up my project repository if they aren't being used.

This is unavoidable, it something imports `github.com/go-kit/kit/log`, then we'll fetch `github.com/go-kit/kit` and copy the `log` subdirectory downwards. In fact even doing that is a mistake because `github.com/go-kit/kit/log` may depend on `github.com/go-kit/kit/log/levels` which may depend on `github.com/go-kit/kit`. So in fixing this issue I may end up vendoring more code than you asked for, not less.

**Comment by ChrisHines** [comment]
I think the current behavior is confusing because `gb vendor fetch` always recursively copies nested packages, and optionally recursively fetches dependencies. Furthermore, dependency based recursion updates the manifest, but nesting based recursion does not. This difference results in sometimes surprising behavior by other vendor sub-commands.

>So in fixing this issue I may end up vendoring more code than you asked for, not less.

I'm not sure what fix you had in mind. The fix that I was imagining would be not to recursively copy the nested packages. More specifically, given a repo containing the following files, and assuming that the two package do not depend on each other:

github.com/user/repo/pkg.go
github.com/user/repo/nested/other.go

`gb vendor fetch github.com/user/repo` would clone the repo into a temp dir, then copy only pkg.go.
`gb vendor fetch github.com/user/repo/nested` would clone the repo and copy only nested/other.go.

**Comment by davecheney** [comment]
> I'm not sure what fix you had in mind. The fix that I was imagining would be not to recursively copy the nested packages. More specifically, given a repo containing the following files, and assuming that the two package do not depend on each other:

I think this will be confusing. There will be parts of the vendored package which are visible in the source repo, but are missing in the vendored copy. 

In the example you gave, cherry picking packages out of repos will exacerbate the other issue you raised where removing one vendored dep caused another one to be removed.

To be clear, vendoring wastes disk space, I'm not going to address this with gb-vendor, in fact, I suspect fixing the issues you've raised here will cause more code to be vendored, not less.

**Comment by ChrisHines** [comment]
I am not sure how we would end up with more code getting vendored, but let's put that aside.

Perhaps I am misunderstanding the suggested workflow for `gb vendor` in the face of nested packages. Is it not recommended to do the following?

```
gb vendor fetch github.com/user/repo
gb vendor fetch github.com/user/repo/nested
```

Do we not want both packages in the manifest if they are both in the transitive import set of code under $PROJECT/src?

If not, then what should be done if the nested package were vendored early in a project's life, and only later the parent package was added as a dependency of the project?

Just to be clear, I was coming at this with the expectation that vendoring would treat each package as a standalone entity regardless of what repo it is stored in, in the same way that the go compiler treats packages.

**Comment by davecheney** [comment]
The first command, `gb vendor fetch github.com/user/repo` should prevent the second from succeeding as `github.com/user/repo/nested` is already covered by `github.com/user/repo`. If that does not happen it is a bug, but I think one I've already tried to fix.

> If not, then what should be done if the nested package were vendored early in a project's life, and only later the parent package was added as a dependency of the project?

Bad things, some effort has been made to handle this, but there are still edge cases.

> Just to be clear, I was coming at this with the expectation that vendoring would treat each package as a standalone entity regardless of what repo it is stored in, in the same way that the go compiler treats packages.

This is not true, gb vendor does not vendor _package_ it vendors _repositories_, which may contain many packages.

**Comment by ChrisHines** [comment]
>This is not true, gb vendor does not vendor package it vendors repositories, which may contain many packages.

OK. That's where I was going off the rails. I don't think that is clearly documented anywhere that I have seen. I think I was misled by the Path field on the [vendor.Dependency](http://godoc.org/github.com/constabulary/gb/vendor#Dependency) struct.

Does that mean that `gb vendor fetch github.com/user/repo/nested` should never be allowed? Or should `gb vendor` find the repo root and vendor the whole repo?

I will file other issues if I find `gb vendor` not working as described here.

**Comment by davecheney** [comment]
What it does now is fetch olny repo/ nested, which has a lot of fought edges, I think what I will do is change it to work like the go tool which always figures out the root of the repository and fetches the whole thing. I'm surprised that nobody has been bitten by this yet. I guess few use this feature.

**Comment by davecheney** [comment]
Oh, and it's certainly not your fault. This is something I'm still coming to understand fully as I explore the problem space.

**Comment by ChrisHines** [comment]
OK. Thanks for the quick answers. It sounds like the discussion helped clarify some things for you as well. Closing this issue with a much better idea how to use `gb vendor` as intended and better equipped to spot real issues. :smile_cat:

**Comment by kevinburke** [comment]
Any chance we could better document this behavior ?
