### ISSUE TITLE
gb-vendor: `purge` command fails with `golang.org/x/tools/go/loader/testdata` package inside vendor/.

### ISSUE THREAD

**Issue by chakrit** [constabulary/gb#300]
In one of my project codebases, when trying to switch a branch for a dependency, I ran:

```sh
$ gb vendor delete github.com/go-swagger/go-swagger
$ gb vendor purge
```

The last command results in:

```sh
FATAL command "purge" failed: import could not be parsed: /Users/chakrit/Documents/censored/app/vendor/src/golang.org/x/tools/go/loader/testdata/badpkgdecl.go:1:34: expected 'package', found 'EOF'
FATAL command "vendor" failed: exit status 1
```

It seems the imports scanner is (corretctly) being overeager in scanning the imports so it picks up a bad test data file that it should not need to care about. So it failed to purge the package.

How to resolve this besides manually deleting those packages (which may have other dependents that I might not know of)?

**Comment by chakrit** [comment]
Will update with a more specific repro later this week if I can.

**Comment by davecheney** [comment]
Thanks. That's the clue I need, itll be fowling on testdata/

This should be pretty simple to fix if you want to try.
