### ISSUE TITLE
gb not working with git2go

### ISSUE THREAD

**Issue by linuxerwang** [constabulary/gb#307]
My project needs to use https://github.com/libgit2/git2go. To statically compile with git2go, we have to compile libgit2 statically and git2go provides a "next" branch and scripts to build.  Since in gb vendor the .git was not reserved I can't use "git submodule" to fetch libgit2. Also the scripts provided by git2go doesn't work in vendor mode.  So here is what I did:

$ mkdir /tmp/test-git2go
$ cd /tmp/test-git2go
$ gb vendor fetch -branch next github.com/libgit2/git2go

This fetched git2go "next" branch without problem.

$ mkdir vendor/src/github.com/libgit2/git2go/vendor
$ cd vendor/src/github.com/libgit2/git2go/vendor
$ git clone https://github.com/libgit2/libgit2
$ cd libgit2
$ git co fb84cde81e11947add4ff8bb9b4084f7d76e6567 # libgit2 v0.22+1 for branch "next" 
$ cd ../..
$ ./script/build-libgit2-static.sh

Now libgit2 was successfully built under vendor/src/github.com/libgit2/git2go/vendor/libgit2/build.

$ export CGO_LDFLAGS="/tmp/test-git2go/vendor/src/github.com/libgit2/git2go/vendor/libgit2/build/libgit2.a -L/tmp/test-git2go/vendor/src/github.com/libgit2/git2go/vendor/libgit2/build -Wl,-Bsymbolic-functions -Wl,-z,relro -L/tmp/test-git2go/vendor/src/github.com/libgit2/git2go/vendor/libgit2/install/lib -lhttp_parser -lssh2 -lgcrypt -lrt -lgit2 -lssl -lcrypto -ldl -lz"

$ export CGO_CFLAGS=-I/tmp/test-git2go/vendor/src/github.com/libgit2/git2go/vendor/libgit2/include

$ gb build -v github.com/libgit2/git2go

Now I got this error message:

https://drive.google.com/open?id=0BwrTqzph0i12N0laQ1BHVW9VY2M

I think the issue here is that gb doesn't honor CGO_LDFLAGS and CGO_CFLAGS.  Any suggestions?

Thanks!

**Comment by linuxerwang** [comment]
Hmm, I pasted the wrong error message.  The output is big, please download this file: https://drive.google.com/open?id=0BwrTqzph0i12N0laQ1BHVW9VY2M

**Comment by davecheney** [comment]
Thanks for reporting your issue. gb is blowing up because of this flag you passed

    export CGO_LDFLAGS="/tmp/test-git2go/vendor/src/github.com/libgit2/git2go/vendor/libgit2/build/libgit2.a 

Is that correct, or is it missing a prefix like -o or -i or something ?

**Comment by linuxerwang** [comment]
Hi, Dave

I got the env vars from the git2go scripts:https://github.com/libgit2/git2go/blob/next/script/with-static.sh

Because I can not use this script directly under gb vendoring, I simple run it without args and copied out the env vars.  It worked for git2go with ./script/with_static.sh go install ./...

Without gb, I use this Makefile to build:

https://github.com/libgit2/git2go/blob/next/Makefile

Thank you for the help!

**Comment by davecheney** [comment]
Thanks for that. I still hold that what that script provides is not a flag,
it doesn't start with a hyphen.

That said, if it works with the go tool, I need to figure out why it
doesn't work with gb.

**Comment by linuxerwang** [comment]
Right. Please have a try on compiling git2go with "next" branch as in git2go web site. Another thing bewildered me is how to gracefully handle git submodule with gb. So far I have to git clone manually.

Thanks!

**Comment by davecheney** [comment]
> So far I have to git clone manually.

Place your git submodules in `$PROJECT/vendor/src/`

**Comment by davecheney** [comment]
@linuxerwang Further to what I wrote previously, gb expects all the source for the project to be present in `$PROJECT/src` or `$PROJECT/vendor/src`. How that source gets there is really up to you. You could vendor it all (possibly with the gb-vendor plugin, or manually), or set up git submodules at the correct locations in `$PROJECT/vendor/src/...`. It's really up to you what works best with your workflow.

**Comment by linuxerwang** [comment]
No problem with this point.  I think my issue is caused by how git2go manages its dependency on libgit2.  In git2go source it has a .gitmodule for the correct version of libgit2.  But "gb vendor fetch" removed the git information. I guess I can add a git submodule in my project, instead. Will try it later.

Thanks.

**Comment by davecheney** [comment]
Merging into #337. These are the same problem, but #337 is easier to reproduce.

**Comment by davecheney** [comment]
Sorry, #331
