### ISSUE TITLE
gb build a binary with given name

### ISSUE THREAD

**Issue by linuxerwang** [constabulary/gb#309]
Similar to "go build" supports -o flag, I feel it would be better if "gb build" supports specifying binary name:

gb build -o myserver package/.../crm_server

Thanks.

**Comment by davecheney** [comment]
Can you please explain why you need this feature. See #97

**Comment by linuxerwang** [comment]
The main reason is to use gb with bazel. In bazel, a best practice is that the binary name is the same as the target name, and target name can be anything (might different from the folder containing main package). This is important because the built binary might be used by other targets, like a target to build deb file.

**Comment by davecheney** [comment]
If gb were to place binaries into `$PROJECT/bin/$GOOS/$GOARCH` would this satisfy your requirement ?

**Comment by linuxerwang** [comment]
No. In bazel the binary would be in a folder as follows (suppose the bazel target is //src/x/y/z:my_binary):

$Project/
    |- bazel-bin/
    |      |- src/
    |           |- x/
    |               |- y/
    |                   |- z/
    |                       |- my_binary
    |- src/
          |- x/
              |- y/
                  |- z/
                      |- main.go

**Comment by davecheney** [comment]
I'm sorry, I was confused, I thought you were talking about this
https://bazil.org/fuse/ project.

It looks like bazel has a prescribed project layout which is incompatible
with gb's layout. I'm not sure adding extra flags to gb to make it put
things in the places bazel expected is the right solution. I think bazel
should build Go projects directly without shelling out to gb. What do you
think about that suggestion ?

**Comment by linuxerwang** [comment]
You are right, bazel (http://bazel.io) has its own project layout. But currently bazel team hasn't determined how to support golang in bazel so that it works for both Google internal and external projects. So the status quo now is that bazel has no golang support at all. But I really want to use both gb and bazel.  Also, I guess even if bazel added go build support it wouldn't support go vendoring, thus I still need gb to handle the vendor fetch.

**Comment by davecheney** [comment]
Closing as I don't think there is much more to do here. Bazel has one way it wants to build, gb has another, I don't think either are going to change much in the future.

**Comment by falzm** [comment]
I've come to a particular use case for this feature: building a project with arbitrary tags leads to a binary name including those tags, for instance:

```
gb build -tags "disable_mysql disable_postgres" cmd/controller
```

builds a binary named `controller-disable_mysql-disable_postgres`, which is quite unpleasant. Could you please reconsider implementing the `-o` flag from `go build`?

**Comment by uronce-cc** [comment]
Here is another detail in a similar scenario posted by @falzm, `gb build -tags "prod enable_add_cluster" manager` would produce binary with name `manager-enable_add_cluster-prod`, so `gb` sorts the tags before appending to the binary name.

**Comment by davecheney** [comment]
I am closing this as won't fix. I do not wish to add -o as gb is project based, not package based. -o makes no sense when you consider a project may produce multiple executables.
