### ISSUE TITLE
gb test: behavior for test-less package differs from `go test` behavior.

### ISSUE THREAD

**Issue by nullstyle** [constabulary/gb#311]
Hi!

It looks like the behavior of `gb test` has recently changed.  The process exits with status 1 when the provided package has no test files, whereas previous behavior (and current behavior of `go test`) would exit successfully.

Having a successful exit when there are no test files in a package allows for simpler CI scripts, since I need not inspect a package to see if it has any tests.  Any chance you could change the behavior back?

**Comment by davecheney** [comment]
@nullstyle I think this has been addressed indirectly in the 0.3.x release series. I'm going to close this issue, please reopen it if you find this is not correct.

**Comment by nullstyle** [comment]
Yep, it works for me now. Thanks!

**Comment by davecheney** [comment]
Thanks for confirming. I'm not sure when that got fixed.
