### ISSUE TITLE
Tests here require network access

### ISSUE THREAD

**Issue by tianon** [constabulary/gb#313]
The tests currently (rightfully so) require network access in order to test things like resolving import paths like `git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git` to the proper remote VCS repo.

Would you be open to either build tags to exclude those tests, or having `go test -short` exclude them for running the rest of the test suite networkless?

**Comment by davecheney** [comment]
The tests should be skipped in -short mode.

**Comment by tianon** [comment]
Oh, you've already got that.  Doh!  Sorry for the wasted time!

![](https://upload.wikimedia.org/wikipedia/commons/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg)

**Comment by davecheney** [comment]
No need to apologise, it reminded me to go and check if I had actually
implemented that feature.

**Comment by tianon** [comment]
:metal: :heart:

**Comment by tianon** [comment]
Just to follow up -- I've tested now and this is working very successfully. :+1:
