### ISSUE TITLE
gb project import path

### ISSUE THREAD

**Issue by tianon** [constabulary/gb#317]
Any plans to include some way for me to specify the import path of my project so that imports like `github.com/user/repo/src/some/xyz` work properly inside the project the same way they would for external projects looking to use packages from my project? (especially so that packages of mine that import other packages of mine work properly for people who aren't building from within my gb project)

My only idea for a workaround is a symlink in `vendor/src` to the top-level, which feels pretty hacky. :smile: (and I'm pretty sure `gb-vendor` will blow it away)

**Comment by davecheney** [comment]
Dup of #316
