### ISSUE TITLE
gb help plugins does not exist

### ISSUE THREAD

**Issue by e-dard** [constabulary/gb#318]
Just started to look through some gb docs and noticed that [godoc mentions](https://godoc.org/github.com/constabulary/gb/cmd/gb#hdr-Run_a_plugin) using `gb help plugins` to look up usage for running plugins. There is no `plugins` command to run though.

I assume the docs should say use `gb help plugin`, but then, when you do run `$gb help plugin` it says at the bottom of usage to look at `gb help plugins`.

All in all a but confusing. I would be happy to fix these typos but I'm not sure if a `plugins` command is being planned or whether everything should just be `plugin`?

**Comment by fatih** [comment]
Agree, I was thinking of writing a new plugin for gb and I thought I could find some help with `gb help plugin[s]` but with no luck. I too get caught in the same limbo as @e-dard .
