### ISSUE TITLE
gb build failed for go1.5

### ISSUE THREAD

**Issue by linuxerwang** [constabulary/gb#319]
I upgraded to go1.5, rebuilt the whole gb pkg/cmds, and "gb build" gave error:

FATAL command "build" failed: fork/exec /usr/share/go-golang/pkg/tool/linux_amd64/6g: no such file or directory

Also tried to rebuild gb with build tag (I know it's redundant):

go install --tags 'go1.5' github.com/constabulary/gb/cmd/gb
go install --tags 'go1.5' github.com/constabulary/gb/cmd/gb-vendor

But still "gb build" failed with the above error.

Thanks.

**Comment by davecheney** [comment]
It's likely that gb didn't get rebuilt, you can try adding the `-v` flag to go install, and seeing if it's actually doing anything.

Personally, I recommend removing `$GOPATH/pkg` and running `go install -v .../cmd/gb`

**Comment by linuxerwang** [comment]
Same issue. I even manually deleted .a and binary.

rm -rf pkg/linux_amd64/github.com/constabulary/gb/*
rm -rf bin/gb*
go install -v .../cmd/gb
go install -v .../cmd/gb-vendor

**Comment by davecheney** [comment]
Are you saying that go install did nothing ? Can you please include the
full output of what you see ?

**Comment by davecheney** [comment]
`/usr/share/go-golang/pkg/tool/linux_amd64/6g` is not a common installation path for Go. Where did you get this go install from ? Do you or have you set GOROOT ? If so, please do not, and repeat the procedure.

**Comment by davecheney** [comment]
Can you please include the ouput of `which go`, is it the version you expect ?

**Comment by linuxerwang** [comment]
gb and gb-vendor were installed correctly, I can run "gb vendor fetch" without problem.  The problem is when running "gb build".

I build my go1.5 from source code. And there is no 6g under /usr/share/go-golang/pkg/tool/linux_amd64/6g. I think go1.5 removed all 6g/6l etc. according to the release notes: https://golang.org/doc/go1.5#compiler_and_tools

No I did not set GOROOT.

**Comment by davecheney** [comment]
Thank you for confirming. My suspicion is that your go installation is not correct, and that incorrect value is being encoded into gb when it is compiled (because it must know this value to know where to find the compiler).

The fact that gb is using the go 1.4 behavior (looking for `6g`, not `compile`) also lead me to believe that the go installation on your computer is not correct. 

How have you installed go ? If you uninstall go and then issue `go`, does it suceed ? What are the values on your $PATH ?

**Comment by linuxerwang** [comment]
I downloaded the go1.5 source tarball, set GOROOT and GOROOT_FINAL to /usr/share/go-golang; compile the source with all.bash; the copy the whole source folder to /usr/share/go-golang; then create a symbol link /usr/bin/go to /usr/share/go-golang/bin/go.

user@host:/usr/share/go-golang$ tree -L 1
.
├── api
├── AUTHORS
├── bin
├── CONTRIBUTING.md
├── CONTRIBUTORS
├── doc
├── favicon.ico
├── lib
├── LICENSE
├── misc
├── PATENTS
├── pkg
├── README.md
├── robots.txt
├── src
├── test
└── VERSION

Thanks.

**Comment by linuxerwang** [comment]
And go env output:

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/advisory/go"
GORACE=""
GOROOT="/usr/share/go-golang"
GOTOOLDIR="/usr/share/go-golang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

$ go version
go version go1.5 linux/amd64

**Comment by davecheney** [comment]
Why would you do this ? Just download the binary tarball from the Go website and unpack it to the recommended location. This binary tarball is very well tested and known to work.

If you do wish to compile from source, my *strongest* recommendation is to _not set GOROOT_ and compile to a directory owned by your user. I outline the procedure here.

http://dave.cheney.net/2014/09/13/how-to-install-multiple-versions

I recommend following the advice outlined above and expect that this will resolve your problem installing gb.

**Comment by linuxerwang** [comment]
Still not working for me.

1. I rebuilt go from source. This time I didn't set any GOROOT paths. I untar source code to /home/tools/go-go1.5, built there, put bin in path. Removed pkg/ bin/ for gb. Generated gb and gb-vendor. "gb build" failed the same way.

$ /home/tools/go-go1.5/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GORACE=""
GOROOT="/home/tools/go-go1.5"
GOTOOLDIR="/home/tools/go-go1.5/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

2. I downloaded the prebuilt go tarball from golang.org. Note that it needs to be extracted to /usr/local/go.  Repeated the above steps, "gb build" filed the same way.

$ /usr/local/go/bin/go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by linuxerwang** [comment]
I have to go to bed now. But please let me know if anything else I should do to figure out the problem. Thanks.

**Comment by davecheney** [comment]
I'm sorry I haven't been able to fix it for you. Can you please confirm the modification time on your `gb` binary. Are you sure it is being rebuilt, are you sure that is the version that is being executed in your path ?

I added a check to gb in  34bdc62cb4823b2bcbb2cc3c9e9d1f12a6d20043 that should fail if the version of Go that build gb does not match the version of Go that is installed. Can you please try

     go get -u github.com/constabulary/gb/...

To download the latest version.

**Comment by linuxerwang** [comment]
The last look before go to bed. You are right! Didn't remember when I copied gb/gb-vendor to /usr/bin. That gave me a hard time. It's totally my fault.

Thank you so much, Dave.

**Comment by davecheney** [comment]
You're welcome, I'm glad you were able to find the problem.
