### ISSUE TITLE
Looking for VERSION file breaks builds on Fedora/CentOS

### ISSUE THREAD

**Issue by Marquis42** [constabulary/gb#325]
The RPM packages for Go in Fedora and CentOS do not have the VERSION file that gb is looking for in /usr/lib/golang.  Therefore, gb fails to function.

**Comment by tianon** [comment]
Aww @davecheney, looks like it wasn't just Gentoo this time.

What do you think about falling back to a shell-out to `go version` for naughty distros like Fedora and Gentoo?

**Comment by tianon** [comment]
(Or accelerating your plans to get mandated `VERSION` upstream :innocent:)

**Comment by tianon** [comment]
I'd also note that in fixing this by hand, I ran into `FATAL Go version does not match: gb was compiled with "go1.4.2", installed Go version from /usr/lib/go is "go1.4.2\n"` -- think a `strings.Trim` is warranted on the file contents as well?

**Comment by davecheney** [comment]
It's just easier to delete the check. Sorry for the inconvenience.

**Comment by PeteE** [comment]
@davecheney now we get:

go/src/github.com/constabulary/gb/cmd/gb/main.go:5: imported and not used: "io/ioutil"
go/src/github.com/constabulary/gb/cmd/gb/main.go:8: imported and not used: "runtime"
go/src/github.com/constabulary/gb/cmd/gb/main.go:9: imported and not used: "strings"

**Comment by davecheney** [comment]
Fixed, sorry.

**Comment by PeteE** [comment]
Thanks!

**Comment by davecheney** [comment]
Sorry for the breakage. That is what I get for making angry commits so soon
after rising.

**Comment by Marquis42** [comment]
Thanks for the fix, and thanks for a great tool!  After all, I wouldn't be filing bugs if I didn't care and/or wasn't using gb actively. :)

**Comment by davecheney** [comment]
Thanks. I appreciate it
