### ISSUE TITLE
env and vendor links at plugins page are directing to 404

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#336]
Hi,

The URL's `env` and `vendor` gives us 404 when visited:

http://getgb.io/plugins/
http://getgb.io/plugins/gb-env
http://getgb.io/plugins/gb-vendor

The correct paths (I believe) should be:

https://godoc.org/github.com/constabulary/gb/cmd/gb#hdr-Print_project_environment_variables
https://godoc.org/github.com/constabulary/gb/cmd/gb-vendor

**Comment by davecheney** [comment]
Thanks. Fixed, but possibly not in the way you were expecting :)
