### ISSUE TITLE
Cross compilation stop working if host OS binary is built

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#337]
Hi,

I just integrated https://github.com/fatih/images/ to gb. 

This works:

```
env GOOS=linux GOARCH=amd64 gb build
env GOOS=windows GOARCH=amd64 gb build
env GOOS=darwin GOARCH=amd64 gb build
```

however the following only creates for darwin and skips `linux` and `windows`:

```
env GOOS=darwin GOARCH=amd64 gb build
env GOOS=linux GOARCH=amd64 gb build
env GOOS=windows GOARCH=amd64 gb build
```

So if the host binary is available inside `bin/` folder it skips building for `linux` and `windows`. For now I just starting building for linux and windows and then move to darwin:

https://github.com/fatih/images/blob/master/Makefile#L25

**Comment by davecheney** [comment]
Thanks for the report, I know what that's happening, isStale is not taking into account the suffix.

**Comment by davecheney** [comment]
@fatih this should be fixed, but I had some trouble verifying the initial report. Could you please test and let me know if it's still broken. Thanks.

**Comment by fatih** [comment]
This has been indeed fixed and works as intended. Thanks Dave. Btw this is just a question totally related. the binary names are in the form of:

```
-rwxr-xr-x   1 fatih  staff  16432868 Sep  8 00:47 images*
-rwxr-xr-x   1 fatih  staff  16528840 Sep  8 00:47 images-linux-amd64*
-rwxr-xr-x   1 fatih  staff  16358400 Sep  8 00:47 images-windows-amd64.exe*
```

isn't it better if  name `images` as `images-darwin-amd64` when called explicitly with the envs `GOOS=darwin GOARCH=amd64`? This is something very minor, I'm just curious. Thanks again.

**Comment by davecheney** [comment]
> isn't it better if name images as images-darwin-amd64 when called
explicitly with the envs GOOS=darwin GOARCH=amd64?

If we can reliably detect the difference between the value being set, and
being inherited by default from runtime.{GOOS,GOARCH}, I agree. Please log
an issue for the cross compilation milestone.

**Comment by fatih** [comment]
Awesome. Here is the issue: https://github.com/constabulary/gb/issues/346 I couldn't add it to the milestone though (it's forbidden for non collaborator)
