### ISSUE TITLE
Cross compiled binary names should changed if envs are explicitly set

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#346]
Hi,

Based on the discussion #337, currently if we build with the following commands:

```bash
env GOOS=darwin GOARCH=amd64 gb build
env GOOS=linux GOARCH=amd64 gb build
env GOOS=windows GOARCH=amd64 gb build
```

it creates binaries with names:

```bash
-rwxr-xr-x   1 fatih  staff  16432868 Sep  8 00:47 images*
-rwxr-xr-x   1 fatih  staff  16528840 Sep  8 00:47 images-linux-amd64*
-rwxr-xr-x   1 fatih  staff  16358400 Sep  8 00:47 images-windows-amd64.exe*
```

Even though I've explicitly set the environment variables with `GOOS=darwin GOARCH=amd64`, the resulting binary is set to `images`. I think it could (should?) be named as `images-darwin-amd64` if the envs are set **explicitly**. 

Because I think iit would make it much more easier to group and create new artifacts (such as zip,tar, etc.. archives) based on the names. So we could create scripts such like `cp images-$GOOS-$GOARCH  out/$GOOS/` etc ...

**Comment by davecheney** [comment]
I think this is helpful for those automating cross compilation. They don't want the "native" build to be special, to have a different name that won't fit the pattern.

Open question, what should happen in this case `env GOOS=linux gb build ...` ?

**Comment by davecheney** [comment]
Most of the groundwork is in place for this. I should have it done by the end of the week.

**Comment by fatih** [comment]
> Open question, what should happen in this case env GOOS=linux gb build ... ?

I think it should build binaries for all possible architectures, such as i386, amd64, etc.. As I remember (not related I know) but https://github.com/mitchellh/gox does also the same if you only specify the OS.

**Comment by davecheney** [comment]
Hmm, that's an interesting idea, but has a few complications

- if GOOS=linux and GOARCH is not set, then to say GOARCH defaults to the
set of all architectures means build times go up, I'd prefer to keep it
explicit

- if neither GOOS and GOARCH is set, then a user may interpret that to be
"build natively", or "build all possible permutations"

If you want this behavior, maybe GOARCH=all would be more explicit

**Comment by fatih** [comment]
You are right, the `all` keyword is used already and would make sense for the current context. I too wouldn't like have a large build time.

**Comment by davecheney** [comment]
I like the idea. Here is the best way to implement it.

- GOOS/GOARCH handling happens in cmd/gb, there are some configuration
options on gb.Context now.
- GOOS/GOARCH=all should be handled in cmd/gb as well, by repeatedly
createing new contexts with the relevant variables.

**Comment by nickstenning** [comment]
Hi folks. I'm wondering if you've made any progress here? I just ran into this today -- having `gb build` write to different paths if `GOOS/GOARCH` matches `GOHOSTOS/GOHOSTARCH` makes writing Makefiles that work across architectures a bit tricky.

**Comment by davecheney** [comment]
Not much progress lately, the focus of the 0.3 series is gb test. See the
roadmap for more details.

I'd welcome a PR on this, but please discuss your change before you start
coding.

Thanks

Dave

**Comment by calmh** [comment]
I'd much prefer a way to get rid of the suffix altoghether. My build process, in shell pseudo code, resembles:

```
for os in linux darwin freebsd ... ; do
  for arch in 386 amd64 ; do
    rm -rf bin
    GOOS=$os GOARCH=$arch go build -i -v -o bin/mybinary ./cmd/mypkg
    tar zcvf myproject-$os-$arch.tar.gz bin/ etc/ otherstuff/
  done
done
```

Having the binary name be predictable and non-suffixed is important there.

**Comment by davecheney** [comment]
I'm sorry but I have decided that if you cross compile your binary will
have the appropriate suffix. Thank you for your understanding.

**Comment by rafael84** [comment]
Hi,

What about simply doing this?

```Diff
diff --git a/package.go b/package.go
index 8d3d61e..1faee8d 100644
--- a/package.go
+++ b/package.go
@@ -2,6 +2,7 @@ package gb
 
 import (
        "fmt"
+       "os"
        "path/filepath"
        "strings"
 
@@ -81,8 +82,8 @@ func (pkg *Package) Binfile() string {
                target = filepath.Join(pkg.Workdir(), filepath.FromSlash(pkg.ImportPath), "_test", binname(pkg))
        }
 
-       // if this is a cross compile or there are build tags, add ctxString.
-       if pkg.isCrossCompile() {
+       // if this is a cross compile or GOOS/GOARCH are both defined or there are build tags, add ctxString.
+       if pkg.isCrossCompile() || (len(os.Getenv("GOOS")) > 0 && len(os.Getenv("GOARCH")) > 0) {
                target += "-" + pkg.ctxString()
        } else if len(pkg.buildtags) > 0 {
                target += "-" + strings.Join(pkg.buildtags, "-")
```

For my scenario, this works as expected: when both GOOS and GOARCH environment variables are defined, the binary is named properly.

The current tests are passing:

```
go test ./...                                                                                                                                                           
ok  	github.com/constabulary/gb	4.781s
ok  	github.com/constabulary/gb/cmd	0.003s
ok  	github.com/constabulary/gb/cmd/gb	18.249s
?   	github.com/constabulary/gb/cmd/gb-vendor	[no test files]
?   	github.com/constabulary/gb/debug	[no test files]
ok  	github.com/constabulary/gb/fileutils	0.006s
ok  	github.com/constabulary/gb/importer	0.004s
ok  	github.com/constabulary/gb/test	12.450s
ok  	github.com/constabulary/gb/vendor	50.931s
```

My environment:

```
$ uname -a                                                                                                                                                                
Linux fiji 3.13.0-70-generic #113-Ubuntu SMP Mon Nov 16 18:34:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ go version                                                                                                                                                              
go version go1.5.2 linux/amd64
```

**Comment by davecheney** [comment]
LGTM. Do you want to submit a PR ? But please include some integration
tests in cmd/gb/gb_test.go. Copy pasta is your friend, look for a test that
uses gb.ExpectExecutable.

If this is too much, I can take a look later this week.

**Comment by rafael84** [comment]
Okay, I'll try to write some tests and then open a PR.

Thanks in advance

**Comment by rafael84** [comment]
I could not find anything named "ExpectExecutable", but I've found this:

```Go
// wantExecutable fails with msg if path is not executable.
func (t *T) wantExecutable(path, msg string) {
	if st, err := os.Stat(path); err != nil {
		if !os.IsNotExist(err) {
			t.Log(err)
		}
		t.Fatal(msg)
	} else {
		if runtime.GOOS != "windows" && st.Mode()&0111 == 0 {
			t.Fatalf("binary %s exists but is not executable", path)
		}
	}
}
```

That would be the utility method to be used on the new test cases, right?

**Comment by rafael84** [comment]
I've written three scenarios as follows:

```Diff
diff --git a/cmd/gb/gb_test.go b/cmd/gb/gb_test.go
index 3965185..b52bf23 100644
--- a/cmd/gb/gb_test.go
+++ b/cmd/gb/gb_test.go
@@ -1501,3 +1501,39 @@ package doctest
        gb.run("doc", "doctest")
        gb.grepStdout("Package doctest tests gb doc$", "expected Package doctest tests gb doc")
 }
+
+func TestIssue346(t *testing.T) {
+       gb := T{T: t}
+       defer gb.cleanup()
+       gb.tempDir("src/p")
+       gb.tempFile("src/p/main.go", `package main
+func main() { println("hello world") }
+`)
+       gb.cd(gb.tempdir)
+       tmpdir := gb.tempDir("tmp")
+
+       gb.setenv("TMP", tmpdir)
+
+       // scenario 1: GOOS/GOARCH not set
+       name := "p"
+       gb.unsetenv("GOOS")
+       gb.unsetenv("GOARCH")
+       gb.run("build")
+       gb.mustExist(gb.path("bin", name))
+       gb.wantExecutable(gb.path("bin", name), "expected $PROJECT/bin/p")
+
+       // scenario 2: GOOS/GOARCH are both set
+       goos := runtime.GOOS
+       name = fmt.Sprintf("p-%s-%s", goos, runtime.GOARCH)
+       gb.setenv("GOOS", goos)
+       gb.setenv("GOARCH", runtime.GOARCH)
+       gb.run("build")
+       gb.mustExist(gb.path("bin", name))
+       gb.wantExecutable(gb.path("bin", name), "expected $PROJECT/bin/p-$GOOS-$GOARCH")
+
+       // scenario 3: just GOOS is set
+       os.Remove(gb.path("bin", name))
+       gb.unsetenv("GOARCH")
+       gb.run("build")
+       gb.mustNotExist(gb.path("bin", name))
+}
```

These are the test results for the proposed changes in ```package.go```:
```
go test -v -run 'Issue346' cmd/gb/gb_test.go                                                                                                 
=== RUN   TestIssue346
--- PASS: TestIssue346 (0.45s)
	gb_test.go:179: running /tmp/testgb612411546/testgb [build]
	gb_test.go:189: standard output:
	gb_test.go:190: p
		
	gb_test.go:179: running /tmp/testgb612411546/testgb [build]
	gb_test.go:189: standard output:
	gb_test.go:190: p
		
	gb_test.go:179: running /tmp/testgb612411546/testgb [build]
	gb_test.go:189: standard output:
	gb_test.go:190: p
		
PASS
ok  	command-line-arguments	2.550s
```

And this proves that it fails with the original implementation of ```package.go```:

```
go test -v -run 'Issue346' cmd/gb/gb_test.go                                                                                                                                                                   
=== RUN   TestIssue346
--- FAIL: TestIssue346 (0.18s)
	gb_test.go:179: running /tmp/testgb931453791/testgb [build]
	gb_test.go:189: standard output:
	gb_test.go:190: p
		
	gb_test.go:179: running /tmp/testgb931453791/testgb [build]
	gb_test.go:426: /tmp/testgb776087346/bin/p-linux-amd64 does not exist (stat /tmp/testgb776087346/bin/p-linux-amd64: no such file or directory)
FAIL
exit status 1
FAIL	command-line-arguments	2.225
```

Is that enough to open the PR?

**Comment by davecheney** [comment]
SGTM.
