### ISSUE TITLE
gb test incorrectly passes flags to testing application

### ISSUE THREAD

**Issue by nsf** [constabulary/gb#349]
Simple project:
```
[nsf @ case]$ tree src
src
└── projectx
    └── main_test.go
```

Contents of `main_test.go`:

```go
package main

import (
	"flag"
	"testing"
)

var name = flag.String("name", "nsf", "what is your name")

func TestX(t *testing.T) {
	if *name != "jardin" {
		t.Fatalf("got: '%s', expected: 'jardin'", *name)
	}
}
```

Running `gb test`:
```
[nsf @ case]$ gb test -name=jardin
--- FAIL: TestX (0.00s)
        main_test.go:12: got: 'jardin=jardin', expected: 'jardin'
FAIL
FATAL command "test" failed: exit status 1
```

I'm using latest gb master as of now. 9c9026c

As you can see it passes flag as `<value>=<value>` instead of `<value>` for some reason.

**Comment by davecheney** [comment]
Thank you for raising this issue. This is pretty broken at the moment, I plan to tackle it in the 0.2 milestone.

**Comment by davecheney** [comment]
I thought that this was roughly fixed in 0.3.x, but it's not. Taking a look at this now.

**Comment by nsf** [comment]
Thanks.

**Comment by davecheney** [comment]
You're welcome. Sorry it took me so long to get to this. Now I have a
proper end to end test of the gb command so it makes it easier to construct
test scenarios.
