### ISSUE TITLE
build error "can't find import fmt" when $GOROOT not set

### ISSUE THREAD

**Issue by jbuberel** [constabulary/gb#35]
Just setting up a practice project, with the following structure:

```
$ find .
.
./bin
./bin/gb-env.exe
./bin/gb-vendor.exe
./bin/gb.exe
./bin/main
./pkg
./pkg/windows_amd64
./pkg/windows_amd64/github.com
./pkg/windows_amd64/github.com/constabulary
./pkg/windows_amd64/github.com/constabulary/gb
./pkg/windows_amd64/github.com/constabulary/gb/cmd.a
./pkg/windows_amd64/github.com/constabulary/gb.a
./src
./src/mytestproj
./src/mytestproj/main
./src/mytestproj/main/main.go
./vendor
./vendor/src
```

GOPATH, GOROOT are both unset. Go is installed in `/home/jbuberel/go`:

```
jbuberel@ubuntu:/media/sf_mymysqltestproj$ gb build -v -goroot="/home/jbuberel/go" all
2015/05/02 18:31:50 INFO project root "/media/sf_mymysqltestproj"
2015/05/02 18:31:50 DEBUG matchPackages: [/media/sf_mymysqltestproj/src] all
2015/05/02 18:31:50 DEBUG args: [mytestproj/main]
2015/05/02 18:31:50 DEBUG loadPackage: mytestproj/main
2015/05/02 18:31:50 DEBUG buildPackage: mytestproj/main
2015/05/02 18:31:50 DEBUG {main mytestproj/main /media/sf_mymysqltestproj/src/mytestproj/main} is a main package, not installing
2015/05/02 18:31:50 INFO compile mytestproj/main [main.go]
2015/05/02 18:31:50 DEBUG gc:gc mytestproj/main /media/sf_mymysqltestproj/src/mytestproj/main /tmp/gb086080072/mytestproj/main/main.a [main.go]
2015/05/02 18:31:50 DEBUG cd /media/sf_mymysqltestproj/src/mytestproj/main; [/home/jbuberel/go/pkg/tool/linux_amd64/6g -p mytestproj/main -pack -o /tmp/gb086080072/mytestproj/main/main.a -I /tmp/gb086080072 -I /media/sf_mymysqltestproj/pkg/linux/amd64 -complete main.go]
2015/05/02 18:31:50 INFO build duration: 5.121073ms map[compile:3.065923ms]
2015/05/02 18:31:50 command "build" failed: [/home/jbuberel/go/pkg/tool/linux_amd64/6g -p mytestproj/main -pack -o /tmp/gb086080072/mytestproj/main/main.a -I /tmp/gb086080072 -I /media/sf_mymysqltestproj/pkg/linux/amd64 -complete main.go]: exit status 1
main.go:4: can't find import: "fmt"
```
So I then set GOROOT, and remove the command-line option. The build works:
```
jbuberel@ubuntu:/media/sf_mymysqltestproj$ export GOROOT=/home/jbuberel/go
jbuberel@ubuntu:/media/sf_mymysqltestproj$ gb build -v all
2015/05/02 18:32:51 INFO project root "/media/sf_mymysqltestproj"
2015/05/02 18:32:51 DEBUG matchPackages: [/media/sf_mymysqltestproj/src] all
2015/05/02 18:32:51 DEBUG args: [mytestproj/main]
2015/05/02 18:32:51 DEBUG loadPackage: mytestproj/main
2015/05/02 18:32:51 DEBUG buildPackage: mytestproj/main
2015/05/02 18:32:51 DEBUG {main mytestproj/main /media/sf_mymysqltestproj/src/mytestproj/main} is a main package, not installing
2015/05/02 18:32:51 INFO compile mytestproj/main [main.go]
2015/05/02 18:32:51 DEBUG gc:gc mytestproj/main /media/sf_mymysqltestproj/src/mytestproj/main /tmp/gb614142370/mytestproj/main/main.a [main.go]
2015/05/02 18:32:51 DEBUG cd /media/sf_mymysqltestproj/src/mytestproj/main; [/home/jbuberel/go/pkg/tool/linux_amd64/6g -p mytestproj/main -pack -o /tmp/gb614142370/mytestproj/main/main.a -I /tmp/gb614142370 -I /media/sf_mymysqltestproj/pkg/linux/amd64 -complete main.go]
2015/05/02 18:32:51 INFO link /media/sf_mymysqltestproj/bin/main [/tmp/gb614142370/mytestproj/main/main.a]
2015/05/02 18:32:51 DEBUG cd .; [/home/jbuberel/go/pkg/tool/linux_amd64/6l -o /media/sf_mymysqltestproj/bin/main -L /tmp/gb614142370 -L /media/sf_mymysqltestproj/pkg/linux/amd64 /tmp/gb614142370/mytestproj/main/main.a]
2015/05/02 18:32:51 DEBUG removing work directory: /tmp/gb614142370
2015/05/02 18:32:51 INFO build duration: 120.359956ms map[compile:5.178768ms link:110.870078ms]
```

Is this an intended behavior?

**Comment by davecheney** [comment]
Is is inside some docker container, or another structs where the binary go installer is not used?

Gb has the GOROOT of the go install that compiled it, if that changes inside another environment, nothing will work.

**Comment by jbuberel** [comment]
I'm re-building the go install from source now, and will then rebuild `gb` and report back. I don't believe the install location was changed between gb build and invocation, but good to be sure.

**Comment by jbuberel** [comment]
Rebuilding the go installation fixed the problem. 

It may have been the result of having done an Ubuntu dist upgrade between building and running. Want me to find a place in the docs for a line like 'You need to run gb using the same go installation that was used to build it.'?

I'd be happy to send a pull request.

**Comment by davecheney** [comment]
> It may have been the result of having done an Ubuntu dist upgrade between building and running. Want me to find a place in the docs for a line like 'You need to run gb using the same go installation that was used to build it.'?
> I'd be happy to send a pull request.

Yes please

> The reason why I think this information would be important is for anyone who is planning to use Docker. If you want to use gb inside the docker container to build your application, you need to build gb inside the container too (using the same go installation).

It's slightly different, `gb` and the toolchain that built `gb` are linked at hip. Is there a reason why 

a. you're not using the binary version of Go from the website ?
b. building Go from source and expecting it to be in a different path inside the docker container ? would `$GOROOT_FINAL` be useful to paper over the gap here ?

**Comment by jbuberel** [comment]
*RE: gb and the use of goroot*

Before I start sending you crappy pull requests, I want to make sure I
understand this correctly. Is it correct to state that "When invoking gb
with the -goroot flag, the toolchain referenced by the flag value must be
the same go toolchain that was used to build gb."?

Or is this slightly less strong version more correct: "When invoking gb
with the -goroot flag, the toolchain referenced by the flag value must be
in the same location as the go toolchain that was used to build gb."?

The distinction is subtle, but I want to make sure I get it right.

*RE: Why on earth would I do such a thing?*

For reasons of simple convenience ("It was easy!"), the Dockerfile used for
Go deployments builds the Go tool from source. We may change that in the
near future, but for now, that's how the Dockerfile is constructed:

ENV GOLANG_VERSION 1.4.2
ENV PATH /go/bin:/usr/src/go/bin:$PATH
ENV GOPATH /go:/go/src/app/_gopath

RUN curl -sSL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz \
    | tar -v -C /usr/src -xz
RUN cd /usr/src/go/src && ./make.bash --no-clean 2>&1
RUN mkdir -p /go/src/app /go/bin && chmod -R 777 /go

That's why the answer to my question above is so critical. If I am going to
make gb work in this docker environment, I want to make sure that we build
gb from source inside the docker file using the go toolchain that will be
used when gb is invoked.

Does that make sense?


Jason L. Buberel
jason@buberel.org

**Comment by davecheney** [comment]
On 4 May 2015 8:12 am, "Jason Buberel" <notifications@github.com> wrote:
>
> *RE: gb and the use of goroot*
>
> Before I start sending you crappy pull requests, I want to make sure I
> understand this correctly. Is it correct to state that "When invoking gb
> with the -goroot flag, the toolchain referenced by the flag value must be
> the same go toolchain that was used to build gb."?

The reason I added -goroot was so I could test go1.4 and 1.5, its not meant
to be needed in the general case, and probably indicates a symptom of a
larger problem.

>
> Or is this slightly less strong version more correct: "When invoking gb
> with the -goroot flag, the toolchain referenced by the flag value must be
> in the same location as the go toolchain that was used to build gb."?
>
> The distinction is subtle, but I want to make sure I get it right.
>
> *RE: Why on earth would I do such a thing?*
>
> For reasons of simple convenience ("It was easy!"), the Dockerfile used
for
> Go deployments builds the Go tool from source. We may change that in the
> near future, but for now, that's how the Dockerfile is constructed:
>
> ENV GOLANG_VERSION 1.4.2
> ENV PATH /go/bin:/usr/src/go/bin:$PATH
> ENV GOPATH /go:/go/src/app/_gopath
>
> RUN curl -sSL https://golang.org/dl/go$GOLANG_VERSION.src.tar.gz \
> | tar -v -C /usr/src -xz
> RUN cd /usr/src/go/src && ./make.bash --no-clean 2>&1
> RUN mkdir -p /go/src/app /go/bin && chmod -R 777 /go

I don't understand what this line does,  doesn't appear to have anything to
do with the preceding line. Is it making a GOPATH?

>
> That's why the answer to my question above is so critical. If I am going
to
> make gb work in this docker environment, I want to make sure that we build
> gb from source inside the docker file using the go toolchain that will be
> used when gb is invoked.
>
> Does that make sense?

I think the disconnect is when gb is invoked inside the environment built
by this dockerfile, the go toolchain is no longer present at /usr/local/go.
From some issues reports it appears to be in /usr/google/something

Can you confirm if this is correct.

>
>
> Jason L. Buberel
> jason@buberel.org
>
> On Sun, May 3, 2015 at 2:17 PM, Dave Cheney <notifications@github.com>
> wrote:
>
>
> > It may have been the result of having done an Ubuntu dist upgrade
between
> > building and running. Want me to find a place in the docs for a line
like
> > 'You need to run gb using the same go installation that was used to
build
> > it.'?
> > I'd be happy to send a pull request.
> >
> > Yes please
> >
> > The reason why I think this information would be important is for anyone
> > who is planning to use Docker. If you want to use gb inside the docker
> > container to build your application, you need to build gb inside the
> > container too (using the same go installation).
> >
> > It's slightly different, gb and the toolchain that built gb are linked
at
> > hip. Is there a reason why
> >
> > a. you're not using the binary version of Go from the website ?
> > b. building Go from source and expecting it to be in a different path
> > inside the docker container ? would $GOROOT_FINAL be useful to paper
over

**Comment by davecheney** [comment]
Basdled on our discussion today in going to mark this closed for the moment.
