### ISSUE TITLE
For go vendor — do not restore already exists modules in vendor path

### ISSUE THREAD

**Issue by kalloc** [constabulary/gb#350]
Hi.

If i'm already have all modules except one and only want to add one module, now I must re-download all modules.
It's a not good, may be we need additional param for gb-vendor restore?
```
gb vendor restore --skip-exists 
```

**Comment by davecheney** [comment]
Sorry, that is correct.

gb vendor restore is _not_ the intended mode of operation, the expected mode of operation is to store your source code in vendor/, not use gb vendor restore as a replacement for go get.

I'm going to make this as closed as I do not intend to add this feature for the reason stated above. If you want to work on it, please reopen and assign to yourself.

**Comment by kalloc** [comment]
Do you know another way to install dependancies to vendor directory ?

**Comment by kalloc** [comment]
Can I do this functional for gb-vendor restore?

**Comment by kalloc** [comment]
@davecheney

**Comment by davecheney** [comment]
@kalloc gb vendor is a plugin that helps you maintain the contents of your vendor/src/ directory. The expected use is, gb vendor fetch <SOMETHING>, then commit the contents of vendor/src/

**Comment by gobwas** [comment]
+1 this could be useful tool for gb. 

In my case, I want to deny `gb vendor restore` to restore some repos, i.e.:

```bash
# Restore all, excepts
gb vendor restore --ignore github.com/...
```
or

```bash
# Restore all from
gb vendor restore github.com/...
```

Make sense @davecheney?

**Comment by davecheney** [comment]
I am sorry for not replying earlier. I will not be adding this functionality. gb cares about repeatable builds, and your suggestion will further encourage people to not vendor their code, but instead ship with the manifest file only and expect users to use restore to recover the source.

**Comment by kalloc** [comment]
@davecheney I understand you, but I'm worrying about cpu usage and projects making time.
If I can skip already exist depends in vendor path, I can make build faster than when I can't skip.
Can I write solution and create pull request?

**Comment by davecheney** [comment]
Can you explain more about your build process. How does gb vendor restore
dominate your build time?

**Comment by kalloc** [comment]
@davecheney of course :)

Let's I show my Makefile file
```
all: deps test build

deps:
        gb vendor restore
        
build:
        env GOOS=darwin GOARCH=amd64 gb build
        env GOOS=linux GOARCH=amd64 gb build

test:
        vet src/project
        cd src/project && GOPATH=${PWD}:${PWD}/vendor/ go test -cover -test.coverprofile=../../reports/cover.out

```

Restoring all dependancies takes much time. I'm living (Russia, Indonesia, Urkaine) in country with poor internet connection, sometimes I'm working via EDGE connection. I don't want to download packages all time.
I'm going to create pull-request to support special flag (like --install-only), if you wouldn't mind.

p.s. Have a nice week ;)

**Comment by gobwas** [comment]
@davecheney @kalloc and other case is: behind the firewall build server could not connect to github.com, and developers add dependencies into the vendor/src manually, and then commit them. After that, build server should restore only allowed to connect repos. 

Thanks )

p.s. @kalloc in Moscow should be a good Internet Connection ;-)

**Comment by kalloc** [comment]
@davecheney the time takes to build the project
```
time make deps
…

real    3m36.935s
user    0m13.451s
sys     0m8.487s
```

```
time make build
env GOOS=darwin GOARCH=amd64 gb build
…
env GOOS=linux GOARCH=amd64 gb build
…
real    0m8.845s
user    0m19.256s
sys     0m2.909s
```

**Comment by kalloc** [comment]
@gobwas yes, you are right, Moscow's internet better than Kaluga's or Krasnodar's

**Comment by davecheney** [comment]
Respectfully, you are using gb vendor incorrectly. The expected use case is
your project will contain all the source of your code, and the depedencies,
vendored into project/vendor/src. The expected use case is _not_ to use gb
vendor restore to avoid vendoring your code, and this is why you are
hitting limitations.

I am afraid I am not willing to accept patches to alter gb vendor restore
for the reasons described above.

Can I suggest that if you do not wish to vendor you code, you use git
submodules or subtrees instead.

**Comment by kalloc** [comment]
@davecheney Sorry, help me to understand right use case.
I make example project (https://github.com/kalloc/gb-wrong-example), tell me, what's wrong with him.
I am not seeing difference between https://github.com/constabulary/example-gsftp and my case.

**Comment by kalloc** [comment]
@davecheney Oh, you mean, I should store all dependancies source in the project? 
It is an overhead

**Comment by davecheney** [comment]
@kalloc that's fine. Let me explain the philosophy of gb. A gb project must contain all the source, including dependencies, however gb itself does not take care of this, it is left to the project owner to decide how to collect all the dependencies into the gb project structure.

One way to do this is to use the _optional_ gb vendor plugin, which will copy the source of your dependencies into your project. This plugin is optional and not integrated into gb in any way apart from living in the same repository. 

gb vendor is as opinionated as gb, so has a set way of working. If this doesn't fit your use case, you don't need to use it.

If you prefer not to vendor your code, then one option is to use git submodules or subtrees, whichever you prefer.

**Comment by kalloc** [comment]
@davecheney Is it possible to use submodule and gb vendor together ?

**Comment by davecheney** [comment]
gb vendor doesn't know about anything in the manifest file, that is, if it didn't vendor it, it doesn't know about it.

With that said, gb doesn't know about gb vendor either, all it cares about is the right code is on disk at the right location.

**Comment by kalloc** [comment]
@davecheney ok, gb isn't that I need, I will look for another tools for dependancies manager, compatible to vendor
