### ISSUE TITLE
What about "gb vendor tree"

### ISSUE THREAD

**Issue by hyper-carrot** [constabulary/gb#360]
I can know what the project's dependent packages via `gb vendor list`, but I don't know their dependency relationship.

**Comment by davecheney** [comment]
I've played around with this visualisation before and it quickly gets out of hand.

http://dave.cheney.net/2014/11/21/visualising-dependencies

If you want to try this, feel free, but I would like to see it implemented as Andrew showed in his talk, http://talks.golang.org/2015/tricks.slide#50

gb vendor has a list subcommand, so implementing the missing commands and fields feels like the right way to do it.

**Comment by hyper-carrot** [comment]
Yeah, I will keep my attention to this.

**Comment by davecheney** [comment]
Closing this as I don't plan to work on this. If you want to work on this please

1. reopen this issue to discuss your design.
2. preferably implement this as a plugin.
