### ISSUE TITLE
cmd/gb conflicts with git branch alias

### ISSUE THREAD

**Issue by xiocode** [constabulary/gb#4]

**Comment by davecheney** [comment]
Im sorry to hear that, I am not planning on changing the name of the tool at the moment, you could rename gb to something else to work around this.

**Comment by elithrar** [comment]
This is usually an issue with the oh-my-zsh git plugin, and not a standard git install.

If you `alias gb=$GOPATH/bin/gb` after the git plugin is imported it will solve it. Or fork the git plugin and remove the alias.

**Comment by xiocode** [comment]
@elithrar thank u

**Comment by davecheney** [comment]
I've had a second report of this issue so I want to reopen the bug for discussion.

The core problem appears to be that some shells and installers (for git I think) create `alias gb=git something` in the user's shell. Annoyingly the user has probably never even used this alias, so are very confused when after installing `gb`, it acts like a broken git command.

The solution is to rename `gb`, possibly to `gbt`, _go build tool_. This would also resolve #11 

However I am not proposing that at this time, I would like to leave this issue open for others to comment so I can get a feel for just how big of an issue this potential conflict is.

/cc @wkennedy

**Comment by demizer** [comment]
I ran into this today with the prezto config framework for ZSH. All I had to do to fix it was to rename the aliases from gb* to gbr*. It was easy for me because I have forked the prezto repo, but the standard install procedure for most ZSH config frameworks is to clone it into $HOME, which would make the situation a little more complicated.

Renaming the gb command is not necessary; users should update their aliases.

**Comment by elithrar** [comment]
For posterity: `echo "alias gb=$GOPATH/bin/gb" >> $HOME/.zshrc && source
$HOME/.zshrc` should do the trick for most where an existing alias
conflicts with gb.

As per my other comment, one of the most common causes is the "git" plugin
for oh-my-zsh which defines a LOT of git-related aliases that you'll never
know about unless you dig through the output of `alias`.

(I also wouldn't rename the tool either!)

**Comment by davecheney** [comment]
Can someone include the output they see when oh my zsh takes over, I'll write a fan entry and close this issue.

**Comment by elithrar** [comment]
```sh
~ gb
fatal: Not a git repository (or any of the parent directories): .git
~ which gb
gb: aliased to git branch
```
