### ISSUE TITLE
vendor fetch can't fetch gb project package

### ISSUE THREAD

**Issue by jarod** [constabulary/gb#405]
if github.com/user/proj/pkg is a gb project, when you run vendor fetch:
```
gb vendor fetch github.com/user/proj/pkg
FATAL command "fetch" failed: lstat /tmp/gb-vendor-534316392/proj: no such file or directory
FATAL command "vendor" failed: exit status 1
```

**Comment by jarod** [comment]
sorry. duplicated with #352

**Comment by davecheney** [comment]
I'm sorry gb vendor fetch can only handle projects on go get format. This is a limitation, please see other related issues
