### ISSUE TITLE
gb vendor fetch -tag, doesn't fetch tag if supplied with --no-recurse

### ISSUE THREAD

**Issue by grubernaut** [constabulary/gb#410]
Almost opposite of #270:

```
$ gb vendor fetch --tag v0.9.9 --no-recurse github.com/aws/aws-sdk-go

$ cat vendor/manifest
{
	"version": 0,
	"dependencies": [
		{
			"importpath": "github.com/aws/aws-sdk-go",
			"repository": "https://github.com/aws/aws-sdk-go",
			"revision": "7553d5227962c0f226768d0435881e99ec0cab35",
			"branch": "master"
		}
	]
}%
```

Yet, allowing recursion, `gb vendor fetch -tag`, works as expected:

```
$ gb vendor fetch -tag v0.9.9 github.com/aws/aws-sdk-go
....
╰─$ cat vendor/manifest
{
	"version": 0,
	"dependencies": [
		{
			"importpath": "github.com/aws/aws-sdk-go",
			"repository": "https://github.com/aws/aws-sdk-go",
			"revision": "c4ae871ffc03691a7b039fa751a1e7afee56e920",
			"branch": "HEAD"
		},
......
```

Not too critical of a bug, as I can keep recursion in until fixed, just increases the size of the project. 

Thanks for the awesome tool!

**Comment by davecheney** [comment]
--tag and --no-recurse are not flags, sorry. Can you retry your original
example with -tag and -no-recurse

**Comment by grubernaut** [comment]
sorry, must have typed/copied them wrong

```
$ gb vendor fetch -tag v0.9.9 -no-recurse github.com/aws/aws-sdk-go

$ cat vendor/manifest
{
	"version": 0,
	"dependencies": [
		{
			"importpath": "github.com/aws/aws-sdk-go",
			"repository": "https://github.com/aws/aws-sdk-go",
			"revision": "7553d5227962c0f226768d0435881e99ec0cab35",
			"branch": "master"
		}
	]
}%
```

**Comment by grubernaut** [comment]
Looks like it may be from here: https://github.com/constabulary/gb/blob/master/cmd/gb-vendor/fetch.go#L108

**Comment by grubernaut** [comment]
Pardon my ignorance though, first use of `gb`. Does convention stand that I should include recursive dependencies on a project anyways?

**Comment by davecheney** [comment]
I'm not sure I understand. The dependencies of a Go project are a set, not
a tree.

**Comment by davecheney** [comment]
What I mean to say is, the contents of $project/vendor/src represent the
set of all packages required either directly or transitively from the code
in $project/src. I think the simplest answer to your question is, yes.

**Comment by grubernaut** [comment]
Okay cool, thank you

**Comment by grubernaut** [comment]
Awesome, thanks!
