### ISSUE TITLE
gb build: cross compile + tags leads to duplication in filename

### ISSUE THREAD

**Issue by tianon** [constabulary/gb#414]
If I do something like `GOOS=windows GOARCH=386 gb build -tags lol`, my final binary name is `cmd-windows-386-lol-lol.exe` instead of just `cmd-windows-386-lol.exe` (due to `ctxString` being added during cross-compile and `buildtags` being included in that).

My thoughts for fixing this would be to use `Suffix()` for both instead, which prepends the `-` appropriately, but the problem there is that it always adds both `gotargetos` and `gotargetarch` regardless of cross-compile.  Since `Suffix()` is _only_ used for `GB_BIN_SUFFIX` in `gb info` (which on my machine is always `GB_BIN_SUFFIX="-linux-amd64"` unless cross-compiling or using tags), I'm confused about this discrepancy, since the name suggests that it's the suffix that'll be appended to the names of binaries output by `gb build`, and thus should be the empty string for no tags and no cross-compile, right?  If this sounds like I'm on the right track, I'm happy to resurrect those parts of #411 as appropriate, but if I'm on the wrong track then I'd really appreciate some insight into what `GB_BIN_SUFFIX` is useful for. :innocent:

Essentially:
```diff
diff --git a/context.go b/context.go
index feac334..0d4a766 100644
--- a/context.go
+++ b/context.go
@@ -167,7 +167,12 @@ func (c *Context) Pkgdir() string {
 // Suffix returns the suffix (if any) for binaries produced
 // by this context.
 func (c *Context) Suffix() string {
-	suffix := c.ctxString()
+	v := []string{}
+	if c.isCrossCompile() {
+		v = append(v, c.gotargetos, c.gotargetarch)
+	}
+	v = append(v, c.buildtags...)
+	suffix := strings.Join(v, "-")
 	if suffix != "" {
 		suffix = "-" + suffix
 	}
diff --git a/package.go b/package.go
index ed26ccb..b30a534 100644
--- a/package.go
+++ b/package.go
@@ -91,15 +91,7 @@ func (pkg *Package) Binfile() string {
 		target = filepath.Join(pkg.Bindir(), binname(pkg))
 	}
 
-	// if this is a cross compile, add ctxString
-	if pkg.isCrossCompile() {
-		target += "-" + pkg.ctxString()
-	}
-
-	// append build tags
-	if len(pkg.buildtags) > 0 {
-		target += "-" + strings.Join(pkg.buildtags, "-")
-	}
+	target += pkg.Suffix()
 
 	if pkg.gotargetos == "windows" {
 		target += ".exe"
```
(leaving `ctxString` alone since it's used for more things, like `pkg/` subdirectory names where it's important to have `gotargetos-gotargetarch` regardless of cross-compile status)

**Comment by tianon** [comment]
To illustrate further, `GOOS=windows GOARCH=386 gb build -tags 'lol omg'` leads to `cmd-windows-386-lol-omg-lol-omg.exe`.

**Comment by tianon** [comment]
(I don't know if it warrants its own issue, but it's worth noting also that `go build -tags 'a b' -tags c` is the same as `go build -tags 'a b c'` or `go build -tags a -tags b -tags c` -- not sure if parity with how `go(1)` handles `-tags` flags is something you care about. :smile:)

**Comment by davecheney** [comment]
Thanks for raising the issue, I thought I added a test case for that, I'll
check when I get home.

**Comment by davecheney** [comment]
@tianon we use the same logic as the go tool does for parsing `-tags`, whatever works for `go`, works for gb.

**Comment by davecheney** [comment]
@tianon as an aside ctx.Suffix only exists to let gb info print out the value. It should be as dumb as possible, that is, the logic should live somewhere else.

**Comment by tianon** [comment]
Ok, fair enough! :+1:

**Comment by tianon** [comment]
(Also, I've double-checked how `go(1)` handles `-tags` and you're indeed correct -- now to go figure out in which software project I've bungled that assumption...  :confounded:)

**Comment by davecheney** [comment]
```
DEBUG cd .; [/home/dfc/go/pkg/tool/linux_amd64/link -o /home/dfc/bin/gb-linux-386-lol-lol -L /tmp/gb501007969 -L /home/dfc/pkg/linux-386-lol -buildmode exe /tmp/gb501007969/github.com/constabulary/gb/cmd/gb/main.a]
DEBUG build duration: 13.331123931s map[gc:32.547943483s asm:667.540463ms pack:194.268204ms link:3.091007647s]
```
Confirmed, I'll have a fix asap,
