### ISSUE TITLE
Allow override fetch package already vendored

### ISSUE THREAD

**Issue by laco0416** [constabulary/gb#420]
If the package `foo` was vendored in fetching another pachage `bar`, I cannot fetch `foo` after `bar`.

```
gb vendor fetch <bar> 
gb vendor fetch <foo>

> FATAL command "fetch" failed: <foo> is already vendored
```

Please allow overriding package already vendored.

**Comment by davecheney** [comment]
Have you tried gb vendor update <foo> ?

**Comment by laco0416** [comment]
yes, but `gb vendor update` needs an existing dependency. 

I need a solution to install a new package, and I want not to mind other packages in order to fetch the package.

**Comment by laco0416** [comment]
Simply, I want `gb fetch -u` just like `go get -u`. :smiley:

**Comment by laco0416** [comment]
expected work flow:

```
# dependencies.sh
gb vendor fetch google.golang.org/appengine
gb vendor fetch golang.org/x/net/context
```

```
> ./dependencies.sh
gb vendor fetch google.golang.org/appengine
fetching recursive dependency golang.org/x/net/context
gb vendor fetch golang.org/x/net/context
```

actually, it fails.

```
> ./dependencies.sh
gb vendor fetch google.golang.org/appengine
fetching recursive dependency golang.org/x/net/context
gb vendor fetch golang.org/x/net/context
FATAL command "fetch" failed: golang.org/x/net/context is already vendored
FATAL command "vendor" failed: exit status 1
```

**Comment by davecheney** [comment]
>  Simply, I want gb vendor fetch -u just like go get -u. :smiley:

I'm sorry but I have no plans to implement that feature. gb is a reaction to all the problems of go get, adding -u, it unconditionally fetching HEAD of every depdendency would undo the work that gb has put into repeatable builds.

**Comment by davecheney** [comment]
Closing as described above. Please feel free to reopen if you disagree
