### ISSUE TITLE
Error on freebsd with $PWD != $(realpath $PWD) 

### ISSUE THREAD

**Issue by cactus** [constabulary/gb#422]
On FreeBSD `/home` is often a symlink to `/usr/home`. This seems to not agree with gb for some reason, and I have to specify the -R path directly.

~~~
$ pwd
/home/user/projects/rollcage

$ realpath $(pwd)
/usr/home/user/projects/rollcage

$ gb build -v
DEBUG project root "/usr/home/user/projects/rollcage"
DEBUG matchPackages: /usr/home/user/projects/rollcage/src ../../../../../../home/user/projects/rollcage/...
DEBUG args: []
DEBUG removing work directory: /tmp/gb148345295
FATAL command "build" failed: no packages supplied

$ gb build -R $(realpath $(pwd)) -v
DEBUG project root "/usr/home/user/projects/rollcage"
DEBUG matchPackages: /usr/home/user/projects/rollcage/src ...
DEBUG args: [rollcage rollcage/commands]
DEBUG build duration: 15.232µs map[]
DEBUG removing work directory: /tmp/gb435798870
~~~

Using gb fetched via go get today (Oct  6).

**Comment by davecheney** [comment]
Thanks for the report. I'll look into it soon.

**Comment by cactus** [comment]
@davecheney I think I found the root cause.
In cmd/main.go

```
	cwd, err := filepath.Abs(cwd) // if cwd was passed in via -R, make sure it is absolute
```

It appears that filepath.Abs does not resolve symlinks on its own.
The following gets it to work -- but I admit to not knowing how portable it would end up being.

~~~
diff --git a/cmd/gb/main.go b/cmd/gb/main.go
index 4a5a311..469311f 100644
--- a/cmd/gb/main.go
+++ b/cmd/gb/main.go
@@ -110,6 +110,10 @@ func main() {
 	if err != nil {
 		log.Fatalf("could not make project root absolute: %v", err)
 	}
+	cwd, err = filepath.EvalSymlinks(cwd)
+	if err != nil {
+		log.Fatalf("could not make project root absolute: %v", err)
+	}
 
 	ctx, err := cmd.NewContext(
 		cwd, // project root
~~~

**Comment by davecheney** [comment]
Thanks. I agree with your diagnosis. That check was added a while back. The
details escape me, but I believe it was also symlinks related, before
changing that path, I'd like to review the reason that line was added.

**Comment by cactus** [comment]
I updated the diff to show a bit more context, and to make it clear that resolving symlinks would be additive, not intended to replace the existing absolutification (that isn't a real word is it?!) of the path.

**Comment by cactus** [comment]
Forgot to mention that I am in no hurry, as I do have a valid workaround (via `-R`). 
Thanks!

**Comment by cactus** [comment]
@davecheney any further thoughts on this?

**Comment by cactus** [comment]
Awesome. Thanks @davecheney.
Just tested on my FreeBSD box and it indeed appears to be fixed!

**Comment by davecheney** [comment]
Thanks for confirming.
