### ISSUE TITLE
gb test should only print test output if tests fail

### ISSUE THREAD

**Issue by mbrevoort** [constabulary/gb#435]
It would be great if gb's behavior was the same as `go test` with the way it deals with printing output. `go test` only prints the output (stdout and stderr) if a test fails:
https://golang.org/src/testing/testing.go?s=12723:12764#L511

I would love it if a test would PASS silently and FAIL verbosely. For example, this passing package test adds a lot of noised to the output, especially when just one of many packages fail to build:

```
$ gb test app/controllers
app/controllers
time="2015-10-30T17:12:22-06:00" level=info msg="Reading Prototype from /Users/mike/dev/rnp/beepboop/app/prototypes/bender.yaml"
time="2015-10-30T17:12:22-06:00" level=info msg="Loaded Prototype bender"
time="2015-10-30T17:12:22-06:00" level=info msg="Reading Prototype from /Users/mike/dev/rnp/beepboop/app/prototypes/george.yaml"
time="2015-10-30T17:12:22-06:00" level=info msg="Loaded Prototype george"
time="2015-10-30T17:12:22-06:00" level=info msg="Reading Prototype from /Users/mike/dev/rnp/beepboop/app/prototypes/poker"
time="2015-10-30T17:12:22-06:00" level=info msg="Loaded Prototype poker"
time="2015-10-30T17:12:22-06:00" level=info msg="New Team Created: ZImcCRS2N4\n"
time="2015-10-30T17:12:22-06:00" level=info msg="New User: jV4t8GVYRf\n"
time="2015-10-30T17:12:22-06:00" level=error msg="uh oh"
time="2015-10-30T17:12:22-06:00" level=info msg="CGpwsvufnH of team tWNd7wnW7E attempted unauthorized request for team NeRrc6CiTD"
time="2015-10-30T17:12:22-06:00" level=error msg="Unauthorized to view a different team"
time="2015-10-30T17:12:22-06:00" level=info msg="2015/10/30 17:12:22 http: multiple response.WriteHeader calls"
time="2015-10-30T17:12:22-06:00" level=error msg="Team 0UzNLjxrtQ not found"
time="2015-10-30T17:12:22-06:00" level=info msg="MaGln0O0qJ of team 3m2MgPOfMo attempted unauthorized request for user Gw838rQErW of team Oh7Z6XwTB3"
time="2015-10-30T17:12:22-06:00" level=error msg="Unauthorized to view a user of a different team"
time="2015-10-30T17:12:22-06:00" level=info msg="2015/10/30 17:12:22 http: multiple response.WriteHeader calls"
time="2015-10-30T17:12:22-06:00" level=error msg="User 4knNUQr0jo not found"
PASS
```

**Comment by davecheney** [comment]
I agree, and i'm working on this for the 0.3 release (soon, i hope).

The plan is exactly as you describe, if the test process passes, exits 0, then nothing will be printed. If it fails, you get stdout and stderr.

**Comment by mbrevoort** [comment]
Sounds great, thanks @davecheney!

**Comment by davecheney** [comment]
Done. See also #438

**Comment by mbrevoort** [comment]
Amazing! So much better!

**Comment by mbrevoort** [comment]
LOL from a coworker:
> as silly as it sounds, it probably means I’ll be more inclined to write more tests

Thanks again Dave

**Comment by davecheney** [comment]
There's a moral in this story, somewhere, I'm sure.

**Comment by dennisjbell** [comment]
I agree with no test output in case of pass, but now there's no output at all on pass, so I don't know if there are even any tests written.  A simple summary of "All N tests passed" would be really helpful to indicate that there were tests and they were all run and passed.

**Comment by davecheney** [comment]
> A simple summary of "All N tests passed" would be really helpful to indicate that there were tests and they were all run and passed.

Unfortunately this information is not available, the test binary only gives a pass or a fail via exit code.

However, we do know the number of test cases written as part of building the test runner binary, perhaps I can log that information
