### ISSUE TITLE
output failing package before compile errors

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#440]
Moving the output of the package name til the completion of the compilation, #437 now causes gb to _not_ print the name of the package if there was a compilation failure
```
lucky(~/src/github.com/constabulary/gb) % gb build
gb.go:71: undefined: "github.com/constabulary/gb/log".Fatalf
FATAL command "build" failed: exit status 2
```
It's not clear which package gb.go belongs to. This is because the compile failure happens in an action below the final action in gb.Compile, so the action is skipped, skipping the logging.

This may be ameliorated if #406 is addressed, but it might need a direct fix.

**Comment by sevein** [comment]
Aye! Same issue here, glad you noticed it.

```
$ gb build
main.go:26: foo declared and not used
main.go:20: bar declared and not used
FATAL command "build" failed: exit status 2
```

**Comment by davecheney** [comment]
I'm working on a fix right now. I'll do a 0.3.1 bugfix release soon
