### ISSUE TITLE
Feature: create `gb version` flag

### ISSUE THREAD

**Issue by qanx** [constabulary/gb#447]
Discovered that when tests pass I see the test output but my coworker, who installed gb about a week or two later, does not. e.g. I see:

```
supervisor
Running Suite: Supervisor Test Suite
====================================
Random Seed: 1447175614
Will run 14 of 14 specs

••••••••••••••
Ran 14 of 14 Specs in 4.350 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```

And he only sees the following for passing tests:

```
supervisor
```

It took a bit to discover that there had been changes made between his install and mine. It would have been much easier and more up front if we had had a `gb version` or similar command to run :)

**Comment by davecheney** [comment]
I'm sorry this caused you issues. I agree this would be very useful, but there are a number of problems to be solved (that I don't have immediate solutions for) as gb is built with the standard go tool.

This is already tracked as #212. Closing as duplicate.
