### ISSUE TITLE
Using gb with godoc.org?

### ISSUE THREAD

**Issue by fd0** [constabulary/gb#457]
I'd really like to use `gb` as a build tool for the [restic backup program](https://github.com/restic/restic). I wasn't able to figure this out myself: Is there a way to use `gb` and have all the code below `src` and still be able to use godoc.org for browsing the code documentation?

**Comment by tianon** [comment]
I don't see any reason for it not to work; https://godoc.org/github.com/constabulary/example-gsftp/src/cmd/gsftp is a link to docs for the example project :smile:

**Comment by fd0** [comment]
Hm, that looks okay indeed. When I last tried it, I remember that it didn't work so well.

I made a (silly) sample repository here: https://github.com/fd0/argon-gb, on godoc.org at least the import paths for packages are wrong (they have an additional path component `src`): https://godoc.org/github.com/fd0/argon-gb/src/foo
