### ISSUE TITLE
main package at $PROJECT/src is ignored

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#46]
Consider this layout
```
$PROJECT
    src/
        main.go
```
`main.go` will be ignored. Similar to #45, this is a bug, but probably not helpful to the user as the command would be installed as `$PROJECT/bin/src`

**Comment by davecheney** [comment]
As part of discussing #48 it was decided that source code at the root of `$PROJECT/src` was a mistake and the small convenience would only confuse when someone went to consume that package. 

To close this issue, gb should be taught to reject source at the top level of `$PROJECT/src/`

cc @wkennedy

**Comment by ajpen** [comment]
So, what this is saying is any code in $PROJECT/src will be ignored? I have main.go there as I would in a typical go project and its not compiled. My other packages are compiled. Do I need main in a different directory?

**Comment by davecheney** [comment]
Any package at $PROJECT/src is ignored because it would have an invalid package import path.

**Comment by davecheney** [comment]
https://getgb.io/faq/#cannot-build-src-root
