### ISSUE TITLE
Installation directives

### ISSUE THREAD

**Issue by fcantournet** [constabulary/gb#470]
Right now the suggested way to install gb (from getgb.io) is :

`go get github.com/constabulary/gb/...`

I get that it's just super convenient, and that master is supposed to always be in working condition, but given that we are big on having releases and sticking to semver, shouldn't we suggest a way to install from a tagged realease instead ?

I mean I don't really want to use `go get` and have the master put in my Docker image that builds the world.

This is a genuine question, I could as easily have a fork that I don't sync except on releases or whatever.

**Comment by davecheney** [comment]
@fcantournet  Thanks for your question. I'll try to answer what I can

> I get that it's just super convenient, and that master is supposed to always be in working condition, but given that we are big on having releases and sticking to semver, shouldn't we suggest a way to install from a tagged realease instead ?

At the moment gb needs go get to be installed. There are a few reasons behind that, a good overview of those is this comment, https://github.com/constabulary/gb/issues/212#issuecomment-156246533. 

In short, I do plan to make gb self hosting, but not until we're closer to the 1.0 release. At the moment, the convenience and ubiquity of `go get -u` is too seductive.

> I mean I don't really want to use go get and have the master put in my Docker image that builds the world.

So don't use go get, use git directly to pull the release tag. 

> This is a genuine question, I could as easily have a fork that I don't sync except on releases or whatever.

I'm not sure what you're asking here, could you please clarify.

**Comment by fcantournet** [comment]
I just meant that it wasn't a blocking issue for me. Just trying to get the conversation started 

You answered it in full. Thanks

**Comment by davecheney** [comment]
Ok, good to know. Thanks for asking.
