### ISSUE TITLE
gb test: Failed to resolve import path "-v"

### ISSUE THREAD

**Issue by nsf** [constabulary/gb#473]
I don't know if this is expected. But it is confusing. I know there is some logic to recognize known testing flags and work with them in a particular way, but I find this confusing.

Define a "projectx" package with TestX and TestY functions in `main_test.go` file.

`gb test -v projectx -run TestX` - runs TestX, all fine
`gb test -v -run TestX projectx` - runs TestX, all fine

It makes you think that position of flags relative to package name is not important. So you try this:

`gb test -v projectx` - runs all tests, all fine
`gb test projectx -v` - fails with:

FATAL: command "test" failed: failed to resolve import path "-v": cannot find package "-v" in any of

I tried to look at the code and figure out what makes "-v" so special. Nothing, other than it's defined on the top level command here: https://github.com/constabulary/gb/blob/master/cmd/gb/test.go#L33

And it is indeed related, because `-cover` fails the same way. Even though both of them are defined here: https://github.com/constabulary/gb/blob/master/cmd/gb/testflag.go#L23-L38

Also if we take different boolean flags which are defined in that list, but are not present in top level package definition, they work just fine. For example `-benchmem` flag can be specified anywhere related to package name.

**Comment by davecheney** [comment]
Thanks for raising this issue. I think what is happening here is gb's flag
parsing is stopping at projectx, and the reminder of the flags are being
forwarded to the test binary which reject them as -v is not defined there.

At a guess I think this is expected, but I'll confirm and see what the go
tool does.
