### ISSUE TITLE
gb env should return value associated with a variable 

### ISSUE THREAD

**Issue by gosuri** [constabulary/gb#476]
A cool enhancement that'll make `gb env` more script friendly would be to return the assigned value for a var, similar to `go env VAR`.  Example:
```sh
$ gb env GB_PROJECT_DIR
/Users/gosuri/code/walker
```

 I can send a patch, if you'd like.

**Comment by davecheney** [comment]
:+1: from me. You'll probably have to do some serious surgery to replace the simplistic way `gb info` works now. 

Alternatively you may want to add a `gb env`, or make `gb env` an alias for `gb info`. 
 
Either way, please make sure you add end to end tests to cmd/gb/gb_test.go.

Thanks

Dave

**Comment by gosuri** [comment]
Awesome! Will get rolling.

**Comment by gosuri** [comment]
I see what you meant by "serious surgery", the args are pkg paths :)

**Comment by davecheney** [comment]
I believe there is an option to override arg parsing per command. Have a
look at the cmd.Cmd structure and check out how test monkeys with argument
parsing.

**Comment by gosuri** [comment]
Thanks.. Figured it out

**Comment by davecheney** [comment]
Sorry its such a hand rolled mess.

Part of the challenge with gb is I've made such a song and dance about how
package management should be done, I've sort of painted myself into a
corner and made myself unable to use third party packages.

I should probably find a ladder and get down off my high horse.

**Comment by gosuri** [comment]
I sort of jumped straight to the command's code under the assumption that args weren't manipulated. It wasn't hard tracing back. The code and tests were clear and easy to understand.

More over, I learned much more about the tool with this exercise. Will come handy since I'll be using gb everyday.

**Comment by davecheney** [comment]
closed by #477
