### ISSUE TITLE
Proposal: vendor restore --missing, --retry, and --continue options

### ISSUE THREAD

**Issue by steevee** [constabulary/gb#498]
A flaky internet connection has left me wanting three additional (related) options for the `gb` plugin `vendor-restore`:

- `--missing`: only fetch vendor packages not present. By default everything is fetched, which makes sense given the `vendor/src` directories are but copies of the cloned working-copy, so they won't have revision information inside them, which makes an `npm update` equivalent statement impossible. However this option could work if:
  - the vendor's package src exists, assume it's the correct one (a bit crap, and possibly dangerous if always relied upon, but a stepping stone)
  - or the working copy's revision was somehow stored (a `.gb/HEAD` file anyone? :sob: or better leverage #316) it could check if the revision matches the `manifest` before restoring (although this would probably be better as the default behaviour, without options)
- `--retry n`: should the first attempt fail (connection timeout, DNS resolution, etc), retry `n` times.
- `--continue`: should fetching a vendor's package fail, carry on with the next.

Currently post pulling in a new revision/branch I run `gb vendor restore` and when my ISP is wigging out, I haven't been able to complete a full restore of more than half a dozen (or the 41) packages.

I know there has been plenty said about `gb vendor restore` (#175, #271) but the inclusion of #281 suggests if you're ideologically inclined then have a go with it. 

Sure, I could use git subtree/submodule, and I'm not against this, but this is a manual task I will have to grapple separately, which doesn't leverage things like the `vendor/manifest` and `gb vendor purge`.

_Caveat: I'm no veteran to `gb`, I've been using it on a converted project of mine for about a week, so maybe I'm missing a trick!_

**Comment by davecheney** [comment]
Thanks for raising this issue. I don't plan on adding these flags. If your
upstream is unstable then you should be vendoring those packages and
checking them into source control.

**Comment by steevee** [comment]
@davecheney does _not planning_ also mean _not opposed_? (Am I reading what I want to read?)
If so, happy to take a look.

Completely understand this is a roundabout solution to essentially upstream not being stable, and there are existing, precise solutions for that. Having said that, `gb vendor restore` exists, and these might be some nice tools for that toolbox.

**Comment by davecheney** [comment]
I'd prefer not to add those features. Vendor restore was a mistake, I should have pushed back harder at the time.

If you don't want to vendor your code, that's fine, I also think vendoring is a crude solution, and am working on something much better, have a look at issue 12302, my comments towards the end of the issue. That's what I propose instead.

**Comment by steevee** [comment]
OK no worries. Glad to get a resolution on `gb vendor restore` at least!
Issue 12302?

**Comment by ngrilly** [comment]
@steevee I guess @davecheney refers to this: https://github.com/golang/go/issues/12302

**Comment by steevee** [comment]
@ngrilly cheers I found it but lost myself in the unfolding novel :smile: 
For completeness I also found #350 which is very similar to this.

Appreciate vendor restore was a mistep, and presume @davecheney was referring to [this comment](https://github.com/golang/go/issues/12302#issuecomment-152072534), but perhaps he can clarify?

In the meantime, I'm going to vendor with git submodules/subtree. A method to leverage the `manfiest` (for my 41 external packages) would make a hell of a Christmas gift!

**Comment by davecheney** [comment]
Yup, that's the comment. 

Steve, why not use go vendor fetch ? You don't have to use th vendor at all, but if you do, this is the way the plugin was designed to work.

**Comment by steevee** [comment]
@davecheney sorry if I'm missing your point, but I understand `vendor fetch` (the `go get` equivalent) fetches one src at a time, so I was using `vendor restore` to process the `manifest` in bulk.

My `/vendor/manifest` is committed and has dozens of dependencies, so I'm looking for ways to make management easier.

Vendoring in dependencies via git submodule/subtree is OK, or simply using `manifest` like I use `package.json` appeals even more to me. However, I'd like to see more tools in the `gb vendor` plugin shed to help either git submobule/tree creation, or `manfest` restoration.
