### ISSUE TITLE
gb build "" does not build anything

### ISSUE THREAD

**Issue by mariokostelac** [constabulary/gb#5]
If main package is placed in src folder, `gb build` does not recognise the package and builds nothing.
Should it be considered as a bug?

**Comment by davecheney** [comment]
I'm working on this now as part of getting more complicate patterns to work, when I'm done we should have the same logic as the `go` tool.

**Comment by davecheney** [comment]
There is one missing case, running `gb build` in the root of a project does not work.

**Comment by davecheney** [comment]
I believe this is now fixed.

**Comment by mariokostelac** [comment]
Sorry for not being clear before. Should it be valid to have main package in src directory?
`src/main.go` for example.

**Comment by davecheney** [comment]
I think that is a valid, if surprising use case. Please look at #46 and close this issue if you think it is a duplicate ( #46 probably has more detail)
