### ISSUE TITLE
New subcommand, gb list

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#52]
`go list` is a very useful command and `gb` could benefit from a similar tool to introspect a project.

`gb list` should probably be integrated into `gb`, but I would like to see it initially developed as a plugin to road test the plugin API (such that it is).

`gb list` should work the same as `go list`; you supply a `text/template` which is executed in an environment that has access to `*gb.Project`, `*gp.Context` and maybe a `[]*gb.Package` from the resolved package set.

This template can be supplied on the command line, similar to `go list -f`, but I'd also like to see it passed into the command via stdin, eg `echo "{{ .Context }}" | go list`

**Comment by fatih** [comment]
This would be also helpful for editors. I'm using extensively `go list` to create the list of dependencies any many other things that I'm passing to `go build` or `go install`. So having it would make the integration for editors more easily.

**Comment by freeformz** [comment]
+1 also for things like heroku-buildpack-go

**Comment by mariokostelac** [comment]
@freeformz don't worry, already planning to do that :)

**Comment by davecheney** [comment]
@mariokostelac #76 contains an initial cut of `gb-list`, feel free to take it and run with it.

**Comment by paxan** [comment]
Anybody wants to try the buildpack... See #85
