### ISSUE TITLE
Clarify project root detection rules

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#53]
In #50 @chrishines pointed out some ambiguity in the project detection rules. 

Clarify them, and add tests. Also.come up with a good story for what happens when accidentally building inside vendor/

**Comment by ChrisHines** [comment]
My suggestion:

>#### Project root auto detection

>A `gb` project is defined as any directory that contains a `src` subdirectory. `gb` automatically detects the root of the project by looking at the current working directory and walking backwards until it finds a directory not named `vendor` that contains a `src` subdirectory.

**Comment by davecheney** [comment]
@ChrisHines sounds good to me. I'm pretty sure this is what the current logic does anyway.

On a related not, I'm kicking myself that the tests in this area are non existant. I have some excuses about mocking filesystems, but they don't cut it. As part of resolving this bug I will add robust tests.

**Comment by ChrisHines** [comment]
Was there a reason you chose not to address the vendor folder in the new wording?

**Comment by davecheney** [comment]
I haven't implemented that logic yet. Please reopen the issue.
