### ISSUE TITLE
gb fails to import standard packages

### ISSUE THREAD

**Issue by dradtke** [constabulary/gb#530]
Given a simple "hello world" project that looks like this:

```
.
└── src
    └── main
        └── main.go
```

where `main.go` looks like this:

```go
package main

import "fmt"

func main() {
	fmt.Println("hello gb")
}
```

Running `gb build main` fails with: **FATAL: command "build" failed: failed to resolve import path "main": import "fmt": not a directory**.

This is with a copy of `gb` that was installed via `go get` just 5-10 minutes ago.

**Comment by dradtke** [comment]
Just confirmed that this example works with version 0.3.5, so it must be something that was introduced since then.

**Comment by davecheney** [comment]
@dradtke sorry for the issue. I haven't been able to replicate this locally. Could you please run 

`env DEBUG=. gb build main`

And paste the full output for me.

**Comment by dradtke** [comment]
That's odd, it's working for me now. However, I have seen a similar issue before with fetching dependencies, and was able to reproduce it. The odd thing about this issue is that it still seems to work in that it downloads the requested dependency, but it outputs a similar error. Here's the output of that one with debugging enabled:

```
2016/01/15 10:28:53 main.go:116: args: [fetch github.com/lib/pq]
2016/01/15 10:28:53 cmd.go:86: project root "/home/damien/workspace/gb"
2016/01/15 10:28:53 main.go:166: args: [fetch github.com/lib/pq]
2016/01/15 10:28:53 main.go:62: project root "/home/damien/workspace/gb"
2016/01/15 10:28:53 main.go:81: args: [github.com/lib/pq]
fetching recursive dependency bufio
FATAL: command "fetch" failed: "bufio" is not a valid import path
FATAL: command "vendor" failed: exit status 1
2016/01/15 10:28:53 context.go:325: removing work directory: /tmp/gb421556522
```

This looks like a different issue, and it's by no means a blocker, so feel free to close this issue. I'll re-open it if I can reproduce it again.

**Comment by AndyEverLie** [comment]
somehow i got the same issue, fixed by reinstall gb. still didn't know why, but it works =_=
