### ISSUE TITLE
make vendor location and checkout configurable (to support separate git repositories, etc.)

### ISSUE THREAD

**Issue by dmitris** [constabulary/gb#55]
Following up on https://twitter.com/dimisec/status/595895255834206208 exchange:

dimisec:  how can we cover the use case when the vendored code is in different repo, ex. http://3dparty.mycorp.com? Must have a config then?

davecheney: all that gb cares about is the source is in the correct path in vendor/src/
davecheney:  I can't answer this in a tweet, could you log an issue and I'll do my best to explain there, with pictures.

Here's the use case I am thinking about.  Suppose that your company is using GHE (GitHub Enterprise) and all the third-party / mirrored opensource code lives in a dedicated GHE instance "opensource.git.corp.company.com" separate from the "git.corp.company.com" which is used for all the internal code.  Therefore you don't have one single source code tree where you could put vendor/src close to the root.  What people want is to use the "natural" package names in the imports such as github.com/robertkrimen/otto, avoid the nuisance of continuous import path rewriting and rely on a building tool that would be able to "magically" map "github.com/abc/xyz" to "git@opensource.git.corp.company.com:abc/xyz.git " so that you could use your central internal mirror (which is reliable and persistent in case the upstream repository disappears).

I wonder if it would be possible to "templatize" the vendor/src location so that the default would be like it is now (for everyone who is happy with gb's status quo) but you would also be able to specify with some optional configuration (for example, ~/.gbconfig file) that instead of vendor/src, the dependencies code should be checked out from git@opensource.git.corp.company.com:[org]/[repo] (and maybe added to _vendor/src subdirectory of the currently compiled project for building).

Another part of the equation is reproducible builds and freezing the versions of the dependencies - being able to nail them down without having to duplicate the code of N dependencies for M projects N*M times which seems somewhat space-wasteful and, probably much worse, means that all those N*M mini-mirrors need to be created and updated/managed (yikes! - a very real pain point).  If a [light-weight] configuration file would be required for that, I think it's a fair price to pay (especially if we can have tooling to help creating and updating such configuration).

One more wish that I see commonly expressed: to be able to fetch the dependencies with a certain tag.  I sorely miss the ability to "go get -tag [sometag]" which would grab the code with the given tag if and where it's available (like Go does with the magical but rather useless "go1" tag) - so that I would not need to do scripting voodoo of: "go get -d [pkg] && cd $GOPATH/pkg && git checkout [sometag] && go get -d ./..." (and then somehow do it recursively for all the deps).  I even tried to request such an extension but of course it was quickly rejected :smile:

**Comment by davecheney** [comment]
@dmitris gb will not have a configuration file. This is a design decision. We have to work around this decision.

Having said that, I think I have not explained how I expect a gb project to be structured. The most important part is there is no `gb get` or any other fetching as part of the tool, the project owner is responsible for populating the `src/` and `vendor/src/` directories with their code, and the dependencies of their code. In short, the project owner copies the source of the packages in to `vendor/src/`.

gb itself is DVCS agnostic, all it cares about is the project is layed out on disk correctly. How the files get from your disk to your colleagues' is outside its area of concern. _If_ your organisation is comfortable using techniques like svn externals of git subtrees then those can be used to glue together other repos into the project's `vendor/src/` directory. I say _if_, gb doesn't require it, you can always just copy the source into the vendor directory and check the whole lot in, which would probably be the most reliable way of getting reproducible builds.

I hope this has answered your question. If not, please highlight the areas of your original question which remain unanswered.

**Comment by dmitris** [comment]
Your point and intended scope of the gb tool is clear, thanks for the explanation.  

I think "go get" initial convenience makes you "spoiled" and makes you wish for an integrated tool that would handle fetching the (properly versioned) code from the DVCS as well as building it but in a more flexible and customisable way than "go get".  But I understand that it may not be what you intend the gb tool to be used for or what most other gophers need or want.

**Comment by davecheney** [comment]
> I think "go get" initial convenience makes you "spoiled" and makes you wish for an integrated tool that would handle fetching the (properly versioned) code from the DVCS as well as building it but in a more flexible and customisable way than "go get".

You can use `git clone` for this, right ?

Wrapping `git clone` in another tool to the extent that you can use all the options, ssh/https, private github enterprise, etc, would just end up replicating `git` for no benefit.
