### ISSUE TITLE
importing bad paths fails with incorrect error

### ISSUE THREAD

**Issue by austinkelmore** [constabulary/gb#550]
If a go file that's being compiled has a bad import path, gb will claim:
> FATAL: command "build" failed: no packages supplied

Even though there _are_ valid files. This is true even if there are many files that are correct, with only one file containing an invalid import.

This is reproduced with a simple test file:
````
package main

import (
	"log"
	"this/is/a/bad/path"
)

func main() {
	log.Println("Hello World.")
}
````

The reason this is happening is for several reasons. In context.go, matchPackages has a call to filepath.Walk that isn't handling the error that's returned. The error that's being returned (but not handled) is correctly calling out
> import "this/is/a/bad/path": not a directory

but that isn't being passed higher up the stack. It's alsonot specifying which file (or line) is causing the bad import, which makes it a bit harder for the user to track down the offending line of code.

I tried to figure out a good way to pass along the information to main so it call fatalf out, but nothing came to mind in the bit that I looked at it since there's no error structure set up in place for that section of code. I'd be happy to try to fix it if you're willing to give a bit of guidance, or if you want to fix this yourself I'm totally happy with that as well.

**Comment by davecheney** [comment]
Thanks for reporting this bug, which revision of gb are you using ?

**Comment by davecheney** [comment]
I'm working in this area right now.

**Comment by austinkelmore** [comment]
I grabbed head as of this morning. https://github.com/constabulary/gb/commit/5217deb25e4ba2962b4212c1f701ebe61383a5f2 to be exact.

**Comment by davecheney** [comment]
Thanks for logging this bug, I think i've cleaned up the worst of the mess.
