### ISSUE TITLE
Question: is it possible to have more than 1 project with $GOPATH?

### ISSUE THREAD

**Issue by jamm** [constabulary/gb#56]
Sorry if it's dumb question, but based on this line from readme:

> A project is conceptually a $GOPATH workspace dedicated to your project's code.

**Comment by davecheney** [comment]
Could you give a bit more background to your question ? gb doesn't use $GOPATH, and that information above is really an aide to help people understand what a gb project is, using information they already know.

**Comment by jamm** [comment]
For example, we have 2 websites - it's 2 different projects (in terminology I used to) with 2 different sets of dependencies. We can have only one $GOPATH in the system, so question is: is it possible to keep sets of dependencies for those 2 projects independent.

**Comment by davecheney** [comment]
gb does not use GOPATH. You would put your gb projects elsewhere, outside GOPATH.

**Comment by jamm** [comment]
well... ok :) it's a good news but then I think you have some controversial points in readme:

> gb operates on the concept of a project. A project has the following properties:
> A project is conceptually a $GOPATH workspace dedicated to your project's code.

**Comment by davecheney** [comment]
Thanks. I think that I didn't understand your original question. Can you
help me understand the points that confused you so I can improve them.
