### ISSUE TITLE
Gets locked into whatever version of Go it is compiled with?

### ISSUE THREAD

**Issue by calmh** [constabulary/gb#560]
I'm not sure if I'm getting this right, but it seems that a gb built with Go 1.4 then can't build stuff after upgrading Go to 1.5 or 1.6. That is:

```
jb@syno:~/s/g/s/syncthing $ gb build
# github.com/calmh/du
diskusage_posix.go:6: import /usr/local/go/pkg/darwin_amd64/path/filepath.a: object is [darwin amd64 go1.5.2 X:none] expected [darwin amd64 go1.4.2 X:precisestack]
...
FATAL: command "build" failed: exit status 1
[1]
jb@syno:~/s/g/s/syncthing $ 
```

I'm not sure why else it would be expecting go1.4.2 archives; I have cleared out pkg and $GOPATH/pkg (that should not be in use anyway). Rebuilding gb solves the problem.

Is this intentional? I have many Go installations that I switch between regularly by pointing /usr/local/go towards for example /usr/local/go1.4.2 or /usr/local/go1.6rc1. Also build servers that guard against regressions by building a project for each supported architecture for each supported Go version (1.3.3, 1.4.3, 1.5.3, go1.6rc1, and so on). Not being able to do this with gb would be annoying. :)

**Comment by davecheney** [comment]
Gb must be built against the version of Go you wish to use. You cannot use
GOROOT tricks to avoid this, but you can use different versions of go to
build different versions of gb.

You should also delete $PROJECT/pkg of you switch between different gb's,
and just different go versions.

**Comment by calmh** [comment]
I take it that's intentional, then. :/

**Comment by davecheney** [comment]
Unfortunately there is no way around it. The go tool also has the same
limitation, but it isn't as obvious as people consider the go tool,and the
tool chain it ships with to be the same thing.

**Comment by calmh** [comment]
/me briefly considers vendoring gb and building *that* as step zero of building the project. But no, seems we stay with the default build tools for another iteration. :)
