### ISSUE TITLE
gb build missing dependencies's vendor dir

### ISSUE THREAD

**Issue by hyper-carrot** [constabulary/gb#561]
I work on a project named ProjectA with gb. It dependent on example.com/ProjectB. ProjectB also has some dependencies (exp.: example.com/ProjectC and example.com/ProjectD) stored in `<ProjectB dir>/vendor`. I fetch ProjectB:

```
gb vendor fetch -no-recurse example.com/ProjectB
```

then, the tree is:

```
ProjectA
|- src
|- vendor
   |- src
      |- example.com
         |- ProjectB
            |- vendor
               |- example.com
                  |- ProjectC
                  |- ProjectD
```

I build ProjectA use `gb build`, and get:

```
FATAL: command "build" failed: failed to resolve import path "abc": import "example.com/ProjectC": not found
```

So, I guess `gb build` missing dependencies's vendor dir. btw: `GO15VENDOREXPERIMENT=1` in my environment.

**Comment by davecheney** [comment]
It looks like project B is using the go tools vendor support.

You have a few choices,

1. Don't use the -no-recurse flag, and let gb vendor fetch projectB's dependencies from upstream
2. Use gb vendor fetch to fetch each of projectBs dependencies explicitly. 
3. Move the contents of projectBs vendor directory to $PROJECT/vendor/src

**Comment by hyper-carrot** [comment]
@davecheney Could you make `gb build` recognize `ProjectB/vendor` ?

**Comment by davecheney** [comment]
No, I have no plans to implement that feature.
https://getgb.io/faq/#govendorexperiment

**Comment by hyper-carrot** [comment]
@davecheney OK, but it's really make a obstacle.

**Comment by cactus** [comment]
Just want to add a comment that not only does this make things a bit more difficult, but in a few cases I have seen:
* not vendoring the latest upstream version (eg. pinned to older version) of a dependency
* modifications to a vendored library not present in the upstream versions. 

In both cases, the end result is subtle brokenness/bugginess. 

At the very least the below recommendation to fetch a fresh copy of a library, made on the linked page, may end up proving problematic for people.

> To resolve these ignored dependencies, you can either copy them from each dependency’s vendor/ folder..., or vendor a fresh copy with gb vendor fetch.The latter is the recommended process so the dependencies’ location is recorded in the gb vendor manifest file.

**Comment by davecheney** [comment]
SGTM. Patches welcome, https://github.com/constabulary/getgb.io
