### ISSUE TITLE
File names in error messages should show absolute or relative path

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#57]
Currently it's only showing the filename. An example error message:

```bash
color ❯ gb build -q
2015/05/09 00:43:44 command "build" failed: [/usr/local/go/pkg/tool/darwin_amd64/6g 
-p github.com/fatih/color 
-pack -o /var/folders/mc/hxkh39y93dn__458mq8xrbcm0000gn/T/gb360767389/github.com/fatih/color.a 
-I /var/folders/mc/hxkh39y93dn__458mq8xrbcm0000gn/T/gb360767389 
-I /Users/fatih/Code/color/pkg/darwin/amd64 -complete color.go doc.go]: exit status 1
color.go:78: c evaluated but not used
```

Would be better if it's changes too (relative path):

```bash
src/github.com/fatih/color.go:78: c evaluated but not used
```

Or even an absolute path. As I know the go tool outputs the file names as relative paths. This is important so an editor can capture and jump to it (example: vim's quickfix window).

Of course a much better approach would be having a editor compatible output (such as we have on in Oracle). It would make parsing easier and we could pipe the result directly to the editor's error parsing function.

**Comment by davecheney** [comment]
@fatih I agree and I'll do this. At the moment the error message are without a path because the build is compiled with the working directory set to the src directory of the package. 

As a simplistic fix, always executing the build from a single location will give more inspectable error message. 

I'd like to avoid making the paths absolute initially, I'd rather everything was relative to `$PROJECT` or `$PROJECT/src/`. @fatih, do you have any preferences ?

**Comment by Supermighty** [comment]
I feel that file paths in messages should be relative to `$PROJECT`.

`gb` is all about thinking in terms of projects. This should be reflected in how it communicates with users.

**Comment by davecheney** [comment]
There is a small inconsistency that you ask for a package to be built by
its import path, but the error message will have src/ stuck on the front. I
think this I'd manageable, and preferable to making the paths relative to
$PROJECT/src/ as it makes it more complicated if the error is in a vendored
package.

**Comment by Supermighty** [comment]
What are other things that would be affected by this decision? Tooling? Copy/Paste from terminal? How does the choice of path make life easier or harder to be a drop-in replacement for the go tool?

**Comment by davecheney** [comment]
If it makes it easier for @fatih to integrate gb I to go-vim, I can only
see this as a positive for other tools that want to integrate.

**Comment by fatih** [comment]
> @fatih I agree and I'll do this. At the moment the error message are without a path because the build is compiled with the working directory set to the src directory of the package.

Thanks a lot @davecheney, this will make it easier to integrate `gb` with editors.

> As a simplistic fix, always executing the build from a single location will give more inspectable error message.

Right. I was executing `gb build` in the root folder. To test how the path is printed I've introduced an error in a new subfolder: `github.com/fatih/color/subcolor`. The error was in the form:

`subcolor.go:78: c evaluated but not used`

However there is no context here, does the file belong to `github.com/fatih/color` or `github.com/fatih/color/subcolor`? (Correct answer is the latter one). So here `gb build` evaluated in the root folder. But of course in the editor, the build will be always from within the source code's location (`github.com/fatih/color`)

> I'd like to avoid making the paths absolute initially, I'd rather everything was relative to $PROJECT or $PROJECT/src/. @fatih, do you have any preferences ?

Relative is imho a good choice to go (because it's the same with the go tools). Because it's relative, it doesn't matter exactly from where it's called right? For example this is how `go build` is acting:

```sh
fatih git:master ❯ pwd
/Users/fatih/Code/koding/go/src/github.com/fatih
fatih git:master ❯ go build ./color
# github.com/fatih/color
color/color.go:79: undefined: a
fatih git:master ❯ cd color
color git:master ❯ go build
# github.com/fatih/color
./color.go:79: undefined: a
color git:master ❯ cd foo/bar
bar git:master ❯ pwd
/Users/fatih/Code/koding/go/src/github.com/fatih/color/foo/bar
bar git:master ❯ go build ../../.
# github.com/fatih/color
../../color.go:79: undefined: a
```

![image](https://cloud.githubusercontent.com/assets/438920/7551822/742476ba-f69f-11e4-90d4-eaac58770eff.png)

For example some users have a autocmd in their vimrc, which is automatically joining the directory of the current buffer's location. However some are in a completely different location but are working on the same buffer. In `vim-go`, what I do is, regardless of the user's directory, I enter into the current buffer's directory and execute `go build`. This makes things very easy for me, because as seen above I'll get always the correct path.

Now for `gb`, I can do the same but as reported in my first reply, it's printing differently. Here is an example:

![image](https://cloud.githubusercontent.com/assets/438920/7551846/4863903c-f6a0-11e4-9f18-2afed7638e04.png)

The error is in the `github.com/fatih/color/subcolor` package obviously, but I don't have any context to the file name.

**Comment by davecheney** [comment]
Got it, fix coming soon.
