### ISSUE TITLE
Can gb vendor standard library?

### ISSUE THREAD

**Issue by typeless** [constabulary/gb#577]
Can I vendor ${GOROOT}/src/crypto/rsa for example?

I tried, but it didn't seem to work.

**Comment by davecheney** [comment]
No. This won't work. The search order is always

$GOROOT
$PROJECT/src
$PROJECT/vendor/src

**Comment by typeless** [comment]
Is this a design choice or a missing feature?

**Comment by davecheney** [comment]
I'd say it was a design choice, but until the Go tool introduced the
ability to override GOROOT from vendor/ it wasn't really an issue.

I reguard the vendor/ behaviour as confusing and inconsistent, vendor/ can
overwrite anything, including your own code, yet GOPATH cannot override
GOROOT.

In gb things are well specified, the search order never changes, your code
cannot be overriden by something you've vendored, and noone can override
GOROOT.

**Comment by typeless** [comment]
Okay, thanks very much.
