### ISSUE TITLE
Cannot pass tags into gb test command

### ISSUE THREAD

**Issue by ceralena** [constabulary/gb#585]
`gb help test` reports this usage:

```
usage: gb test [build flags] -v [packages] [flags for test binary]
```

None of these work for me:

```
gb test '-tags integration' $pkg
gb test -tags integration $pkg
gb test $pkg -tags integration
gb test $pkg '-tags integration'
````

It's not clear to me what the correct usage is, or whether this is actually possible. If it should be possible, I guess this is a big with the documentation / generated help file, which I'm happy to submit a patch for.

**Comment by davecheney** [comment]
`gb test -tags integration $pkg` should be the correct form

**Comment by ceralena** [comment]
Thanks. I think I was on a very old gb where it didn't work.

**Comment by davecheney** [comment]
You're welcome. I think I have test coverage for this. Please feel free to
reopen this issue if you find it is not working as expected.
