### ISSUE TITLE
Command and libraries in the same repo

### ISSUE THREAD

**Issue by uluyol** [constabulary/gb#588]
Keeping libraries and associated tools in the same repo seems to be quite common. How should I set up my repos so that I can use gb for the tools but still have my libraries be go-gettable?

**Comment by davecheney** [comment]
I'm sorry that is not currently possible.

Gb is intended for projects, code that isnt imported by other code.

If you have parts of your code that you want to be go gettable, you should
move them to their own repository and structure them in a go gettable
format.
