### ISSUE TITLE
The standard pattern +build ignore is not supported

### ISSUE THREAD

**Issue by dgsb** [constabulary/gb#589]
Here is a test repository https://github.com/dgsb/gbtest
I think the expected behaviour is that the binary should not be built

**Comment by dgsb** [comment]
Here is a test repository https://github.com/dgsb/gbtest

**Comment by davecheney** [comment]
Build tags _must_ have a newline after them.

lucky(~/src/github.com/dgsb/gbtest) % env GOPATH=$(pwd) go vet ./...

src/gb_buildtag_test/main.go:1: +build comment must appear before package
clause and be followed by a blank line

**Comment by dgsb** [comment]
My mistake, it works indeed.
Sorry for the noise

**Comment by davecheney** [comment]
Not a problem, build tags are very finiky because the tools try to avoid
reading the whole file.
