### ISSUE TITLE
`gb build all` doesn't do anything [Windows]

### ISSUE THREAD

**Issue by laszlothewiz** [constabulary/gb#59]
I set up a simple project:
src/main.go
vendor/src/go-ini/ini.go

When I run `gb build all` nothing happens, no files created, no error messages. 

I ran `gb build -v=true all` and got the following:
DEBUG project root "t:\\2015\\PJT\\Golang\\CWI Automation"
DEBUG matchPackages: [t:\2015\PJT\Golang\CWI Automation\src] all
DEBUG args: []
DEBUG removing work directory: C:\Users\Laci\AppData\Local\Temp\gb086314939
DEBUG build duration: 976.6us map[]

I would be happy to debug this but don't even know where to start.

**Comment by davecheney** [comment]
Thanks for your issue report. You need to move main.go into a package. Code cannot be built at the root of src/ because that is not a package, it has no name.

**Comment by laszlothewiz** [comment]
Thank you for the quick response!

However, after moving the source files into a folder, the build fails (`cwia` is the folder I moved the files to):

    FATAL command "build" failed: failed to resolve package "cwia": cannot find package "cwia" in any of:
        C:\Go\src\pkg\cwia (from $GOROOT)
        t:\2015\PJT\Golang\CWI Automation:t:\2015\PJT\Golang\CWI Automation\vendor\src\cwia (from $GOPATH)

---
Also, could `gb` consider the .go files directly under /src as the main project files and assume the name for them to be the project directory's name?
Eg: `~/someproject/src/main.go` could generate a `someproject.exe` 
This would be ideal for small projects

**Comment by davecheney** [comment]
Possibly, but if you put your files in src/someoroject/main.go the we wouldn't have to add a special case

**Comment by laszlothewiz** [comment]
That's fine but I moved my files under a subdirectory (`cwia`) in `/src` and I got the above error when trying to build.

**Comment by davecheney** [comment]
Let me take a look tomorrow. There is a known error on windows #27 and another issue for building in src/ directly #46

**Comment by laszlothewiz** [comment]
Thanks!
