### ISSUE TITLE
gb clean command

### ISSUE THREAD

**Issue by gsquire** [constabulary/gb#590]
Do you see much utility in a clean command? I would think this could be useful when trying to get a fresh  build by removing the pkg/ and bin/ directories. The idea is similar in spirit to `go clean`.

Thanks for reading.

**Comment by davecheney** [comment]
My preference is to not automate simple, but destructive, operations liege this. 

If you want go to ignore the cache use, -f -F

**Comment by gsquire** [comment]
Ok that's fair, thanks for the input.
