### ISSUE TITLE
gb not using sub-vendored packages

### ISSUE THREAD

**Issue by nesv** [constabulary/gb#596]
Here is my situation: I have vendored `rsc.io/letsencrypt`, and it vendors its own version of `github.com/xenolf/lego/acme`. After hunting around a bit, it seems there is a modification to the sub-vendored package (i.e. `rsc.io/letsencrypt/vendor/github.com/xenolf/lego/acme`), with the `acme.TLSSNI01ChallengeCertDomain` function. (This is all just to put some context around the issue.)

When I ran
```
$ gb vendor fetch rsc.io/letsencrypt
``` 
it pulled in `github.com/xenolf/lego/acme` recursively, and is attempting to use that package, instead of the sub-vendored version at `vendor/src/rsc.io/letsencrypt/vendor/github.com/xenolf/lego/acme`.

Is there a way to get gb to use the sub-vendored version of the `acme` package?

For what it's worth, I am running Go 1.6.2 linux/amd64, and am using the latest version of gb (from `go get -v -u github.com/constabulary/gb/...`).

**Comment by davecheney** [comment]
Gb does not use the go tools vendoe support. The simplest solution is to
either copy the dependencies out of the vendor directory or vendor then
directly using -branch or -revision if necessary.

**Comment by nesv** [comment]
Okee dokee. Thanks, @davecheney :smile:
