### ISSUE TITLE
Binary not being built?

### ISSUE THREAD

**Issue by elimist** [constabulary/gb#600]
When I try building my project (`gb build`) inside the root of one of my projects, nothing happens; the `bin/` directory along with the built binary is not being created. It's odd because it's only happening inside this one project -everything builds fine in my other projects in other workspaces. 

I tried starting from scratch by deleting vendor/, pkg/, reinstalling all dependencies and building it again, but it still doesn't work. 

I'm using go1.6.2 darwin/amd64 with the latest `gb` and everything looks correct regarding `gb env`.
No errors or anything weird is outputted after `gb build`, it just fails silently.

Any idea what could cause the binary to not be built?

**Comment by davecheney** [comment]
Can you please try again with

env DEBUG=. gb build

And paste the complete output. It should be pretty straight forward to
figure it out from there.

**Comment by elimist** [comment]
ok, here is the output from `env DEBUG=. gb build`

❯ env DEBUG=. gb build
2016/06/01 16:51:57 main.go:115: args: []
2016/06/01 16:51:57 cmd.go:86: project root "/Users/elimist/projects/auth"
2016/06/01 16:51:57 import.go:20: /Users/elimist/projects/auth ..
2016/06/01 16:51:57 context.go:435: matchPackages: ...
2016/06/01 16:51:57 main.go:165: args: [github.com/elimist/auth github.com/elimist/auth/identity]
2016/06/01 16:51:58 build.go:49: build duration: 97.43µs map[]
2016/06/01 16:51:58 context.go:319: removing work directory: /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb007489542

**Comment by davecheney** [comment]
Nothing is stale so nothing is rebuilt

**Comment by elimist** [comment]
Hmm, interesting. I tried rebuilding again after modifying some source, still no `bin/` is being created.

env DEBUG=. gb build
2016/06/01 17:04:54 main.go:115: args: []
2016/06/01 17:04:54 cmd.go:86: project root "/Users/elimist/projects/auth"
2016/06/01 17:04:54 import.go:20: /Users/elimist/projects/auth ..
2016/06/01 17:04:54 context.go:435: matchPackages: ...
2016/06/01 17:04:54 main.go:165: args: [github.com/elimist/auth github.com/elimist/auth/identity]
2016/06/01 17:04:54 install.go:130: /Users/elimist/projects/auth/pkg/darwin-amd64/github.com/elimist/auth/identity.a is older than /Users/elimist/projects/auth/src/github.com/elimist/auth/identity/repository.go
2016/06/01 17:04:54 context.go:340: cd /Users/elimist/projects/auth/src/github.com/elimist/auth/identity; [/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64/compile -p github.com/elimist/auth/identity -pack -o /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb741846943/github.com/elimist/auth/identity.a -I /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb741846943 -I /Users/elimist/projects/auth/pkg/darwin-amd64 -complete cache.go config.go model.go repository.go service.go]
github.com/elimist/auth/identity
2016/06/01 17:04:54 context.go:340: cd /Users/elimist/projects/auth/src/github.com/elimist/auth; [/usr/local/Cellar/go/1.6.2/libexec/pkg/tool/darwin_amd64/compile -p github.com/elimist/auth -pack -o /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb741846943/github.com/elimist/auth.a -I /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb741846943 -I /Users/elimist/projects/auth/pkg/darwin-amd64 -complete handlers.go main.go types.go utilities.go]
github.com/elimist/auth
2016/06/01 17:04:54 build.go:49: build duration: 506.423567ms map[gc:504.807623ms]
2016/06/01 17:04:54 context.go:319: removing work directory: /var/folders/cp/35w3f3mx5hv7gq9tc8krbqkm0000gn/T/gb741846943

**Comment by davecheney** [comment]
Which is the main package?

**Comment by elimist** [comment]
the main package is `auth`

**Comment by davecheney** [comment]
Gb doesn't think that is main package, so it isn't linking it, you should
find an auth.a file in pkg/ directory.

Is the source of this project available?

**Comment by elimist** [comment]
Ah, unfortunately the code is not open for now, as per prudish company policy. 
But yeah, what you say makes sense -this was completely my fault. I had forgotten that executables always need a `package main`. Changing the auth's package name to `main` resulted in a proper build. Perhaps we could add a warning for future cases. Thanks for all your help and the quick replies -big fan of your blog!

**Comment by davecheney** [comment]
You're welcome. I don't know how to make gb detect that a main package is a
main package when the package declaration is not main. Perhaps this is
something go vet could do.
