### ISSUE TITLE
Running 'gb test -v' swallows output lines

### ISSUE THREAD

**Issue by fungl164** [constabulary/gb#605]
Hello,

When running ```gb test -v``` with the ```github.com/smartystreets/goconvey/convey``` package for example, the output skips the story lines.  The correct output appears however when running ```go test -v``` instead.  Is there a flag or a fix I am missing?
 
Thanks!

**Comment by davecheney** [comment]
I'm not familiar with goconvey. Can you please show an example of what you
expected and what you received.

**Comment by fungl164** [comment]
Hi, as you requested, here is a screenshot of what I would expect...
Thanxs @davecheney!

<img width="1454" alt="screen shot 2016-06-11 at 2 21 15 pm" src="https://cloud.githubusercontent.com/assets/1827730/15986802/3be43a26-2fe0-11e6-9dd7-5362c64bbb1a.png">

**Comment by davecheney** [comment]
Thanks, at a guess one of the output is going to stdout the rest is going
to stderr and gb test is discarding one or the other.

**Comment by fungl164** [comment]
Hi, I tried redirecting stderr to stdout on various shells (bash, zsh, fish) and still got the same results. 

Not sure what could be wrong,.  As a side note, perhaps not directly relevant but works... [modd](https://github.com/cortesi/modd) with [goconvey](https://github.com/smartystreets/goconvey/convey) and ```go test -v``` creates the correct output...thnxs!

**Comment by davecheney** [comment]
> Hi, I tried redirecting stderr to stdout on various shells (bash, zsh, fish) and still got the same results.

I don't think that will help, the problem is managing stdout/stderr when the test binary is forked by gb.

> Not sure what could be wrong,. As a side note, perhaps not directly relevant but works... modd with goconvey and go test -v creates the correct output...thnxs!

I don't know who what `modd` is. Can you please give some more details.

**Comment by fungl164** [comment]
[modd](https://github.com/cortesi/modd) is a file watcher that can trigger shell actions when it detects a file has changed.  Basically it forks a process and routes the output to stdout.  As far as I can tell it produces the same output as running ```go test -v``` directly from the shell.

**Comment by davecheney** [comment]
Thanks. This should be a pretty straight forward issue to fix, 

https://github.com/constabulary/gb/blob/master/test/test.go#L196

In fact, I'm surprised that it doesn't work already.

**Comment by davecheney** [comment]
@fungl164 oh, think i see what is happening. If you look closely on the left hand example, gb, you see four dots, corresponding to the ticks on the right hand side.

I suspect one of two things:

1. goconvey is sniffing stdout/stderr and altering it's behaviour depending on the state of the controlling terminal (ie, it's not a tty, or doesn't look enough like a tty)
2. the -v flag passed to go test has a slightly different behaviour under gb.

**Comment by davecheney** [comment]
@fungl164 it's the latter, something about the way gb is handling -v is not correct wrt. what goconvey expects.

**Comment by fungl164** [comment]
Beautiful. Thank you @davecheney!
