### ISSUE TITLE
Vendor bug?

### ISSUE THREAD

**Issue by gsquire** [constabulary/gb#628]
I ran into an issue with the latest [gb](https://github.com/constabulary/gb/commit/62ddcb9124a4f04409136c8122e1c3fab0e4cedb) when updating my vendor dependencies.

Unfortunately I am in a private repo so I can't share the manifest but I listed the steps in which the build fails. I very well could be missing something. I thought `gb vendor restore` would reload my vendor packages back to their old state. So perhaps a bug got introduced recently?

Steps:

```sh
gb vendor update -all
gb vendor restore
gb build
# Oh shoot! An upstream library broke the build, revert back to the previous manifest.
git checkout -- vendor/manifest
gb vendor restore
gb build
# Still broken?
rm -r vendor/src
gb vendor restore
gb build
# This builds fine.
```

Let me know if there is any missing information. I made sure the manifest was identical to its previous commit too just to ensure I wasn't crazy.

**Comment by davecheney** [comment]
I don't think vendor restore works like that, it only replaces your local
copy if it's missing.

Gb vendor restore has a lot of usabilities problems, I'm sorry about that.

Are your vendors dependencies checked in, git reset would probably have
worked better?

**Comment by gsquire** [comment]
No problem. I only check in the manifest to save some space in the repository so that's why I couldn't just reset it.

I checked the `vendor/src` path and noticed that the `.git` folder isn't there. So does `gb` clone a repository at a specific commit? I suppose I could dig into the code.

**Comment by davecheney** [comment]
It depends on what options you passed to gb vendor fetch as to what is
cloned onto disk. G. Deletes all the .git metadata. If you wanted to use
submodules rather than copying all your code into your project, that will
work just as well as gb doesn't care how the code gets into vendor/src/
only that it is there when it comes time to build.

**Comment by gsquire** [comment]
I see. It's not a big deal having to remove the `vendor/src` folders. I just wanted to make sure it wasn't really an issue. Thanks for your time.
