### ISSUE TITLE
Arbitrarily removal of legit .gitignore files

### ISSUE THREAD

**Issue by Dr-Terrible** [constabulary/gb#638]
When fetching [Revel](https://github.com/revel/revel) with `gb vendor fetch github.com/revel/revel`, the `.gitignore` file from https://github.com/revel/revel/tree/master/skeleton is stripped out.

Without that file, revel CLI stopped to work correctly:

> revel new github.com/user/example
> ~
> ~ revel! http://revel.github.io
> ~
> Abort: Failed to open file /home/user/myproject/vendor/src/github.com/revel/revel/skeleton/.gitignore: open /home/user/myproject/vendor/src/github.com/revel/revel/skeleton/.gitignore: no such file or directory

which in turn breaks Heroku deployment with Gb.

I think that the correct behaviour should be to have Gb removing only `.gitignore` files from the root directory of a repository, while ignoring all the others within the repo's sub-directories.

**Comment by davecheney** [comment]
Thank you for raising this issue. I the way that GB vendor strips non
source code is probably not documented at all, or sufficiently. I will try
to address this.

Being practical, fixes to GB vendor are not on the road map for the next
few months at least, so I recommend that you manually copy all of the files
that revel requires. You can also use git submodules if you are favourable
to that.

**Comment by Dr-Terrible** [comment]
@davecheney, you closed the issue, but I don't see a bug fix in the logs, nor an documentation update about the way GB vendor strips non source code.

I'm fine if you're not interested in fixing the bug, but the problem remains: GB vendor is stripping ".git*" files NOT related to Git's metadata, breaking packages. I previously reported `Revel` as an example of a package tampered by GB, but there are others too, such as `Gogs`.

I think you're missing the point, so just to be clear:

```shell
$ tree -d .
.
├── .git              <-- Git's metadata; it's OK to be stripped
├── .gitignores       <-- Git's metadata; it's OK to be stripped
└── foo
    └── bar
        └── .gitignores <-- It's not Git's metadata; it should not be stripped
```

**Comment by davecheney** [comment]
gb vendor _only_ copies `.go` files. 

gb vendor is just a convenience, you can use git submodules or just copy the code you need directly if you like.
