### ISSUE TITLE
Output for running against test file

### ISSUE THREAD

**Issue by ardan-bkennedy** [constabulary/gb#64]
I know it should not build a test file, but it should also not produce this output. It should returning something simple or nothing.

File: example3_test.go

`sh gb build -q` | done: 124.45275ms ]
	FATAL command "build" failed: [/Users/bill/go/pkg/tool/darwin_amd64/6g -p github.com/ArdanStudios/gotraining/09-testing/01-testing/example3 -pack -o /var/folders/8q/d2pfdk_x4qd4__l6gypvzsw40000gn/T/gb966307503/github.com/ArdanStudios/gotraining/09-testing/01-testing/example3.a -I /var/folders/8q/d2pfdk_x4qd4__l6gypvzsw40000gn/T/gb966307503 -I /Users/bill/Spaces/Go/Projects/pkg/darwin/amd64 -complete]: exit status 1
	usage: 6g [options] file.go...
	  -+	compiling runtime
	  -%	debug non-static initializers
	  -A	for bootstrapping, allow 'any' type
	  -B	disable bounds checking
	  -D path
<cut remaining display of 6g usage>

**Comment by davecheney** [comment]
Can you zip up that package and attach it to the issue please

**Comment by ardan-bkennedy** [comment]
The latest version of the tool has seemed to correct this. Very weird.

**Comment by davecheney** [comment]
Free bug fixes, winning!
