### ISSUE TITLE
gb vendor fetch: does not tolerate HTML-style unclosed "meta" tag

### ISSUE THREAD

**Issue by seh** [constabulary/gb#642]
When attempting to run _gb vendor fetch_ against [a remote import path _without a VCS type qualifier_](https://golang.org/cmd/go/#hdr-Remote_import_paths), the XML parser rejects a `meta` tag supplied by the server that _go get_ accepts. Specifically, if the response document contains a `meta` tag that's an XML start tag, but not an empty element or paired with a closing end tag, [_gb vendor fetch_ rejects the document as being invalid](https://github.com/constabulary/gb/blob/master/internal/vendor/discovery.go#L44). It's true; the document _is_ invalid XML, because it consists solely of an opened-but-never-closed element.

The _go get_ documentation offers this `meta` tag as an example:

```html
<meta name="go-import" content="import-prefix vcs repo-root">
```
Taken literally, that's valid HTML, but not valid XML unless it's followed by an end tag (`</meta>`). However, _go get_ accepts it, because _go get_'s parser [tolerates premature EOF so long as it already parsed at least one `go-import` directive](https://github.com/golang/go/blob/master/src/cmd/go/discovery.go#L46), whereas [_gb vendor fetch_ does not](https://github.com/constabulary/gb/blob/master/internal/vendor/discovery.go#L44).

Note that _go get_ concession came in [commit 5b085482ae8792cf751371991488d29e7bd3762f](https://github.com/golang/go/commit/5b085482ae8792cf751371991488d29e7bd3762f), in response to [issue 13683 ("cmd/go: go get uses XML parser to parse HTML")](https://github.com/golang/go/issues/13683). _gb vendor fetch_'s current code predates that fix by about five months. Would you consider accepting a port of that _go get_ fix to _gb vendor_?

**Comment by davecheney** [comment]
Thank you for reporting this issue.

**Comment by shawnzhu** [comment]
Does it fix the problem by picking up the fix from this commit from go lang? https://github.com/golang/go/commit/81a4bbffbf70edd3aaa401b38eb581ad94e2288f

Here's the gerrit change: https://go-review.googlesource.com/#/c/14482/

**Comment by seh** [comment]
I prepared a fix, porting both the change that @shawnzhu [mentions](https://github.com/constabulary/gb/issues/642#issuecomment-246362957) and the _go get_ change [I mentioned above](https://github.com/constabulary/gb/issues/642#issue-176364834) ([5b085482ae8792cf751371991488d29e7bd3762f](https://github.com/golang/go/commit/5b085482ae8792cf751371991488d29e7bd3762f)), and wrote unit tests attempting to prove that _both_ are necessary. I had a hard time finding any input that requires _both_ changes.

When using an XML parser with [`Strict`](https://golang.org/pkg/encoding/xml/#Decoder) set to false, as both _go get_ and _gb vendor_ do, the parser tolerates unquoted attribute values, which is what I thought thought was the interesting part of [this test case](https://github.com/golang/go/blob/5b085482ae8792cf751371991488d29e7bd3762f/src/cmd/go/pkg_test.go#L66). Using `Decoder.RawToken` instead of `Decoder.Token` is enough to get that test to pass in `gb vendor`, because with `RawToken` the parsing never declares premature EOF for lack of an XML end element. It takes something like an unterminated CDATA section.

It's probably useful to accommodate such a malformed document; I'm just confused as to whether [that test case in 5b085482ae8792cf751371991488d29e7bd3762f](5b085482ae8792cf751371991488d29e7bd3762f) failed without that change.

I'll submit a PR for your consideration.

**Comment by seh** [comment]
Now that #643 is merged, I'm considering this problem to be fixed.
