### ISSUE TITLE
Root detection rules allow vendor directory as a false project root.

### ISSUE THREAD

**Issue by ChrisHines** [constabulary/gb#66]
When building from inside the vendor directory `gb` would view vendor as the project root which will likely surprise many people.

**Comment by davecheney** [comment]
What should we do in that case? Exit with an error message or pretend like we were building from the project root?

**Comment by ChrisHines** [comment]
`gb build` -> error (vendored packages can only be built as a dependency of a project package)
`gb build project/package` -> behave the same as if we are building from anywhere else within the project

This rule would make it difficult to have a project actually named "vendor" with a structure such as:
```
vendor/src/...
vendor/vendor/src/...
```

**Comment by davecheney** [comment]
Short version, I recognise this is a potential problem, but I don't plan to look at it in the near or medium term, at least not until #100 is resolved, which is also a medium term issue.

**Comment by davecheney** [comment]
Closing for the moment.
