### ISSUE TITLE
Code has a compiler error but not being reported

### ISSUE THREAD

**Issue by ardan-bkennedy** [constabulary/gb#67]
The handler.SendJSON function does not exist, yet no compiler error is reported.

    package main

    import (
	    "log"
	    "net/http"
    )

    func main() {
	    Routes()

	    log.Println("listener : Started : Listening on :4000")
	    http.ListenAndServe(":4000", nil)
    }

    // Routes sets the routes for the web service.
    func Routes() {
	    http.HandleFunc("/sendjson", handler.SendJSON)
    }

**Comment by davecheney** [comment]
Can you please include a zip of the project and/or the output with -v. Could this be #46 ?

**Comment by ardan-bkennedy** [comment]
DEBUG project root "/Users/bill/Spaces/Go/Projects/src/github.com/goinaction/code"
	DEBUG matchPackages: [/Users/bill/Spaces/Go/Projects/src/github.com/goinaction/code/src] ../chapter9/listing04/...
	DEBUG args: []
	DEBUG removing work directory: /var/folders/8q/d2pfdk_x4qd4__l6gypvzsw40000gn/T/gb705588546
	DEBUG build duration: 54.501µs map[]
[ ~/Spaces/Go/Projects/src/github.com/goinaction/code/chapter9/listing04/ ] #

**Comment by ardan-bkennedy** [comment]
Ah, interesting. there is that silly src folder hanging out there that I abandoned. Let me move the code.

**Comment by ardan-bkennedy** [comment]
Sorry, it is working when the code is moved out

$ gb build
test
FATAL command "build" failed: [/Users/bill/go/pkg/tool/darwin_amd64/6g -p test -pack -o /var/folders/8q/d2pfdk_x4qd4__l6gypvzsw40000gn/T/gb913145059/test/main.a -I /var/folders/8q/d2pfdk_x4qd4__l6gypvzsw40000gn/T/gb913145059 -I /Users/bill/Spaces/Go/Projects/pkg/darwin/amd64 -complete listing04.go]: exit status 1
listing04.go:19: undefined: handle

**Comment by davecheney** [comment]
Thanks for confirming. I'll have to mark this one up to an unfortunate outcome of project root auto detection.
