### ISSUE TITLE
-ldflag support for versioning

### ISSUE THREAD

**Issue by ardan-bkennedy** [constabulary/gb#68]
We are using

    gb build -ldflags "-X main.gitTagInfo \"${REPO_VERSION}\" -X main.gitRevision \"${REPO_REV}\"" -o $@

in our Makefile to have the linker initialize main.gitTagInfo and main.GitRevision. gb build does not support the -ldflags argument, so we cannot compile the git revision info into our binary.  We do not want to sacrifice the ability to have our program support a -version flag that gives the info required to tell us exactly which revision and git tag it was built from.

We really like using -ldflags instead of having our Makefile generate a .go file.  It allows for non-makefile builds (invoking go build directly) to test that builds work, and it is not subject to the risk of accidentally using an out-of-date generated .go file left over from a previous make invocation.

**Comment by davecheney** [comment]
Duplicate #16
