### ISSUE TITLE
test fails to find standard lib import

### ISSUE THREAD

**Issue by bndw** [constabulary/gb#680]
`gb test` is failing to find the `net/http/httptest` subdirectory

```go
// src/foo/foo_test.go
package main

import (
	"net/http/httptest"
	"testing"
)

func TestFoo(t *testing.T) {
	_ = httptest.NewRequest("", "https://example.com", nil)
}
```

```sh
$ gb test -a
foo_test.go:9: undefined: httptest.NewRequest
FATAL command "test" failed: exit status 2
```

**Comment by davecheney** [comment]
I'm not able to reproduce this issue, see #681 for a test that confirms this.

**Comment by davecheney** [comment]
Hmm, looks like httptest may not have existed in 1.6 and earlier. Let me check.

**Comment by davecheney** [comment]
Yup, `httptest.NewRequest` was added in Go 1.7.

If you have upgraded your Go installation you _must_ rebuild gb. Sorry about this limitation, it's not an easy one to overcome.

**Comment by bndw** [comment]
@davecheney Thanks for the lightning fast followup and resolution!

**Comment by davecheney** [comment]
No worries.
