### ISSUE TITLE
build from a parent directory?

### ISSUE THREAD

**Issue by andrewchambers** [constabulary/gb#7]
Would something like the following be useful?

```gb ./path/to/src/my/package```

or perhaps

```gb build -c ./path/to/src/my/package # -c change working dir```

I  ran into this because I have a project with multiple languages at the root and the go projects are a sub  directory, I want to invoke gb from a top level build script.
It may also be nice to specify an alternative output directory.

I am happy to work around the issue if you don't think it is worth it.

**Comment by davecheney** [comment]
Sounds good to me, but the flag should be -r, or -R, to set the project
root.

gb build -R path/to/project {all,some/import/path}
