### ISSUE TITLE
gb support for plugins in Go 1.8

### ISSUE THREAD

**Issue by bstarynk** [constabulary/gb#700]
Go 1.8 has [plugins](https://golang.org/doc/go1.8#plugin) and a [plugin](https://golang.org/pkg/plugin/) package. With the `go` command, plugins can (and should) be compiled with `go build -buildmode=plugin` ; what is the equivalent with `gb` ? (it should be documented)

Thanks

[Basile Starynkevitch](http://starynkevitch.net/Basile/)

**Comment by davecheney** [comment]
Sorry, gb doesn't support any of the go build modes. It's not on my roadmap
to add them.

**Comment by bstarynk** [comment]
It is not a matter of supporting `go build` modes. It is a matter of supporting *plugins* (which is a new and important feature of Go 1.8 language).

**Comment by davecheney** [comment]
Real talk: plugins are pretty broken in 1.8, I'm not planning on looking at it til after 1.9

**Comment by we-zhang** [comment]
+1 for supporting go plugin in gb

**Comment by davecheney** [comment]
Being straight with you, plug-ins in go are pretty broken and only work on Linux, sorta. 

I don’t have any plans to add support for them to gb.

**Comment by davecheney** [comment]
Won’t fix. Sorry.

**Comment by bstarynk** [comment]
On 11/25/2017 04:08 AM, Dave Cheney wrote:
>
> Won’t fix. Sorry.
>


Then you need to document that. This would avoid future people coding in 
Go and using plugins to even consider using GB.

You need to mention lack of plugin support in your README.md and on the 
https://getgb.io/ site.

Cheers.

-- 
Basile STARYNKEVITCH   == http://starynkevitch.net/Basile
opinions are mine only - les opinions sont seulement miennes
Bourg La Reine, France
