### ISSUE TITLE
gb install failed on mac

### ISSUE THREAD

**Issue by yuchaoran2011** [constabulary/gb#701]
I tried the the go get command to install gb. The command ran without giving any output, so I supposed the installation was successful. But when I ran "gb", I got error "gb: command not found". I checked under /usr/local/go/, which is my GOPATH, gb is not there.

More context:
I installed Go using the GUI installer provided on the official website. I've verified that the installer did set GOPATH correctly and put it in PATH as well. I got "go version go1.8 darwin/amd64" after running "go version"

I also tried to clone the gb repo and use "go build" and then "go install" to install it, but the build failed with error "use of internal package not allowed".

Can anyone help me here?

**Comment by dcheney-atlassian** [comment]
Can you please post the complete output of

  go install -v github.com/constabulary/gb/...

**Comment by yuchaoran2011** [comment]
I just tried the command. The -v flag didn't seem to help. I got nothing in the output. The command seemed to have succeeded, but gb was still not installed.

**Comment by dcheney-atlassian** [comment]
> I got nothing in the output. 

ok, if there was no output then there is nothing to compile. Check that `$GOPATH/bin/` is your `$PATH`

**Comment by yuchaoran2011** [comment]
I found ":/usr/local/go/bin:" as a substring of "echo $PATH".

**Comment by yuchaoran2011** [comment]
$GOPATH is not defined in my environment though, but $GOPATH/bin/ is in the $PATH

**Comment by dcheney-atlassian** [comment]
Then you need to add `$HOME/go/bin` to your path.

I've raised a bug on the Go project as this is no longer mentioned in the installation instructions.

**Comment by yuchaoran2011** [comment]
Thanks for the prompt help! It's working now!
