### ISSUE TITLE
gb is installed using go, but when i hit gb command, "command not found" error coming

### ISSUE THREAD

**Issue by jibinpjohn** [constabulary/gb#704]
Hello,

I have installed the gb using the go tool. However when I hit the gb command, "command not found" error coming. Should i set any PATH variables ?

Here are the commands, i have executed.
-----------------------------------------------------------------------------------
root@DAEDALUS-STUD-U:~# go get github.com/constabulary/gb/...
root@DAEDALUS-STUD-U:~# ls
Bilder     Downloads  Musik       Schreibtisch  Vorlagen
Dokumente  go         Öffentlich  Videos
root@DAEDALUS-STUD-U:~# gb
gb: Befehl nicht gefunden.
root@DAEDALUS-STUD-U:~#

**Comment by davecheney** [comment]
Is `$GOPATH/bin` in your `$PATH`?

**Comment by davecheney** [comment]
Specially add /root/go/bin to your $PATH

**Comment by jibinpjohn** [comment]
Many thanks,It worked.

root@DAEDALUS-STUD-U:~/go/bin# export PATH=$PATH:/root/go/bin
root@DAEDALUS-STUD-U:~/go/bin# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go/bin
root@DAEDALUS-STUD-U:~/go/bin# gb
gb, a project based build tool for the Go programming language.

Usage:

        gb command [arguments]

Can you close the issue ?
