### ISSUE TITLE
gb test is broken on darwin

### ISSUE THREAD

**Issue by timperrett** [constabulary/gb#705]
Hi there! long time user of gb, its a great tool - thanks for making it! For some reason, new `go get` on OSX is broken and `test` command no longer works. Here's the output:

```
gb test -v
_testmain.go:58: cannot use matchString (type func(string, string) (bool, error)) as type testing.testDeps in argument to testing.MainStart:
        func(string, string) (bool, error) does not implement testing.testDeps (missing MatchString method)
FATAL: command "test" failed: exit status 2
make: *** [test] Error 1
```

Thanks in advance for any information.

**Comment by davecheney** [comment]
Thanks for logging this issue. Which version of Go are you using?

**Comment by timperrett** [comment]
Hey @davecheney - so we figured out the issue: under Go 1.8, we get the aforementioned issue. With Go 1.7, its all golden. Moreover, what's weird is that Go 1.8 with Linux works fine, but on darwin it explodes. 

Hope this helps - happy to provide any additional information needed.

**Comment by davecheney** [comment]
It could be a mismatch between the version of go you have installed,
and the version of go that compiled gb. The easiest way to fix this is
to

1. make sure you unset GOROOT ( never ever set GOROOT )
2. run go version, check that it's the version you expect
3. go get -u github.com/constabulary/gb/...

**Comment by timperrett** [comment]
Thanks @davecheney you were right - should not have been setting the GOROOT. Not doing this, and updating the `gb` worked. Sorry for the noise, and thanks for the continued efforts on this great tool.
