### ISSUE TITLE
Question: customize `src` directory?

### ISSUE THREAD

**Issue by roxma** [constabulary/gb#708]
Hi, nice project here

I just read the [usage documentation](https://getgb.io/docs/usage/) on how the project root is detected

> gb automatically detects your project’s root directory based on your current working directory.

> A gb project is defined as any directory that contains a src/ subdirectory. gb automatically detects the root of the project by looking at the current working directory and walking backwards until it finds a directory that contains a src/ subdirectory.

I'm working on a project written in in golang and c++, they are run as independent process, communicating over unix socket. Currently they are put in saparate directories, like `$PROJECT/goserver` `$PROJECT/cppserver`. It would be wierd to rename `$PROJECT/goserver` to `$PROJECT/src` if I need to use `gb`. Is there any way to customize the name of `src` directory?

**Comment by dcheney-atlassian** [comment]
I'm afraid not, `src/` is used as the sentinal to find the root of the gb project.
