### ISSUE TITLE
How to track vendor packages' git version?

### ISSUE THREAD

**Issue by AlexanderChen1989** [constabulary/gb#71]
Is there a recommended way to track vendor packages' version?

**Comment by davecheney** [comment]
At the moment the best way to do this is probably to use git submodules or subversions (depending on your preference). 

gb doesn't mandate that you do this, in fact gb doesn't mandate which DVCS you use (although obviously not using source control would be short sighted). 

In the future `gb-vendor` may be able to help here, and it may be able to emit a file which records the revision of code vendored.

**Comment by tsenart** [comment]
:+1: to extend gb-vendor with sane DVCS integrations.

**Comment by davecheney** [comment]
I wanted to include a comment I wrote on constabulary/gb-vendor#3

---

Thanks Toby but I'm worried this won't work in several common cases

the project owner has followed our instructions and checked all their source into a new repository, they won't have the .git or .hg metadata so this call will fail. And then we'll have to document this case.

if project owners have set their project up using submodules / subtrees, this will also fail, in a really unexpected way.

I'm sorry for being very cautious with gb-vendor, it's going to be very easy to get it wrong and create a crappier experience. gb-vendor should be able to do this, but it needs to do this by recording the details about packages it vendored, not relying on the DVCS metadata to be present.

---

The take away is, gb cares about building projects laid out in the prescribed format. gv-vendor will grow and change to not just shell out to go get, but to manage revisions vendored. 

This is quite a big job, and it's not top of my list (although it can be top of someone else's list). So for the moment, if your workflow supports it, submodules, subtrees, subsomethings, are the best solution.

**Comment by tsenart** [comment]
http://godoc.org/golang.org/x/tools/go/vcs

**Comment by davecheney** [comment]
The new version of `gb vendor` tracks the remote location the source was vendored from.

**Comment by tsenart** [comment]
Great! Thanks for this!

**Comment by davecheney** [comment]
You can use gb vendor list to get a report of the current dependencies. It
supports a -f flag to customise the output.
