### ISSUE TITLE
Windows commands need to end in .exe

### ISSUE THREAD

**Issue by jhyoon0801** [constabulary/gb#72]
Now, gb can build a project on windows, but the output( specially executable program ) suffix is non. So if I want to execute the program, I have to change the file name. ( to need the one more step )
I think if the code( gc.go:103 or ... ) changed, everything is happy! thanks :)

+ Sorry for my poor English..

**Comment by davecheney** [comment]
Thanks. I forgot that programs in windows have to end in `.exe`, I'll fix this.
