### ISSUE TITLE
Support 'src/foo/...' paths for gb build

### ISSUE THREAD

**Issue by mpe** [constabulary/gb#73]
With the following layout:

```
src
└── foo
    └── main.go
```

As a noob I expect to be able to do:

```
$ gb build src/foo/main.go
```

and/or:

```
$ gb build src/foo
```

Neither of these currently work. eg:

```
2015/05/12 19:22:35 command "build" failed: failed to resolve package "src/foo": cannot find package "src/foo" in any of:
	/usr/lib/go/src/src/foo (from $GOROOT)
	/home/user/gb-project/src/src/foo (from $GOPATH)
	/home/user/gb-project/vendor/src/src/foo
````

The error message is fairly clear, there's a double ```src/src``` in there, but it still took me a while to notice my error. It seems like it would be fairly easy for the tool to work this out for you and DTRT.

**Comment by davecheney** [comment]
Gb always works on import paths, try

gb build foo

Or the simpler

gb build all

**Comment by davecheney** [comment]
The error message is pretty bad at the moment because I'm reusing `go/build`. I'll be able improve that in a few weeks when I write a replacement package parser.

**Comment by davecheney** [comment]
This is now a dup of #306. This will improve the error messages. I don't think there is anything more to do here.
