### ISSUE TITLE
horizon

### ISSUE THREAD

**Issue by PiotrFerenc** [constabulary/gb#734]
i try build horizon but i have errors. Please help me, my friends :)
issue
https://travis-ci.org/stellar/horizon/jobs/350571522#L601
source:
https://github.com/openbankit/horizon

system:
Debian9

**Comment by tianon** [comment]
Looks like it's failing to find the exact commit of one of the
dependencies; maybe updating that one to a more recent commit would work?

Have you verified that the offending package still exists and wasn't yanked
or moved?

**Comment by PiotrFerenc** [comment]
all packages exist and are the latest :(
https://github.com/openbankit/horizon/blob/master/vendor/manifest

**Comment by tianon** [comment]
The build job you posted is building from https://github.com/stellar/horizon/blob/master/vendor/manifest, and the reference it's failing on is commit `ff4a55a20a86994118644bbddc6a216da193cc13`, which is from https://github.com/visionmedia/go-debug, which only has a single commit, and `ff4a55a20a86994118644bbddc6a216da193cc13` is not the reference for it.

**Comment by PiotrFerenc** [comment]
Yesssss ! Thanks @tianon  :)
