### ISSUE TITLE
using gb to make a library

### ISSUE THREAD

**Issue by rbucker** [constabulary/gb#735]
is ```gb``` only meant for creating an executable? What about creating libraries? I cannot seem to create a library using the project folder that can be imported in another project.  Even the examples do not force the source in that way. (I'm getting failed to import errors)

**Comment by davecheney** [comment]
Sorry, gb is for projects only at this point; code that produces
executables.

**Comment by rbucker** [comment]
After spending hours on this I cannot say I read that in the doc. Thank I'll close.
