### ISSUE TITLE
gb-init: new plugin

### ISSUE THREAD

**Issue by davecheney** [constabulary/gb#75]
As part of the discussion in #48 it was decided to create a new plugin, `gb-init` that would create the basic skeleton of a project. 

gb-init should take a flag or parameter for the name of the initial package in the project and have a reasonable default.
```
% mkdir $HOME/project
% cd $HOME/project
% gb init -p helloworld
% tree
lucky(~/project) % tree
.
├── src
│   └── helloworld
└── vendor
    └── src
```

Something like this

**Comment by mariokostelac** [comment]
If we want to run that with `gb init`, we need to create a way to run it without getting
`FATAL could not locate project root: could not find project root in "/Users/mario/tmp" or its parents`

**Comment by davecheney** [comment]
Yup. This will probably need tighter integration with cmd/gb. 

We either have to

 A. Not assume every plugin is executing inside a project.
B. Write go init as a sub command inside cmd/gb.

The latter is probably better.

**Comment by Supermighty** [comment]
Before I saw this issue I wrote gb-new, a plugin to do something like this. https://github.com/Supermighty/gb-new

We can use what I've written as a starting point.

**Comment by Supermighty** [comment]
I've played around with this a bit more; using gb's command tools, and I have the error where no root is found. Though I'm not getting an error, it's just stalling out. It does work when I run `gb new` in a directory with an `src/` directory. 

Unless we pass in a special "no root" case for `FindProjectroot` we would have to bypass `cmd.RunCommand`.

**Comment by davecheney** [comment]
I'm thinking that this might be a case where this could not be written as a
plugin. I'd rather not add a general setting for not detecting the project
root.

**Comment by Supermighty** [comment]
I'm not sure it has to be a plugin. My [first pass](https://github.com/Supermighty/gb-new/blob/fd220630d54c16c0aa62d98cc8360b71764c2481/main.go) at this worked at creating the skel by not importing or using any `gb` resources. It bypassed it all.

- Does it need to know anything about a gb project, or can it just be dumb and create directories and files. 
- Could a "plugin" that doesn't really plug-in be the way to go?
- What does the plugin gain by using `cmd.RunCommand` and the like?

Sitenote: My idea for this differs than your example at the beginning of this issue; I have the command creating the project directory, where as you have that manually created, though both could be accommodated in a single tool.

**Comment by davecheney** [comment]
Timed out. IMO creating a gb project can be performed with `mkdir -p $PROJECT/src`. As I won't have any time to work on this til next year, I'm closing it.
