### ISSUE TITLE
-tags support

### ISSUE THREAD

**Issue by drewwells** [constabulary/gb#81]
Does gb plan to support custom build constraints? ie `go build -tags dev` mentioned here: http://golang.org/pkg/go/build/#Context

**Comment by davecheney** [comment]
Short answer, not yet, but it is definitely on the plan.

**Comment by mborho** [comment]
+1

It's not possible to build static linked binaries with gb at the moment. Or am I wrong?

**Comment by davecheney** [comment]
If your version of go was built with cgo enabled then at the moment the
binaries produced by gb may not be static.

**Comment by mborho** [comment]
@davecheney thanks, I've found a way to build a static binary now:

GOPATH=/path/to/gb/project/vendor:/path/to/project CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extld ld -extldflags -static' -a -x .

**Comment by davecheney** [comment]
Yup, that'll work for the moment.

I hope that I can provide a significantly simpler experience,
-installsuffux is quite gross.

**Comment by drewwells** [comment]
Lol popular request. Thanks looks great!
