### ISSUE TITLE
Import cycles not detetcted

### ISSUE THREAD

**Issue by markuslindenberg** [constabulary/gb#83]
`gb` will hang when I have import cycles in my code, while go will detect this and refuse to build:

```
$ find .
.
./src
./src/bar
./src/bar/bar.go
./src/foo
./src/foo/foo.go

$ cat src/foo/foo.go 
package main

import _ "bar"

func main() {
}

$ cat src/bar/bar.go 
package bar

import "bar"

$ export GOPATH=$(pwd)
$ go install foo
import cycle not allowed
package foo
	imports bar
	imports bar
$ gb build foo
```

`gb` will hang with 100% CPU usage on one core.

**Comment by mariokostelac** [comment]
Working on that.

**Comment by davecheney** [comment]
Sorry about that, the code in loadPackage passes down a map to track import
loops, but it isn't hooked up yet.

**Comment by markuslindenberg** [comment]
Yeah, thanks so much and thanks for `gb`, love it. :+1:
