### ISSUE TITLE
[hack] Heroku buildpack for gb projects

### ISSUE THREAD

**Issue by paxan** [constabulary/gb#85]
I've hacked this contraption:
https://github.com/paxan/heroku-buildpack-gb

Hope this helps. It's pretty primitive and doesn't do `-tags heroku` yet, nor has any C compilation like the official Go buildpack does.

Demo:
```
$ git push heroku master
Counting objects: 557, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (381/381), done.
Writing objects: 100% (557/557), 234.41 KiB | 0 bytes/s, done.
Total 557 (delta 239), reused 227 (delta 143)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> gb-project app detected
remote: -----> Installing go1.4.2... done
remote: -----> Running: vendor/bin/gb build all
remote:        code.google.com/p/go-uuid/uuid
... private packages elided ...
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing... done, 2.1MB
remote: -----> Launching... done, v4
remote:        https://mighty-refuge-5518.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
```

**Comment by paxan** [comment]
cc: @freeformz (since you mentioned the need for the buildpack)

**Comment by davecheney** [comment]
This is great!

I don't know if the constabulary org is the right place for it. But I'm
happy to write this up and link to it from the examples section on getgb.io

**Comment by paxan** [comment]
Cool. Didn't mean to imply it needs to be in constabulary org. It can stay under my acct for now.

**Comment by freeformz** [comment]
Why don't you PR heroku/heroku-buildpack-go?


    _____________________________

**Comment by davecheney** [comment]
No worries. No offence taken, I'm delighted t stoke your enthusiasm.

**Comment by paxan** [comment]
@freeformz I shall try. I wanted to get the simple version going since I have some apps I want on gb, right now.

**Comment by mariokostelac** [comment]
+1 for PR to heroku/heroku-buildpack-go.

**Comment by freeformz** [comment]
@paxan Great, looking forward to it.

**Comment by davecheney** [comment]
@paxan I'm going to close this for now. I know @freeformz is working on it, and this won't live in the gb project anyway. Please reopen if you disagree.

**Comment by paxan** [comment]
:+1:

**Comment by paxan** [comment]
@freeformz I haven't done much on trying to incorporate this into `heroku-buildpack-go` except a real ugly local hack which boils down to:

```diff
diff --git a/bin/compile b/bin/compile
index 212d3ac..0eb3a85 100755
--- a/bin/compile
+++ b/bin/compile
@@ -3,6 +3,13 @@
 
 set -eo pipefail
 
+# If this looks like Gb-style project-based Go app, run gb-compile
+# instead.
+if test -n "$(find "$1" -type f -name '*.go' | egrep "$1/(src|vendor/src)" | sed 1q)"
+then
+    exec "$(dirname ${BASH_SOURCE[0]})/gb-compile" "$@"
+fi
+
 # Go releases for Darwin beginning with 1.2rc1
 # have included more than one build, depending
 # on the specific version of Mac OS X. Try to
```

And `gb-compile` that is getting `exec`-ed is the verbatim copy of:
https://github.com/paxan/heroku-buildpack-gb/blob/master/bin/compile

@davecheney tells me you've started working on this. If so, I can help with testing it or whatever. Let me know.

**Comment by freeformz** [comment]
@paxan @davecheney said (at gophercon) that he's going to make a "gb detect" or some such command that I could use to determine if gb thinks it can build a repo. If he delivers that I'll add support in the buildpack, at least experimentally to start.

Technically I guess that's not a blocker, but I'd rather use / rely on something from @davecheney then looking for src/ and vendor/src directories as part of the official buildpack.

**Comment by paxan** [comment]
`gb detect` would require obtaining the `gb` binary at detect time, wouldn't it?

The buildpack I wrote takes a somewhat unorthodox approach: it assumes `gb` itself is also vendored under `proj/vendor/src/...`, so by design, `gb` source is there already, but needs to be bootstrapped with:

    GOPATH="$(pwd)/vendor" go install github.com/constabulary/gb/...

**Comment by davecheney** [comment]
yup, that's gb info
