### ISSUE TITLE
cmd/gb: -toolchain option unused

### ISSUE THREAD

**Issue by mvdan** [constabulary/gb#9]
The -toolchain option in cmd/gb seems to be unused at the moment. Is this intentional?

```
toolchain = fs.String("toolchain", "gc", "choose go compiler toolchain")
```

**Comment by davecheney** [comment]
It is unused at the moment, but in the future i want to support gccgo and
llgo. there is also the null toolchain, which I was using for testing, but
is probably hard to use in practice.
