### ISSUE TITLE
How to distinguish between a go and gb project?

### ISSUE THREAD

**Issue by fatih** [constabulary/gb#93]
Say we have our code inside a `src` folder:

```
~/foo/src/github.com/fatih/color
```

Our root folder is:

```
~/foo
```

Can we say that this is a gb project if all or some of followings are true:

1. `$GB_PROJECT_DIR` is equal to `~/foo`
2. `$GOPATH` is not equal to `~/foo`
3. There is a `vendor` folder in the form of: `~/foo/src/vendor` (I'm not sure about this though,there might be a source code that doesn't have any kind of vendorized code, thus not `vendor` folder at all)

I have a function to find out the root project folder of a given go file, however I need to be sure I'm dealing with a `gb` project. Because it might be also a file inside a `$GOPATH`. 

This clarifications are needed so I can make `godef` and many other tools automatically play nice with `gb` project. For example `godef` should jump to the vendored file inside the `$PROJECT` instead of to a file inside `$GOPATH`

In the docs it says: `A gb project is a folder on disk that contains a sub directory named src/`. This explanation is also true for any `$GOPATH` go project.

**Comment by davecheney** [comment]
Sorry for the brief reply, mobile.

The project directory is ~/foo/, not ~/foo/src/. The project detection rule
says the project root is the parent of a directory called src/

**Comment by fatih** [comment]
Totally right, I've fixed the paths. The questions are still valid.

**Comment by davecheney** [comment]
I'll take a look when I get home.

**Comment by fatih** [comment]
Relates issue https://github.com/constabulary/gb/issues/53.

**Comment by davecheney** [comment]
I believe that `gb info` contains all the information needed.
