### ISSUE TITLE
Support for the race detector

### ISSUE THREAD

**Issue by ardan-bkennedy** [constabulary/gb#96]
Having the ability to run gb build and gb test with the -race option. This is an important tool that everyone should be using.

**Comment by davecheney** [comment]
Shouldn't be a problem but it is blocked by cgo support and figuring out
what to do hashing build tags to make conditional compilation sane.

**Comment by rmrio** [comment]
Any news, guys?

**Comment by davecheney** [comment]
It's on the list, below finishing gb-vendor and cgo support.

**Comment by falzm** [comment]
I would also like this to be implemented in `gb build`, please.

**Comment by dlclark** [comment]
I *think* the pre-reqs for this one are completed now.  Any thoughts on this?

**Comment by davecheney** [comment]
Yup, the big blocker was tag support which is now done.

**Comment by tylerb** [comment]
Very excited about this. Just finished migrating my day job project to gb, and I miss running race on all my tests.

**Comment by sevein** [comment]
You probably know this :) but I've worked around this by updating my GOPATH, just in case someone gets stuck here.
