### ISSUE TITLE
Building platform specific code

### ISSUE THREAD

**Issue by davidkaya** [constabulary/gb#98]
Hello, I am using this package https://github.com/andrewtj/dnssd. The problem is that when I call `gb build all` I get following error:
`2015/05/16 10:16:02 command "build" failed: [/usr/local/go/pkg/tool/darwin_amd64/6g -p github.com/andrewtj/dnssd -pack -o /var/folders/x6/5l2hmn513bnblpxbrjtf5j380000gn/T/gb885390207/github.com/andrewtj/dnssd.a -I /var/folders/x6/5l2hmn513bnblpxbrjtf5j380000gn/T/gb885390207 -I <PATH_TO_PROJECT>/pkg/darwin/amd64 browse.go dnssd.go errors.go poller.go queryrecord.go register.go resolve.go]: exit status 1
poller.go:19: undefined: platformPollServerState`

The package contains platform specific file (`os_unix.go`) which contains build tag `// +build darwin freebsd linux netbsd openbsd` (https://github.com/andrewtj/dnssd/blob/master/os_unix.go), however `gb build all` does not seem to include the file in the compiling.

I am using Mac OS X.

Is this issue in `gb` or am I missing something?

Thanks a lot

**Comment by davecheney** [comment]
Can you try again with the latest revision. I think this is related to
incomplete cgo support. If I'm right you should receive a better error
message.

Cgo support is #92, and in progress now.

**Comment by davidkaya** [comment]
Now I get `FATAL command "build" failed: github.com/andrewtj/dnssd: cgo not suppored, see https://github.com/constabulary/gb/issues/12`. 
Thanks for the fast response. I am really looking forward for the cgo support.

**Comment by davecheney** [comment]
Initial cgo support is landing in #103
